/* Copyright 2022 - Generated by convert_keymap_extras_header.js
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

export default {
  /*
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ ` │ 1 │ 2 │ 3 │ 4 │ 5 │ 6 │ 7 │ 8 │ 9 │ 0 │ - │ = │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │ Q │ W │ E │ R │ T │ Y │ U │ I │ O │ P │ [ │ ] │  \  │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴─────┤
   * │      │ A │ S │ D │ F │ G │ H │ J │ K │ L │ ; │ ' │        │
   * ├──────┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴────────┤
   * │        │ Z │ X │ C │ V │ B │ N │ M │ , │ . │ / │          │
   * ├────┬───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  KC_GRV: { name: '~\n`', title: '` and ~' },
  KC_1: { name: '!\n1', title: '1 and !' },
  KC_2: { name: '@\n2', title: '2 and @' },
  KC_3: { name: '#\n3', title: '3 and #' },
  KC_4: { name: '$\n4', title: '4 and $' },
  KC_5: { name: '%\n5', title: '5 and %' },
  KC_6: { name: '^\n6', title: '6 and ^' },
  KC_7: { name: '&\n7', title: '7 and &' },
  KC_8: { name: '*\n8', title: '8 and *' },
  KC_9: { name: '(\n9', title: '9 and (' },
  KC_0: { name: ')\n0', title: '0 and )' },
  KC_MINS: { name: '_\n-', title: '- and _' },
  KC_EQL: { name: '+\n=', title: '= and +' },
  // Row 2
  KC_Q: { name: 'Q', title: 'q and Q' },
  KC_W: { name: 'W', title: 'w and W' },
  KC_E: { name: 'E', title: 'e and E' },
  KC_R: { name: 'R', title: 'r and R' },
  KC_T: { name: 'T', title: 't and T' },
  KC_Y: { name: 'Y', title: 'y and Y' },
  KC_U: { name: 'U', title: 'u and U' },
  KC_I: { name: 'I', title: 'i and I' },
  KC_O: { name: 'O', title: 'o and O' },
  KC_P: { name: 'P', title: 'p and P' },
  KC_LBRC: { name: '{\n[', title: '[ and {' },
  KC_RBRC: { name: '}\n]', title: '] and }' },
  KC_BSLS: { name: '|\n\\', title: '\\ and |' },
  // Row 3
  KC_A: { name: 'A', title: 'a and A' },
  KC_S: { name: 'S', title: 's and S' },
  KC_D: { name: 'D', title: 'd and D' },
  KC_F: { name: 'F', title: 'f and F' },
  KC_G: { name: 'G', title: 'g and G' },
  KC_H: { name: 'H', title: 'h and H' },
  KC_J: { name: 'J', title: 'j and J' },
  KC_K: { name: 'K', title: 'k and K' },
  KC_L: { name: 'L', title: 'l and L' },
  KC_SCLN: { name: ':\n;', title: '; and :' },
  KC_QUOT: { name: '"\n\'', title: '\' and "' },
  // Row 4
  KC_Z: { name: 'Z', title: 'z and Z' },
  KC_X: { name: 'X', title: 'x and X' },
  KC_C: { name: 'C', title: 'c and C' },
  KC_V: { name: 'V', title: 'v and V' },
  KC_B: { name: 'B', title: 'b and B' },
  KC_N: { name: 'N', title: 'n and N' },
  KC_M: { name: 'M', title: 'm and M' },
  KC_COMM: { name: '<\n,', title: ', and <' },
  KC_DOT: { name: '>\n.', title: '. and >' },
  KC_SLSH: { name: '?\n/', title: '/ and ?' },

  /* Shifted symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ ~ │ ! │ @ │ # │ $ │ % │ ^ │ & │ * │ ( │ ) │ _ │ + │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │   │   │   │   │   │   │   │   │   │   │ { │ } │  |  │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴─────┤
   * │      │   │   │   │   │   │   │   │   │   │ : │ " │        │
   * ├──────┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴────────┤
   * │        │   │   │   │   │   │   │   │ < │ > │ ? │          │
   * ├────┬───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  'S(KC_GRV)': { name: '~', title: '~' },
  KC_TILD: { name: '~', title: '~' },
  'S(KC_1)': { name: '!', title: '!' },
  KC_EXLM: { name: '!', title: '!' },
  'S(KC_2)': { name: '@', title: '@' },
  KC_AT: { name: '@', title: '@' },
  'S(KC_3)': { name: '#', title: '#' },
  KC_HASH: { name: '#', title: '#' },
  'S(KC_4)': { name: '$', title: '$' },
  KC_DLR: { name: '$', title: '$' },
  'S(KC_5)': { name: '%', title: '%' },
  KC_PERC: { name: '%', title: '%' },
  'S(KC_6)': { name: '^', title: '^' },
  KC_CIRC: { name: '^', title: '^' },
  'S(KC_7)': { name: '&', title: '&' },
  KC_AMPR: { name: '&', title: '&' },
  'S(KC_8)': { name: '*', title: '*' },
  KC_ASTR: { name: '*', title: '*' },
  'S(KC_9)': { name: '(', title: '(' },
  KC_LPRN: { name: '(', title: '(' },
  'S(KC_0)': { name: ')', title: ')' },
  KC_RPRN: { name: ')', title: ')' },
  'S(KC_MINS)': { name: '_', title: '_' },
  KC_UNDS: { name: '_', title: '_' },
  'S(KC_EQL)': { name: '+', title: '+' },
  KC_PLUS: { name: '+', title: '+' },
  // Row 2
  'S(KC_LBRC)': { name: '{', title: '{' },
  KC_LCBR: { name: '{', title: '{' },
  'S(KC_RBRC)': { name: '}', title: '}' },
  KC_RCBR: { name: '}', title: '}' },
  'S(KC_BSLS)': { name: '|', title: '|' },
  KC_PIPE: { name: '|', title: '|' },
  // Row 3
  'S(KC_SCLN)': { name: ':', title: ':' },
  KC_COLN: { name: ':', title: ':' },
  'S(KC_QUOT)': { name: '"', title: '"' },
  KC_DQUO: { name: '"', title: '"' },
  // Row 4
  'S(KC_COMM)': { name: '<', title: '<' },
  KC_LT: { name: '<', title: '<' },
  'S(KC_DOT)': { name: '>', title: '>' },
  KC_GT: { name: '>', title: '>' },
  'S(KC_SLSH)': { name: '?', title: '?' },
  KC_QUES: { name: '?', title: '?' },

  /* Other keys */
  KC_NUHS: { name: '~\n#', title: 'Non-US # and ~' },
  'S(KC_NUHS)': { name: '~', title: '~' },
  KC_NUBS: { name: '|\n\\', title: 'Non-US \\ and |' },
  'S(KC_NUBS)': { name: '|', title: '|' },

  SC_LSPO: { name: 'LS / (', title: 'Left Shift when held, ( when tapped' },
  SC_RSPC: { name: 'RS / )', title: 'Right Shift when held, ) when tapped' },
  SC_LCPO: { name: 'LC / (', title: 'Left Control when held, ( when tapped' },
  SC_RCPC: { name: 'RC / )', title: 'Right Control when held, ) when tapped' },
  SC_LAPO: { name: 'LA / (', title: 'Left Alt when held, ( when tapped' },
  SC_RAPC: { name: 'RA / )', title: 'Right Alt when held, ) when tapped' },

  QK_GESC: {
    name: '`/~\nEsc',
    title: 'Esc normally, but ` when GUI is active or ~ when Shift is active'
  }
};
