/* Copyright 2022 - Generated by convert_keymap_extras_header.js
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

export default {
  /*
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ ` │ 1 │ 2 │ 3 │ 4 │ 5 │ 6 │ 7 │ 8 │ 9 │ 0 │ - │ = │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │ Q │ W │ E │ R │ T │ Y │ U │ I │ O │ P │ [ │ ] │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │ A │ S │ D │ F │ G │ H │ J │ K │ L │ ; │ ' │ # │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │ \ │ Z │ X │ C │ V │ B │ N │ M │ , │ . │ / │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  KC_GRV: { name: '¬\n`', alias: 'IE_GRV', title: '` and ¬' },
  KC_1: { name: '!\n1', alias: 'IE_1', title: '1 and !' },
  KC_2: { name: '"\n2', alias: 'IE_2', title: '2 and "' },
  KC_3: { name: '£\n3', alias: 'IE_3', title: '3 and £' },
  KC_4: { name: '$\n4', alias: 'IE_4', title: '4 and $' },
  KC_5: { name: '%\n5', alias: 'IE_5', title: '5 and %' },
  KC_6: { name: '^\n6', alias: 'IE_6', title: '6 and ^' },
  KC_7: { name: '&\n7', alias: 'IE_7', title: '7 and &' },
  KC_8: { name: '*\n8', alias: 'IE_8', title: '8 and *' },
  KC_9: { name: '(\n9', alias: 'IE_9', title: '9 and (' },
  KC_0: { name: ')\n0', alias: 'IE_0', title: '0 and )' },
  KC_MINS: { name: '_\n-', alias: 'IE_MINS', title: '- and _' },
  KC_EQL: { name: '+\n=', alias: 'IE_EQL', title: '= and +' },
  // Row 2
  KC_Q: { name: 'Q', alias: 'IE_Q', title: 'q and Q' },
  KC_W: { name: 'W', alias: 'IE_W', title: 'w and W' },
  KC_E: { name: 'E', alias: 'IE_E', title: 'e and E' },
  KC_R: { name: 'R', alias: 'IE_R', title: 'r and R' },
  KC_T: { name: 'T', alias: 'IE_T', title: 't and T' },
  KC_Y: { name: 'Y', alias: 'IE_Y', title: 'y and Y' },
  KC_U: { name: 'U', alias: 'IE_U', title: 'u and U' },
  KC_I: { name: 'I', alias: 'IE_I', title: 'i and I' },
  KC_O: { name: 'O', alias: 'IE_O', title: 'o and O' },
  KC_P: { name: 'P', alias: 'IE_P', title: 'p and P' },
  KC_LBRC: { name: '{\n[', alias: 'IE_LBRC', title: '[ and {' },
  KC_RBRC: { name: '}\n]', alias: 'IE_RBRC', title: '] and }' },
  // Row 3
  KC_A: { name: 'A', alias: 'IE_A', title: 'a and A' },
  KC_S: { name: 'S', alias: 'IE_S', title: 's and S' },
  KC_D: { name: 'D', alias: 'IE_D', title: 'd and D' },
  KC_F: { name: 'F', alias: 'IE_F', title: 'f and F' },
  KC_G: { name: 'G', alias: 'IE_G', title: 'g and G' },
  KC_H: { name: 'H', alias: 'IE_H', title: 'h and H' },
  KC_J: { name: 'J', alias: 'IE_J', title: 'j and J' },
  KC_K: { name: 'K', alias: 'IE_K', title: 'k and K' },
  KC_L: { name: 'L', alias: 'IE_L', title: 'l and L' },
  KC_SCLN: { name: ':\n;', alias: 'IE_SCLN', title: '; and :' },
  KC_QUOT: { name: "@\n'", alias: 'IE_QUOT', title: "' and @" },
  KC_NUHS: { name: '~\n#', alias: 'IE_HASH', title: '# and ~' },
  // Row 4
  KC_NUBS: { name: '|\n\\', alias: 'IE_BSLS', title: '\\ and |' },
  KC_Z: { name: 'Z', alias: 'IE_Z', title: 'z and Z' },
  KC_X: { name: 'X', alias: 'IE_X', title: 'x and X' },
  KC_C: { name: 'C', alias: 'IE_C', title: 'c and C' },
  KC_V: { name: 'V', alias: 'IE_V', title: 'v and V' },
  KC_B: { name: 'B', alias: 'IE_B', title: 'b and B' },
  KC_N: { name: 'N', alias: 'IE_N', title: 'n and N' },
  KC_M: { name: 'M', alias: 'IE_M', title: 'm and M' },
  KC_COMM: { name: '<\n,', alias: 'IE_COMM', title: ', and <' },
  KC_DOT: { name: '>\n.', alias: 'IE_DOT', title: '. and >' },
  KC_SLSH: { name: '?\n/', alias: 'IE_SLSH', title: '/ and ?' },

  /* Shifted symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ ¬ │ ! │ " │ £ │ $ │ % │ ^ │ & │ * │ ( │ ) │ _ │ + │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │   │   │   │   │   │   │   │   │   │   │ { │ } │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │   │   │   │   │   │   │   │   │   │ : │ @ │ ~ │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │ | │   │   │   │   │   │   │   │ < │ > │ ? │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  'S(KC_GRV)': { name: '¬', alias: 'IE_NOT', title: '¬' },
  KC_TILD: { name: '¬', alias: 'IE_NOT', title: '¬' },
  'S(KC_1)': { name: '!', alias: 'IE_EXLM', title: '!' },
  KC_EXLM: { name: '!', alias: 'IE_EXLM', title: '!' },
  'S(KC_2)': { name: '"', alias: 'IE_DQUO', title: '"' },
  KC_AT: { name: '"', alias: 'IE_DQUO', title: '"' },
  'S(KC_3)': { name: '£', alias: 'IE_PND', title: '£' },
  KC_HASH: { name: '£', alias: 'IE_PND', title: '£' },
  'S(KC_4)': { name: '$', alias: 'IE_DLR', title: '$' },
  KC_DLR: { name: '$', alias: 'IE_DLR', title: '$' },
  'S(KC_5)': { name: '%', alias: 'IE_PERC', title: '%' },
  KC_PERC: { name: '%', alias: 'IE_PERC', title: '%' },
  'S(KC_6)': { name: '^', alias: 'IE_CIRC', title: '^' },
  KC_CIRC: { name: '^', alias: 'IE_CIRC', title: '^' },
  'S(KC_7)': { name: '&', alias: 'IE_AMPR', title: '&' },
  KC_AMPR: { name: '&', alias: 'IE_AMPR', title: '7' },
  'S(KC_8)': { name: '*', alias: 'IE_ASTR', title: '*' },
  KC_ASTR: { name: '*', alias: 'IE_ASTR', title: '*' },
  'S(KC_9)': { name: '(', alias: 'IE_LPRN', title: '(' },
  KC_LPRN: { name: '(', alias: 'IE_LPRN', title: '(' },
  'S(KC_0)': { name: ')', alias: 'IE_RPRN', title: ')' },
  KC_RPRN: { name: ')', alias: 'IE_RPRN', title: ')' },
  'S(KC_MINS)': { name: '_', alias: 'IE_UNDS', title: '_' },
  KC_UNDS: { name: '_', alias: 'IE_UNDS', title: '_' },
  'S(KC_EQL)': { name: '+', alias: 'IE_PLUS', title: '+' },
  KC_PLUS: { name: '+', alias: 'IE_PLUS', title: '+' },
  // Row 2
  'S(KC_LBRC)': { name: '{', alias: 'IE_LCBR', title: '{' },
  KC_LCBR: { name: '{', alias: 'IE_LCBR', title: '{' },
  'S(KC_RBRC)': { name: '}', alias: 'IE_RCBR', title: '}' },
  KC_RCBR: { name: '}', alias: 'IE_RCBR', title: '}' },
  // Row 3
  'S(KC_SCLN)': { name: ':', alias: 'IE_COLN', title: ':' },
  KC_COLN: { name: ':', alias: 'IE_COLN', title: ':' },
  'S(KC_QUOT)': { name: '@', alias: 'IE_AT', title: '@' },
  KC_DQUO: { name: '@', alias: 'IE_AT', title: '@' },
  'S(KC_NUHS)': { name: '~', alias: 'IE_TILD', title: '~' },
  // Row 4
  'S(KC_NUBS)': { name: '|', alias: 'IE_PIPE', title: '|' },
  'S(KC_COMM)': { name: '<', alias: 'IE_LABK', title: '<' },
  KC_LT: { name: '<', alias: 'IE_LABK', title: '<' },
  'S(KC_DOT)': { name: '>', alias: 'IE_RABK', title: '>' },
  KC_GT: { name: '>', alias: 'IE_RABK', title: '>' },
  'S(KC_SLSH)': { name: '?', alias: 'IE_QUES', title: '?' },
  KC_QUES: { name: '?', alias: 'IE_QUES', title: '?' },

  /* AltGr symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ ¦ │   │   │   │ € │   │   │   │   │   │   │   │   │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │   │   │ É │   │   │   │ Ú │ Í │ Ó │   │   │   │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │ Á │   │   │   │   │   │   │   │   │   │ ´ │   │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │   │   │   │   │   │   │   │   │   │   │   │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  'ALGR(KC_GRV)': { name: '¦', alias: 'IE_BRKP', title: '¦' },
  'ALGR(KC_4)': { name: '€', alias: 'IE_EURO', title: '€' },
  // Row 2
  'ALGR(KC_E)': { name: 'É', alias: 'IE_EACU', title: 'É' },
  'ALGR(KC_U)': { name: 'Ú', alias: 'IE_UACU', title: 'Ú' },
  'ALGR(KC_I)': { name: 'Í', alias: 'IE_IACU', title: 'Í' },
  'ALGR(KC_O)': { name: 'Ó', alias: 'IE_OACU', title: 'Ó' },
  // Row 3
  'ALGR(KC_A)': { name: 'Á', alias: 'IE_AACU', title: 'Á' },
  'ALGR(KC_QUOT)': { name: '´', alias: 'IE_ACUT', title: '◌́ (dead)' },

  /* Other keys */
  KC_BSLS: { name: '~\n#', title: '# and ~' },
  'S(KC_BSLS)': { name: '~', title: '~' },
  KC_PIPE: { name: '~', alias: 'IE_TILD', title: '~' },

  SC_LSPO: { name: 'LS / (', title: 'Left Shift when held, ( when tapped' },
  SC_RSPC: { name: 'RS / )', title: 'Right Shift when held, ) when tapped' },
  SC_LCPO: { name: 'LC / (', title: 'Left Control when held, ( when tapped' },
  SC_RCPC: { name: 'RC / )', title: 'Right Control when held, ) when tapped' },
  SC_LAPO: { name: 'LA / (', title: 'Left Alt when held, ( when tapped' },
  SC_RAPC: { name: 'RA / )', title: 'Right Alt when held, ) when tapped' },

  QK_GESC: {
    name: '`/¬\nEsc',
    title: 'Esc normally, but ` when GUI is active or ¬ when Shift is active'
  }
};
