/* Copyright 2022 - Generated by convert_keymap_extras_header.js
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

export default {
  /*
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ ` │ ! │ - │ / │ ; │ : │ , │ . │ = │ ( │ ) │ ? │ X │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │ Ą │ Ž │ E │ R │ T │ Y │ U │ I │ O │ P │ Į │ W │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │ A │ S │ D │ Š │ G │ H │ J │ K │ L │ Ų │ Ė │ Q │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │ < │ Z │ Ū │ C │ V │ B │ N │ M │ Č │ F │ Ę │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  KC_GRV: { name: '~\n`', alias: 'LT_GRV', title: '` and ~' },
  KC_1: { name: '1\n!', alias: 'LT_EXLM', title: '! and 1' },
  KC_2: { name: '2\n-', alias: 'LT_MINS', title: '- and 2' },
  KC_3: { name: '3\n/', alias: 'LT_SLSH', title: '/ and 3' },
  KC_4: { name: '4\n;', alias: 'LT_SCLN', title: '; and 4' },
  KC_5: { name: '5\n:', alias: 'LT_COLN', title: ': and 5' },
  KC_6: { name: '6\n,', alias: 'LT_COMM', title: ', and 6' },
  KC_7: { name: '7\n.', alias: 'LT_DOT', title: '. and 7' },
  KC_8: { name: '8\n=', alias: 'LT_EQL', title: '= and 8' },
  KC_9: { name: '9\n(', alias: 'LT_LPRN', title: '( and 9' },
  KC_0: { name: '0\n)', alias: 'LT_RPRN', title: ') and 0' },
  KC_MINS: { name: '+\n?', alias: 'LT_QUES', title: '? and +' },
  KC_EQL: { name: 'X', alias: 'LT_X', title: 'x and X' },
  // Row 2
  KC_Q: { name: 'Ą', alias: 'LT_AOGO', title: 'ą and Ą' },
  KC_W: { name: 'Ž', alias: 'LT_ZCAR', title: 'ž and Ž' },
  KC_E: { name: 'E', alias: 'LT_E', title: 'e and E' },
  KC_R: { name: 'R', alias: 'LT_R', title: 'r and R' },
  KC_T: { name: 'T', alias: 'LT_T', title: 't and T' },
  KC_Y: { name: 'Y', alias: 'LT_Y', title: 'y and Y' },
  KC_U: { name: 'U', alias: 'LT_U', title: 'u and U' },
  KC_I: { name: 'I', alias: 'LT_I', title: 'i and I' },
  KC_O: { name: 'O', alias: 'LT_O', title: 'o and O' },
  KC_P: { name: 'P', alias: 'LT_P', title: 'p and P' },
  KC_LBRC: { name: 'Į', alias: 'LT_IOGO', title: 'į and Į' },
  KC_RBRC: { name: 'W', alias: 'LT_W', title: 'w and W' },
  // Row 3
  KC_A: { name: 'A', alias: 'LT_A', title: 'a and A' },
  KC_S: { name: 'S', alias: 'LT_S', title: 's and S' },
  KC_D: { name: 'D', alias: 'LT_D', title: 'd and D' },
  KC_F: { name: 'Š', alias: 'LT_SCAR', title: 'š and Š' },
  KC_G: { name: 'G', alias: 'LT_G', title: 'g and G' },
  KC_H: { name: 'H', alias: 'LT_H', title: 'h and H' },
  KC_J: { name: 'J', alias: 'LT_J', title: 'j and J' },
  KC_K: { name: 'K', alias: 'LT_K', title: 'k and K' },
  KC_L: { name: 'L', alias: 'LT_L', title: 'l and L' },
  KC_SCLN: { name: 'Ų', alias: 'LT_UOGO', title: 'ų and Ų' },
  KC_QUOT: { name: 'Ė', alias: 'LT_EDOT', title: 'ė and Ė' },
  KC_NUHS: { name: 'Q', alias: 'LT_Q', title: 'q and Q' },
  // Row 4
  KC_NUBS: { name: '>\n<', alias: 'LT_LABK', title: '< and >' },
  KC_Z: { name: 'Z', alias: 'LT_Z', title: 'z and Z' },
  KC_X: { name: 'Ū', alias: 'LT_UMAC', title: 'ū and Ū' },
  KC_C: { name: 'C', alias: 'LT_C', title: 'c and C' },
  KC_V: { name: 'V', alias: 'LT_V', title: 'v and V' },
  KC_B: { name: 'B', alias: 'LT_B', title: 'b and B' },
  KC_N: { name: 'N', alias: 'LT_N', title: 'n and N' },
  KC_M: { name: 'M', alias: 'LT_M', title: 'm and M' },
  KC_COMM: { name: 'Č', alias: 'LT_CCAR', title: 'č and Č' },
  KC_DOT: { name: 'F', alias: 'LT_F', title: 'f and F' },
  KC_SLSH: { name: 'Ę', alias: 'LT_EOGO', title: 'ę and Ę' },

  /* Shifted symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ ~ │ 1 │ 2 │ 3 │ 4 │ 5 │ 6 │ 7 │ 8 │ 9 │ 0 │ + │   │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │   │   │   │   │   │   │   │   │   │   │   │   │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │   │   │   │   │   │   │   │   │   │   │   │   │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │ > │   │   │   │   │   │   │   │   │   │   │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  'S(KC_GRV)': { name: '~', alias: 'LT_TILD', title: '~' },
  KC_TILD: { name: '~', alias: 'LT_TILD', title: '~' },
  'S(KC_1)': { name: '1', alias: 'LT_1', title: '1' },
  KC_EXLM: { name: '1', alias: 'LT_1', title: '1' },
  'S(KC_2)': { name: '2', alias: 'LT_2', title: '2' },
  KC_AT: { name: '2', alias: 'LT_2', title: '2' },
  'S(KC_3)': { name: '3', alias: 'LT_3', title: '3' },
  KC_HASH: { name: '3', alias: 'LT_3', title: '3' },
  'S(KC_4)': { name: '4', alias: 'LT_4', title: '4' },
  KC_DLR: { name: '4', alias: 'LT_4', title: '4' },
  'S(KC_5)': { name: '5', alias: 'LT_5', title: '5' },
  KC_PERC: { name: '5', alias: 'LT_5', title: '5' },
  'S(KC_6)': { name: '6', alias: 'LT_6', title: '6' },
  KC_CIRC: { name: '6', alias: 'LT_6', title: '6' },
  'S(KC_7)': { name: '7', alias: 'LT_7', title: '7' },
  KC_AMPR: { name: '7', alias: 'LT_7', title: '7' },
  'S(KC_8)': { name: '8', alias: 'LT_8', title: '8' },
  KC_ASTR: { name: '8', alias: 'LT_8', title: '8' },
  'S(KC_9)': { name: '9', alias: 'LT_9', title: '9' },
  KC_LPRN: { name: '9', alias: 'LT_9', title: '9' },
  'S(KC_0)': { name: '0', alias: 'LT_0', title: '0' },
  KC_RPRN: { name: '0', alias: 'LT_0', title: '0' },
  'S(KC_MINS)': { name: '+', alias: 'LT_PLUS', title: '+' },
  KC_UNDS: { name: '+', alias: 'LT_PLUS', title: '+' },
  // Row 4
  'S(KC_NUBS)': { name: '>', alias: 'LT_RABK', title: '>' },

  /* AltGr symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ ´ │ @ │ _ │ # │ $ │ § │ ^ │ & │ * │ [ │ ] │ ' │ % │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │   │   │ € │   │   │   │   │   │   │   │ { │ } │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │   │   │   │   │   │   │   │   │   │   │ " │ | │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │ – │   │   │   │   │   │   │   │ „ │ “ │ \ │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  'ALGR(KC_GRV)': { name: '´', alias: 'LT_ACUT', title: '´' },
  'ALGR(KC_1)': { name: '@', alias: 'LT_AT', title: '@' },
  'ALGR(KC_2)': { name: '_', alias: 'LT_UNDS', title: '_' },
  'ALGR(KC_3)': { name: '#', alias: 'LT_HASH', title: '#' },
  'ALGR(KC_4)': { name: '$', alias: 'LT_DLR', title: '$' },
  'ALGR(KC_5)': { name: '§', alias: 'LT_SECT', title: '§' },
  'ALGR(KC_6)': { name: '^', alias: 'LT_CIRC', title: '^' },
  'ALGR(KC_7)': { name: '&', alias: 'LT_AMPR', title: '&' },
  'ALGR(KC_8)': { name: '*', alias: 'LT_ASTR', title: '*' },
  'ALGR(KC_9)': { name: '[', alias: 'LT_LBRC', title: '[' },
  'ALGR(KC_0)': { name: ']', alias: 'LT_RBRC', title: ']' },
  'ALGR(KC_MINS)': { name: "'", alias: 'LT_QUOT', title: "'" },
  'ALGR(KC_EQL)': { name: '%', alias: 'LT_PERC', title: '%' },
  // Row 2
  'ALGR(KC_E)': { name: '€', alias: 'LT_EURO', title: '€' },
  'ALGR(KC_LBRC)': { name: '{', alias: 'LT_LCBR', title: '{' },
  'ALGR(KC_RBRC)': { name: '}', alias: 'LT_RCBR', title: '}' },
  // Row 3
  'ALGR(KC_QUOT)': { name: '"', alias: 'LT_DQUO', title: '"' },
  'ALGR(KC_NUHS)': { name: '|', alias: 'LT_PIPE', title: '|' },
  // Row 4
  'ALGR(KC_NUBS)': { name: '–', alias: 'LT_NDSH', title: '–' },
  'ALGR(KC_COMM)': { name: '„', alias: 'LT_DLQU', title: '„' },
  'ALGR(KC_DOT)': { name: '“', alias: 'LT_LDQU', title: '“' },
  'ALGR(KC_SLSH)': { name: '\\', alias: 'LT_BSLS', title: '\\' },

  /* Other keys */
  KC_BSLS: { name: 'Q', title: 'Q' },
  'S(KC_BSLS)': { name: 'Q', title: 'Q' },
  KC_PLUS: { name: 'X', alias: 'S(LT_X)', title: 'X' },
  KC_LCBR: { name: 'Į', alias: 'S(LT_IOGO)', title: 'Į' },
  KC_RCBR: { name: 'W', alias: 'S(LT_W)', title: 'W' },
  KC_LT: { name: 'Č', alias: 'S(LT_CCAR)', title: 'Č' },
  KC_GT: { name: 'F', alias: 'S(LT_F)', title: 'F' },
  KC_COLN: { name: 'Ų', alias: 'S(LT_UOGO)', title: 'Ų' },
  KC_PIPE: { name: 'Q', alias: 'LT_Q', title: 'Q' },
  KC_QUES: { name: 'Ę', alias: 'S(LT_EOGO)', title: 'Ę' },
  KC_DQUO: { name: 'Ė', alias: 'S(LT_EDOT)', title: 'Ė' },

  SC_LSPO: { name: 'LS / 9', title: 'Left Shift when held, 9 when tapped' },
  SC_RSPC: { name: 'RS / 0', title: 'Right Shift when held, 0 when tapped' },
  SC_LCPO: { name: 'LC / 9', title: 'Left Control when held, 9 when tapped' },
  SC_RCPC: { name: 'RC / 0', title: 'Right Control when held, 0 when tapped' },
  SC_LAPO: { name: 'LA / 9', title: 'Left Alt when held, 9 when tapped' },
  SC_RAPC: { name: 'RA / 0', title: 'Right Alt when held, 0 when tapped' },

  QK_GESC: {
    name: '`/~\nEsc',
    title: 'Esc normally, but ` when GUI is active or ~ when Shift is active'
  }
};
