/* Copyright 2022 - Generated by convert_keymap_extras_header.js
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

export default {
  /*
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ ; │ + │ ě │ š │ č │ ř │ ž │ ý │ á │ í │ é │ = │ ´ │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │ Q │ W │ E │ R │ T │ Z │ U │ I │ O │ P │ ú │ ) │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │ A │ S │ D │ F │ G │ H │ J │ K │ L │ ů │ § │ ¨ │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │ \ │ Y │ X │ C │ V │ B │ N │ M │ , │ . │ - │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  KC_GRV: { name: '°\n;', alias: 'CZ_SCLN', title: '; and °' },
  KC_1: { name: '1\n+', alias: 'CZ_PLUS', title: '+ and 1' },
  KC_2: { name: '2\ně', alias: 'CZ_ECAR', title: 'ě and 2' },
  KC_3: { name: '3\nš', alias: 'CZ_SCAR', title: 'š and 3' },
  KC_4: { name: '4\nč', alias: 'CZ_CCAR', title: 'č and 4' },
  KC_5: { name: '5\nř', alias: 'CZ_RCAR', title: 'ř and 5' },
  KC_6: { name: '6\nž', alias: 'CZ_ZCAR', title: 'ž and 6' },
  KC_7: { name: '7\ný', alias: 'CZ_YACU', title: 'ý and 7' },
  KC_8: { name: '8\ná', alias: 'CZ_AACU', title: 'á and 8' },
  KC_9: { name: '9\ní', alias: 'CZ_IACU', title: 'í and 9' },
  KC_0: { name: '0\né', alias: 'CZ_EACU', title: 'é and 0' },
  KC_MINS: { name: '%\n=', alias: 'CZ_EQL', title: '= and %' },
  KC_EQL: {
    name: 'ˇ\n´',
    alias: 'CZ_ACUT',
    title: '◌́ (dead) and ◌̌ (dead)'
  },
  // Row 2
  KC_Q: { name: 'Q', alias: 'CZ_Q', title: 'q and Q' },
  KC_W: { name: 'W', alias: 'CZ_W', title: 'w and W' },
  KC_E: { name: 'E', alias: 'CZ_E', title: 'e and E' },
  KC_R: { name: 'R', alias: 'CZ_R', title: 'r and R' },
  KC_T: { name: 'T', alias: 'CZ_T', title: 't and T' },
  KC_Y: { name: 'Z', alias: 'CZ_Z', title: 'z and Z' },
  KC_U: { name: 'U', alias: 'CZ_U', title: 'u and U' },
  KC_I: { name: 'I', alias: 'CZ_I', title: 'i and I' },
  KC_O: { name: 'O', alias: 'CZ_O', title: 'o and O' },
  KC_P: { name: 'P', alias: 'CZ_P', title: 'p and P' },
  KC_LBRC: { name: '/\nú', alias: 'CZ_UACU', title: 'ú and /' },
  KC_RBRC: { name: '(\n)', alias: 'CZ_RPRN', title: ') and (' },
  // Row 3
  KC_A: { name: 'A', alias: 'CZ_A', title: 'a and A' },
  KC_S: { name: 'S', alias: 'CZ_S', title: 's and S' },
  KC_D: { name: 'D', alias: 'CZ_D', title: 'd and D' },
  KC_F: { name: 'F', alias: 'CZ_F', title: 'f and F' },
  KC_G: { name: 'G', alias: 'CZ_G', title: 'g and G' },
  KC_H: { name: 'H', alias: 'CZ_H', title: 'h and H' },
  KC_J: { name: 'J', alias: 'CZ_J', title: 'j and J' },
  KC_K: { name: 'K', alias: 'CZ_K', title: 'k and K' },
  KC_L: { name: 'L', alias: 'CZ_L', title: 'l and L' },
  KC_SCLN: { name: '"\nů', alias: 'CZ_URNG', title: 'ů and "' },
  KC_QUOT: { name: '!\n§', alias: 'CZ_SECT', title: '§ and !' },
  KC_NUHS: { name: "'\n¨", alias: 'CZ_DIAE', title: "◌̈ (dead) and '" },
  // Row 4
  KC_NUBS: { name: '|\n\\', alias: 'CZ_BSLS', title: '\\ and |' },
  KC_Z: { name: 'Y', alias: 'CZ_Y', title: 'y and Y' },
  KC_X: { name: 'X', alias: 'CZ_X', title: 'x and X' },
  KC_C: { name: 'C', alias: 'CZ_C', title: 'c and C' },
  KC_V: { name: 'V', alias: 'CZ_V', title: 'v and V' },
  KC_B: { name: 'B', alias: 'CZ_B', title: 'b and B' },
  KC_N: { name: 'N', alias: 'CZ_N', title: 'n and N' },
  KC_M: { name: 'M', alias: 'CZ_M', title: 'm and M' },
  KC_COMM: { name: '?\n,', alias: 'CZ_COMM', title: ', and ?' },
  KC_DOT: { name: ':\n.', alias: 'CZ_DOT', title: '. and :' },
  KC_SLSH: { name: '_\n-', alias: 'CZ_MINS', title: '- and _' },

  /* Shifted symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ ° │ 1 │ 2 │ 3 │ 4 │ 5 │ 6 │ 7 │ 8 │ 9 │ 0 │ % │ ˇ │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │   │   │   │   │   │   │   │   │   │   │ / │ ( │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │   │   │   │   │   │   │   │   │   │ " │ ! │ ' │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │ | │   │   │   │   │   │   │   │ ? │ : │ _ │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  'S(KC_GRV)': { name: '°', alias: 'CZ_RNGA', title: '◌̊ (dead)' },
  KC_TILD: { name: '°', alias: 'CZ_RNGA', title: '◌̊ (dead)' },
  'S(KC_1)': { name: '1', alias: 'CZ_1', title: '1' },
  KC_EXLM: { name: '1', alias: 'CZ_1', title: '1' },
  'S(KC_2)': { name: '2', alias: 'CZ_2', title: '2' },
  KC_AT: { name: '2', alias: 'CZ_2', title: '2' },
  'S(KC_3)': { name: '3', alias: 'CZ_3', title: '3' },
  KC_HASH: { name: '3', alias: 'CZ_3', title: '3' },
  'S(KC_4)': { name: '4', alias: 'CZ_4', title: '4' },
  KC_DLR: { name: '4', alias: 'CZ_4', title: '4' },
  'S(KC_5)': { name: '5', alias: 'CZ_5', title: '5' },
  KC_PERC: { name: '5', alias: 'CZ_5', title: '5' },
  'S(KC_6)': { name: '6', alias: 'CZ_6', title: '6' },
  KC_CIRC: { name: '6', alias: 'CZ_6', title: '6' },
  'S(KC_7)': { name: '7', alias: 'CZ_7', title: '7' },
  KC_AMPR: { name: '7', alias: 'CZ_7', title: '7' },
  'S(KC_8)': { name: '8', alias: 'CZ_8', title: '8' },
  KC_ASTR: { name: '8', alias: 'CZ_8', title: '8' },
  'S(KC_9)': { name: '9', alias: 'CZ_9', title: '9' },
  KC_LPRN: { name: '9', alias: 'CZ_9', title: '9' },
  'S(KC_0)': { name: '0', alias: 'CZ_0', title: '0' },
  KC_RPRN: { name: '0', alias: 'CZ_0', title: '0' },
  'S(KC_MINS)': { name: '%', alias: 'CZ_PERC', title: '%' },
  KC_UNDS: { name: '%', alias: 'CZ_PERC', title: '%' },
  'S(KC_EQL)': { name: 'ˇ', alias: 'CZ_CARN', title: '◌̌ (dead)' },
  KC_PLUS: { name: 'ˇ', alias: 'CZ_CARN', title: '◌̌ (dead)' },
  // Row 2
  'S(KC_LBRC)': { name: '/', alias: 'CZ_SLSH', title: '/' },
  KC_LCBR: { name: '/', alias: 'CZ_SLSH', title: '/' },
  'S(KC_RBRC)': { name: '(', alias: 'CZ_LPRN', title: '(' },
  KC_RCBR: { name: '(', alias: 'CZ_LPRN', title: '(' },
  // Row 3
  'S(KC_SCLN)': { name: '"', alias: 'CZ_DQUO', title: '"' },
  KC_COLN: { name: '"', alias: 'CZ_DQUO', title: '"' },
  'S(KC_QUOT)': { name: '!', alias: 'CZ_EXLM', title: '!' },
  KC_DQUO: { name: '!', alias: 'CZ_EXLM', title: '!' },
  'S(KC_NUHS)': { name: "'", alias: 'CZ_QUOT', title: "'" },
  // Row 4
  'S(KC_NUBS)': { name: '|', alias: 'CZ_PIPE', title: '|' },
  'S(KC_COMM)': { name: '?', alias: 'CZ_QUES', title: '?' },
  KC_LT: { name: '?', alias: 'CZ_QUES', title: '?' },
  'S(KC_DOT)': { name: ':', alias: 'CZ_COLN', title: ':' },
  KC_GT: { name: ':', alias: 'CZ_COLN', title: ':' },
  'S(KC_SLSH)': { name: '_', alias: 'CZ_UNDS', title: '_' },
  KC_QUES: { name: '_', alias: 'CZ_UNDS', title: '_' },

  /* AltGr symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │   │ ~ │   │ ^ │ ˘ │   │ ˛ │ ` │ ˙ │   │ ˝ │   │ ¸ │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │   │   │ € │   │   │   │   │   │   │   │ ÷ │ × │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │   │ đ │ Đ │ [ │ ] │   │   │ ł │ Ł │ $ │ ß │ ¤ │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │   │   │ # │ & │ @ │ { │ } │   │ < │ > │ * │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  'ALGR(KC_1)': { name: '~', alias: 'CZ_TILD', title: '~' },
  'ALGR(KC_3)': { name: '^', alias: 'CZ_CIRC', title: '◌̂ (dead)' },
  'ALGR(KC_4)': { name: '˘', alias: 'CZ_BREV', title: '◌̆ (dead)' },
  'ALGR(KC_6)': { name: '˛', alias: 'CZ_OGON', title: '◌̨ (dead)' },
  'ALGR(KC_7)': { name: '`', alias: 'CZ_GRV', title: '◌̀ (dead)' },
  'ALGR(KC_8)': { name: '˙', alias: 'CZ_DOTA', title: '◌̇ (dead)' },
  'ALGR(KC_0)': { name: '˝', alias: 'CZ_DACU', title: '◌̋ (dead)' },
  'ALGR(KC_EQL)': { name: '¸', alias: 'CZ_CEDL', title: '◌̧ (dead)' },
  // Row 2
  'ALGR(KC_E)': { name: '€', alias: 'CZ_EURO', title: '€' },
  'ALGR(KC_LBRC)': { name: '÷', alias: 'CZ_DIV', title: '÷' },
  'ALGR(KC_RBRC)': { name: '×', alias: 'CZ_MUL', title: '×' },
  // Row 3
  'ALGR(KC_S)': { name: 'đ', alias: 'CZ_LDST', title: 'đ' },
  'ALGR(KC_D)': { name: 'Đ', alias: 'CZ_CDST', title: 'Đ' },
  'ALGR(KC_F)': { name: '[', alias: 'CZ_LBRC', title: '[' },
  'ALGR(KC_G)': { name: ']', alias: 'CZ_RBRC', title: ']' },
  'ALGR(KC_K)': { name: 'ł', alias: 'CZ_LLST', title: 'ł' },
  'ALGR(KC_L)': { name: 'Ł', alias: 'CZ_CLST', title: 'Ł' },
  'ALGR(KC_SCLN)': { name: '$', alias: 'CZ_DLR', title: '$' },
  'ALGR(KC_QUOT)': { name: 'ß', alias: 'CZ_SS', title: 'ß' },
  'ALGR(KC_NUHS)': { name: '¤', alias: 'CZ_CURR', title: '¤' },
  // Row 4
  'ALGR(KC_X)': { name: '#', alias: 'CZ_HASH', title: '#' },
  'ALGR(KC_C)': { name: '&', alias: 'CZ_AMPR', title: '&' },
  'ALGR(KC_V)': { name: '@', alias: 'CZ_AT', title: '@' },
  'ALGR(KC_B)': { name: '{', alias: 'CZ_LCBR', title: '{' },
  'ALGR(KC_N)': { name: '}', alias: 'CZ_RCBR', title: '}' },
  'ALGR(KC_COMM)': { name: '<', alias: 'CZ_LABK', title: '<' },
  'ALGR(KC_DOT)': { name: '>', alias: 'CZ_RABK', title: '>' },
  'ALGR(KC_SLSH)': { name: '*', alias: 'CZ_ASTR', title: '*' },

  /* Other keys */
  KC_BSLS: { name: "'\n¨", title: "◌̈ (dead) and ' (dead)" },
  'S(KC_BSLS)': { name: "'", title: "'" },
  KC_PIPE: { name: "'", alias: 'CZ_QUOT', title: "'" },

  SC_LSPO: { name: 'LS / 9', title: 'Left Shift when held, 9 when tapped' },
  SC_RSPC: { name: 'RS / 0', title: 'Right Shift when held, 0 when tapped' },
  SC_LCPO: { name: 'LC / 9', title: 'Left Control when held, 9 when tapped' },
  SC_RCPC: { name: 'RC / 0', title: 'Right Control when held, 0 when tapped' },
  SC_LAPO: { name: 'LA / 9', title: 'Left Alt when held, 9 when tapped' },
  SC_RAPC: { name: 'RA / 0', title: 'Right Alt when held, 0 when tapped' },

  QK_GESC: {
    name: ';/°\nEsc',
    title: 'Esc normally, but ; when GUI is active or ° when Shift is active'
  }
};
