/* Copyright 2022 - Generated by convert_keymap_extras_header.js
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

export default {
  /*
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ § │ 1 │ 2 │ 3 │ 4 │ 5 │ 6 │ 7 │ 8 │ 9 │ 0 │ ' │ ^ │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │ Q │ W │ E │ R │ T │ Z │ U │ I │ O │ P │ è │ ¨ │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │ A │ S │ D │ F │ G │ H │ J │ K │ L │ é │ à │ $ │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │ < │ Y │ X │ C │ V │ B │ N │ M │ , │ . │ - │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  KC_GRV: { name: '°\n§', alias: 'CH_SECT', title: '§ and °' },
  KC_1: { name: '+\n1', alias: 'CH_1', title: '1 and +' },
  KC_2: { name: '"\n2', alias: 'CH_2', title: '2 and "' },
  KC_3: { name: '*\n3', alias: 'CH_3', title: '3 and *' },
  KC_4: { name: 'ç\n4', alias: 'CH_4', title: '4 and ç' },
  KC_5: { name: '%\n5', alias: 'CH_5', title: '5 and %' },
  KC_6: { name: '&\n6', alias: 'CH_6', title: '6 and &' },
  KC_7: { name: '/\n7', alias: 'CH_7', title: '7 and /' },
  KC_8: { name: '(\n8', alias: 'CH_8', title: '8 and (' },
  KC_9: { name: ')\n9', alias: 'CH_9', title: '9 and )' },
  KC_0: { name: '=\n0', alias: 'CH_0', title: '0 and =' },
  KC_MINS: { name: "?\n'", alias: 'CH_QUOT', title: "' and ?" },
  KC_EQL: { name: '`\n^', alias: 'CH_CIRC', title: '◌̂ (dead) and ◌̀ (dead)' },
  // Row 2
  KC_Q: { name: 'Q', alias: 'CH_Q', title: 'q and Q' },
  KC_W: { name: 'W', alias: 'CH_W', title: 'w and W' },
  KC_E: { name: 'E', alias: 'CH_E', title: 'e and E' },
  KC_R: { name: 'R', alias: 'CH_R', title: 'r and R' },
  KC_T: { name: 'T', alias: 'CH_T', title: 't and T' },
  KC_Y: { name: 'Z', alias: 'CH_Z', title: 'z and Z' },
  KC_U: { name: 'U', alias: 'CH_U', title: 'u and U' },
  KC_I: { name: 'I', alias: 'CH_I', title: 'i and I' },
  KC_O: { name: 'O', alias: 'CH_O', title: 'o and O' },
  KC_P: { name: 'P', alias: 'CH_P', title: 'p and P' },
  KC_LBRC: { name: 'ü\nè', alias: 'CH_EGRV', title: 'è and ü' },
  KC_RBRC: { name: '!\n¨', alias: 'CH_DIAE', title: '◌̈ (dead) and !' },
  // Row 3
  KC_A: { name: 'A', alias: 'CH_A', title: 'a and A' },
  KC_S: { name: 'S', alias: 'CH_S', title: 's and S' },
  KC_D: { name: 'D', alias: 'CH_D', title: 'd and D' },
  KC_F: { name: 'F', alias: 'CH_F', title: 'f and F' },
  KC_G: { name: 'G', alias: 'CH_G', title: 'g and G' },
  KC_H: { name: 'H', alias: 'CH_H', title: 'h and H' },
  KC_J: { name: 'J', alias: 'CH_J', title: 'j and J' },
  KC_K: { name: 'K', alias: 'CH_K', title: 'k and K' },
  KC_L: { name: 'L', alias: 'CH_L', title: 'l and L' },
  KC_SCLN: { name: 'ö\né', alias: 'CH_EACU', title: 'é and ö' },
  KC_QUOT: { name: 'ä\nà', alias: 'CH_AGRV', title: 'à and ä' },
  KC_NUHS: { name: '£\n$', alias: 'CH_DLR', title: '$ and £' },
  // Row 4
  KC_NUBS: { name: '>\n<', alias: 'CH_LABK', title: '< and >' },
  KC_Z: { name: 'Y', alias: 'CH_Y', title: 'y and Y' },
  KC_X: { name: 'X', alias: 'CH_X', title: 'x and X' },
  KC_C: { name: 'C', alias: 'CH_C', title: 'c and C' },
  KC_V: { name: 'V', alias: 'CH_V', title: 'v and V' },
  KC_B: { name: 'B', alias: 'CH_B', title: 'b and B' },
  KC_N: { name: 'N', alias: 'CH_N', title: 'n and N' },
  KC_M: { name: 'M', alias: 'CH_M', title: 'm and M' },
  KC_COMM: { name: ';\n,', alias: 'CH_COMM', title: ', and ;' },
  KC_DOT: { name: ':\n.', alias: 'CH_DOT', title: '. and :' },
  KC_SLSH: { name: '_\n-', alias: 'CH_MINS', title: '- and _' },

  /* Shifted symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ ° │ + │ " │ * │ ç │ % │ & │ / │ ( │ ) │ = │ ? │ ` │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │   │   │   │   │   │   │   │   │   │   │ ü │ ! │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │   │   │   │   │   │   │   │   │   │ ö │ ä │ £ │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │ > │   │   │   │   │   │   │   │ ; │ : │ _ │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  'S(KC_GRV)': { name: '°', alias: 'CH_DEG', title: '°' },
  KC_TILD: { name: '°', alias: 'CH_DEG', title: '°' },
  'S(KC_1)': { name: '+', alias: 'CH_PLUS', title: '+' },
  KC_EXLM: { name: '+', alias: 'CH_PLUS', title: '+' },
  'S(KC_2)': { name: '"', alias: 'CH_DQUO', title: '"' },
  KC_AT: { name: '"', alias: 'CH_DQUO', title: '"' },
  'S(KC_3)': { name: '*', alias: 'CH_ASTR', title: '*' },
  KC_HASH: { name: '*', alias: 'CH_ASTR', title: '*' },
  'S(KC_4)': { name: 'ç', alias: 'CH_CCED', title: 'ç' },
  KC_DLR: { name: 'ç', alias: 'CH_CCED', title: 'ç' },
  'S(KC_5)': { name: '%', alias: 'CH_PERC', title: '%' },
  KC_PERC: { name: '%', alias: 'CH_PERC', title: '%' },
  'S(KC_6)': { name: '&', alias: 'CH_AMPR', title: '&' },
  KC_CIRC: { name: '&', alias: 'CH_AMPR', title: '&' },
  'S(KC_7)': { name: '/', alias: 'CH_SLSH', title: '/' },
  KC_AMPR: { name: '/', alias: 'CH_SLSH', title: '/' },
  'S(KC_8)': { name: '(', alias: 'CH_LPRN', title: '(' },
  KC_ASTR: { name: '(', alias: 'CH_LPRN', title: '(' },
  'S(KC_9)': { name: ')', alias: 'CH_RPRN', title: ')' },
  KC_LPRN: { name: ')', alias: 'CH_RPRN', title: ')' },
  'S(KC_0)': { name: '=', alias: 'CH_EQL', title: '=' },
  KC_RPRN: { name: '=', alias: 'CH_EQL', title: '=' },
  'S(KC_MINS)': { name: '?', alias: 'CH_QUES', title: '?' },
  KC_UNDS: { name: '?', alias: 'CH_QUES', title: '?' },
  'S(KC_EQL)': { name: '`', alias: 'CH_GRV', title: '◌̀ (dead)' },
  KC_PLUS: { name: '`', alias: 'CH_GRV', title: '◌̀ (dead)' },
  // Row 2
  'S(KC_LBRC)': { name: 'ü', alias: 'CH_UDIA', title: 'ü' },
  KC_LCBR: { name: 'ü', alias: 'CH_UDIA', title: 'ü' },
  'S(KC_RBRC)': { name: '!', alias: 'CH_EXLM', title: '!' },
  KC_RCBR: { name: '!', alias: 'CH_EXLM', title: '!' },
  // Row 3
  'S(KC_SCLN)': { name: 'ö', alias: 'CH_ODIA', title: 'ö' },
  KC_COLN: { name: 'ö', alias: 'CH_ODIA', title: 'ö' },
  'S(KC_QUOT)': { name: 'ä', alias: 'CH_ADIA', title: 'ä' },
  KC_DQUO: { name: 'ä', alias: 'CH_ADIA', title: 'ä' },
  'S(KC_NUHS)': { name: '£', alias: 'CH_PND', title: '£' },
  // Row 4
  'S(KC_NUBS)': { name: '>', alias: 'CH_RABK', title: '>' },
  'S(KC_COMM)': { name: ';', alias: 'CH_SCLN', title: ';' },
  KC_LT: { name: ';', alias: 'CH_SCLN', title: ';' },
  'S(KC_DOT)': { name: ':', alias: 'CH_COLN', title: ':' },
  KC_GT: { name: ':', alias: 'CH_COLN', title: ':' },
  'S(KC_SLSH)': { name: '_', alias: 'CH_UNDS', title: '_' },
  KC_QUES: { name: '_', alias: 'CH_UNDS', title: '_' },

  /* AltGr symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │   │ ¦ │ @ │ # │   │   │ ¬ │ | │ ¢ │   │   │ ´ │ ~ │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │   │   │ € │   │   │   │   │   │   │   │ [ │ ] │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │   │   │   │   │   │   │   │   │   │   │ { │ } │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │ \ │   │   │   │   │   │   │   │   │   │   │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  'ALGR(KC_1)': { name: '¦', alias: 'CH_BRKP', title: '¦' },
  'ALGR(KC_2)': { name: '@', alias: 'CH_AT', title: '@' },
  'ALGR(KC_3)': { name: '#', alias: 'CH_HASH', title: '#' },
  'ALGR(KC_6)': { name: '¬', alias: 'CH_NOT', title: '¬' },
  'ALGR(KC_7)': { name: '|', alias: 'CH_PIPE', title: '|' },
  'ALGR(KC_8)': { name: '¢', alias: 'CH_CENT', title: '¢' },
  'ALGR(KC_MINS)': { name: '´', alias: 'CH_ACUT', title: '◌́ (dead)' },
  'ALGR(KC_EQL)': { name: '~', alias: 'CH_TILD', title: '◌̃ (dead)' },
  // Row 2
  'ALGR(KC_E)': { name: '€', alias: 'CH_EURO', title: '€' },
  'ALGR(KC_LBRC)': { name: '[', alias: 'CH_LBRC', title: '[' },
  'ALGR(KC_RBRC)': { name: ']', alias: 'CH_RBRC', title: ']' },
  // Row 3
  'ALGR(KC_QUOT)': { name: '{', alias: 'CH_LCBR', title: '{' },
  'ALGR(KC_NUHS)': { name: '}', alias: 'CH_RCBR', title: '}' },
  // Row 4
  'ALGR(KC_NUBS)': { name: '\\', alias: 'CH_BSLS', title: '\\' },

  /* Other keys */
  KC_BSLS: { name: '£\n$', title: '$ and £' },
  'S(KC_BSLS)': { name: '£', title: '£' },
  KC_PIPE: { name: '£', alias: 'CH_PND', title: '£' },

  SC_LSPO: { name: 'LS / )', title: 'Left Shift when held, ) when tapped' },
  SC_RSPC: { name: 'RS / =', title: 'Right Shift when held, = when tapped' },
  SC_LCPO: { name: 'LC / )', title: 'Left Control when held, ) when tapped' },
  SC_RCPC: { name: 'RC / =', title: 'Right Control when held, = when tapped' },
  SC_LAPO: { name: 'LA / )', title: 'Left Alt when held, ) when tapped' },
  SC_RAPC: { name: 'RA / =', title: 'Right Alt when held, = when tapped' },

  QK_GESC: {
    name: '§/°\nEsc',
    title: 'Esc normally, but § when GUI is active or ° when Shift is active'
  }
};
