/* Copyright 2022 - Generated by convert_keymap_extras_header.js
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

export default {
  /*
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ ; │ 1 │ 2 │ 3 │ 4 │ 5 │ 6 │ 7 │ 8 │ 9 │ 0 │ - │ = │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │ / │ ' │ פ │ ם │ ן │ ו │ ט │ א │ ר │ ק │ ] │ [ │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │ ף │ ך │ ל │ ח │ י │ ע │ כ │ ג │ ד │ ש │ , │ \ │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │   │ ץ │ ת │ צ │ מ │ נ │ ה │ ב │ ס │ ז │ . │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  KC_GRV: { name: '~\n;', alias: 'IL_SCLN', title: '; and ~' },
  KC_1: { name: '!\n1', alias: 'IL_1', title: '1 and !' },
  KC_2: { name: '@\n2', alias: 'IL_2', title: '2 and @' },
  KC_3: { name: '#\n3', alias: 'IL_3', title: '3 and #' },
  KC_4: { name: '$\n4', alias: 'IL_4', title: '4 and $' },
  KC_5: { name: '%\n5', alias: 'IL_5', title: '5 and %' },
  KC_6: { name: '^\n6', alias: 'IL_6', title: '6 and ^' },
  KC_7: { name: '&\n7', alias: 'IL_7', title: '7 and &' },
  KC_8: { name: '*\n8', alias: 'IL_8', title: '8 and *' },
  KC_9: { name: ')\n9', alias: 'IL_9', title: '9 and )' },
  KC_0: { name: '(\n0', alias: 'IL_0', title: '0 and (' },
  KC_MINS: { name: '_\n-', alias: 'IL_MINS', title: '- and _' },
  KC_EQL: { name: '+\n=', alias: 'IL_EQL', title: '= and +' },
  // Row 2
  KC_Q: { name: '/', alias: 'IL_SLSH', title: '/' },
  KC_W: { name: "'", alias: 'IL_QUOT', title: "'" },
  KC_E: { name: 'ק', alias: 'IL_QOF', title: 'ק' },
  KC_R: { name: 'ר', alias: 'IL_RESH', title: 'ר' },
  KC_T: { name: 'א', alias: 'IL_ALEF', title: 'א' },
  KC_Y: { name: 'ט', alias: 'IL_TET', title: 'ט' },
  KC_U: { name: 'ו', alias: 'IL_VAV', title: 'ו' },
  KC_I: { name: 'ן', alias: 'IL_FNUN', title: 'ן' },
  KC_O: { name: 'ם', alias: 'IL_FMEM', title: 'ם' },
  KC_P: { name: 'פ', alias: 'IL_PE', title: 'פ' },
  KC_LBRC: { name: '}\n]', alias: 'IL_RBRC', title: '] and }' },
  KC_RBRC: { name: '{\n[', alias: 'IL_LBRC', title: '[ and {' },
  // Row 3
  KC_A: { name: 'ש', alias: 'IL_SHIN', title: 'ש' },
  KC_S: { name: 'ד', alias: 'IL_DALT', title: 'ד' },
  KC_D: { name: 'ג', alias: 'IL_GIML', title: 'ג' },
  KC_F: { name: 'כ', alias: 'IL_KAF', title: 'כ' },
  KC_G: { name: 'ע', alias: 'IL_AYIN', title: 'ע' },
  KC_H: { name: 'י', alias: 'IL_YOD', title: 'י' },
  KC_J: { name: 'ח', alias: 'IL_HET', title: 'ח' },
  KC_K: { name: 'ל', alias: 'IL_LAMD', title: 'ל' },
  KC_L: { name: 'ך', alias: 'IL_FKAF', title: 'ך' },
  KC_SCLN: { name: ':\nף', alias: 'IL_FPE', title: 'ף and :' },
  KC_QUOT: { name: '"\n,', alias: 'IL_COMM', title: ', and "' },
  KC_NUHS: { name: '|\n\\', alias: 'IL_BSLS', title: '\\ and |' },
  // Row 4
  KC_Z: { name: 'ז', alias: 'IL_ZAYN', title: 'ז' },
  KC_X: { name: 'ס', alias: 'IL_SMKH', title: 'ס' },
  KC_C: { name: 'ב', alias: 'IL_BET', title: 'ב' },
  KC_V: { name: 'ה', alias: 'IL_HE', title: 'ה' },
  KC_B: { name: 'נ', alias: 'IL_NUN', title: 'נ' },
  KC_N: { name: 'מ', alias: 'IL_MEM', title: 'מ' },
  KC_M: { name: 'צ', alias: 'IL_TSDI', title: 'צ' },
  KC_COMM: { name: '>\nת', alias: 'IL_TAV', title: 'ת and >' },
  KC_DOT: { name: '<\nץ', alias: 'IL_FTSD', title: 'ץ and <' },
  KC_SLSH: { name: '?\n.', alias: 'IL_DOT', title: '. and ?' },

  /* Shifted symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ ~ │ ! │ @ │ # │ $ │ % │ ^ │ & │ * │ ) │ ( │ _ │ + │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │   │   │   │   │   │   │   │   │   │   │ } │ { │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │   │   │   │   │   │   │   │   │   │ : │ " │ | │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │   │   │   │   │   │   │   │   │ > │ < │ ? │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  'S(KC_GRV)': { name: '~', alias: 'IL_TILD', title: '~' },
  KC_TILD: { name: '~', alias: 'IL_TILD', title: '~' },
  'S(KC_1)': { name: '!', alias: 'IL_EXLM', title: '!' },
  KC_EXLM: { name: '!', alias: 'IL_EXLM', title: '!' },
  'S(KC_2)': { name: '@', alias: 'IL_AT', title: '@' },
  KC_AT: { name: '@', alias: 'IL_AT', title: '@' },
  'S(KC_3)': { name: '#', alias: 'IL_PND', title: '£' },
  KC_HASH: { name: '#', alias: 'IL_PND', title: '£' },
  'S(KC_4)': { name: '$', alias: 'IL_DLR', title: '$' },
  KC_DLR: { name: '$', alias: 'IL_DLR', title: '$' },
  'S(KC_5)': { name: '%', alias: 'IL_PERC', title: '%' },
  KC_PERC: { name: '%', alias: 'IL_PERC', title: '%' },
  'S(KC_6)': { name: '^', alias: 'IL_CIRC', title: '^' },
  KC_CIRC: { name: '^', alias: 'IL_CIRC', title: '^' },
  'S(KC_7)': { name: '&', alias: 'IL_AMPR', title: '&' },
  KC_AMPR: { name: '&', alias: 'IL_AMPR', title: '&' },
  'S(KC_8)': { name: '*', alias: 'IL_ASTR', title: '*' },
  KC_ASTR: { name: '*', alias: 'IL_ASTR', title: '*' },
  'S(KC_9)': { name: ')', alias: 'IL_RPRN', title: ')' },
  KC_LPRN: { name: ')', alias: 'IL_RPRN', title: ')' },
  'S(KC_0)': { name: '(', alias: 'IL_LPRN', title: '(' },
  KC_RPRN: { name: '(', alias: 'IL_LPRN', title: '(' },
  'S(KC_MINS)': { name: '_', alias: 'IL_UNDS', title: '_' },
  KC_UNDS: { name: '_', alias: 'IL_UNDS', title: '_' },
  'S(KC_EQL)': { name: '+', alias: 'IL_PLUS', title: '+' },
  KC_PLUS: { name: '+', alias: 'IL_PLUS', title: '+' },
  // Row 2
  'S(KC_LBRC)': { name: '}', alias: 'IL_RCBR', title: '}' },
  KC_LCBR: { name: '}', alias: 'IL_RCBR', title: '}' },
  'S(KC_RBRC)': { name: '{', alias: 'IL_LCBR', title: '{' },
  KC_RCBR: { name: '{', alias: 'IL_LCBR', title: '{' },
  // Row 3
  'S(KC_SCLN)': { name: ':', alias: 'IL_COLN', title: ':' },
  KC_COLN: { name: ':', alias: 'IL_COLN', title: ':' },
  'S(KC_QUOT)': { name: '"', alias: 'IL_DQUO', title: '"' },
  KC_DQUO: { name: '"', alias: 'IL_DQUO', title: '"' },
  'S(KC_NUHS)': { name: '|', alias: 'IL_PIPE', title: '|' },
  // Row 4
  'S(KC_COMM)': { name: '>', alias: 'IL_RABK', title: '>' },
  KC_LT: { name: '>', alias: 'IL_RABK', title: '>' },
  'S(KC_DOT)': { name: '<', alias: 'IL_LABK', title: '<' },
  KC_GT: { name: '<', alias: 'IL_LABK', title: '<' },
  'S(KC_SLSH)': { name: '?', alias: 'IL_QUES', title: '?' },
  KC_QUES: { name: '?', alias: 'IL_QUES', title: '?' },

  /* AltGr symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │   │   │   │ € │ ₪ │ ° │   │   │ × │   │   │   │   │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │   │   │   │   │   │ װ │   │   │   │   │   │   │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │   │   │   │   │ ײ │ ױ │   │   │   │   │   │   │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │   │   │   │   │   │   │   │   │   │   │ ÷ │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  'ALGR(KC_3)': { name: '€', alias: 'IL_EURO', title: '€' },
  'ALGR(KC_4)': { name: '₪', alias: 'IL_SHKL', title: '₪' },
  'ALGR(KC_5)': { name: '°', alias: 'IL_DEG', title: '°' },
  'ALGR(KC_8)': { name: '×', alias: 'IL_MUL', title: '×' },
  // Row 2
  'ALGR(KC_Y)': { name: 'װ', alias: 'IL_DVAV', title: 'װ' },
  // Row 3
  'ALGR(KC_G)': { name: 'ױ', alias: 'IL_VYOD', title: 'ױ' },
  'ALGR(KC_H)': { name: 'ײ', alias: 'IL_DYOD', title: 'ײ' },
  // Row 4
  'ALGR(KC_SLSH)': { name: '÷', alias: 'IL_DIV', title: '÷' },

  /* Other keys */
  KC_BSLS: { name: '|\n\\', title: '\\ and |' },
  'S(KC_BSLS)': { name: '|', title: '|' },
  KC_NUBS: { name: '|\n\\', title: '\\ and |' },
  'S(KC_NUBS)': { name: '|', title: '|' },
  KC_PIPE: { name: '|', alias: 'IL_PIPE', title: '|' },

  SC_LSPO: { name: 'LS / )', title: 'Left Shift when held, ) when tapped' },
  SC_RSPC: { name: 'RS / (', title: 'Right Shift when held, ( when tapped' },
  SC_LCPO: { name: 'LC / )', title: 'Left Control when held, ) when tapped' },
  SC_RCPC: { name: 'RC / (', title: 'Right Control when held, ( when tapped' },
  SC_LAPO: { name: 'LA / )', title: 'Left Alt when held, ) when tapped' },
  SC_RAPC: { name: 'RA / (', title: 'Right Alt when held, ( when tapped' },

  QK_GESC: {
    name: ';/~\nEsc',
    title: 'Esc normally, but ; when GUI is active or ~ when Shift is active'
  }
};
