/* Copyright 2022 - Generated by convert_keymap_extras_header.js
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

export default {
  /*
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ $ │ & │ [ │ { │ } │ ( │ = │ * │ ) │ + │ ] │ ! │ # │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │ ; │ , │ . │ P │ Y │ F │ G │ C │ R │ L │ / │ @ │  \  │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴─────┤
   * │      │ A │ O │ E │ U │ I │ D │ H │ T │ N │ S │ - │        │
   * ├──────┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴────────┤
   * │        │ ' │ Q │ J │ K │ X │ B │ M │ W │ V │ Z │          │
   * ├────┬───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  KC_GRV: { name: '~\n$', alias: 'DP_DLR', title: '$ and ~' },
  KC_1: { name: '%\n&', alias: 'DP_AMPR', title: '& and %' },
  KC_2: { name: '7\n[', alias: 'DP_LBRC', title: '[ and 7' },
  KC_3: { name: '5\n{', alias: 'DP_LCBR', title: '{ and 5' },
  KC_4: { name: '3\n}', alias: 'DP_RCBR', title: '} and 3' },
  KC_5: { name: '1\n(', alias: 'DP_LPRN', title: '( and 1' },
  KC_6: { name: '9\n=', alias: 'DP_EQL', title: '= and 9' },
  KC_7: { name: '0\n*', alias: 'DP_ASTR', title: '* and 0' },
  KC_8: { name: '2\n)', alias: 'DP_RPRN', title: ') and 2' },
  KC_9: { name: '4\n+', alias: 'DP_PLUS', title: '+ and 4' },
  KC_0: { name: '6\n]', alias: 'DP_RBRC', title: '] and 6' },
  KC_MINS: { name: '8\n!', alias: 'DP_EXLM', title: '! and 8' },
  KC_EQL: { name: '`\n#', alias: 'DP_HASH', title: '# and `' },
  // Row 2
  KC_Q: { name: ':\n;', alias: 'DP_SCLN', title: '; and :' },
  KC_W: { name: '<\n,', alias: 'DP_COMM', title: ', and <' },
  KC_E: { name: '>\n.', alias: 'DP_DOT', title: '. and >' },
  KC_R: { name: 'P', alias: 'DP_P', title: 'p and P' },
  KC_T: { name: 'Y', alias: 'DP_Y', title: 'y and Y' },
  KC_Y: { name: 'F', alias: 'DP_F', title: 'f and F' },
  KC_U: { name: 'G', alias: 'DP_G', title: 'g and G' },
  KC_I: { name: 'C', alias: 'DP_C', title: 'c and C' },
  KC_O: { name: 'R', alias: 'DP_R', title: 'r and R' },
  KC_P: { name: 'L', alias: 'DP_L', title: 'l and L' },
  KC_LBRC: { name: '?\n/', alias: 'DP_SLSH', title: '/ and ?' },
  KC_RBRC: { name: '^\n@', alias: 'DP_AT', title: '@ and ^' },
  KC_BSLS: { name: '|\n\\', alias: 'DP_BSLS', title: '\\ and |' },
  // Row 3
  KC_A: { name: 'A', alias: 'DP_A', title: 'a and A' },
  KC_S: { name: 'O', alias: 'DP_O', title: 'o and O' },
  KC_D: { name: 'E', alias: 'DP_E', title: 'e and E' },
  KC_F: { name: 'U', alias: 'DP_U', title: 'u and U' },
  KC_G: { name: 'I', alias: 'DP_I', title: 'i and I' },
  KC_H: { name: 'D', alias: 'DP_D', title: 'd and D' },
  KC_J: { name: 'H', alias: 'DP_H', title: 'h and H' },
  KC_K: { name: 'T', alias: 'DP_T', title: 't and T' },
  KC_L: { name: 'N', alias: 'DP_N', title: 'n and N' },
  KC_SCLN: { name: 'S', alias: 'DP_S', title: 's and S' },
  KC_QUOT: { name: '_\n-', alias: 'DP_MINS', title: '- and _' },
  // Row 4
  KC_Z: { name: '"\n\'', alias: 'DP_QUOT', title: '\' and "' },
  KC_X: { name: 'Q', alias: 'DP_Q', title: 'q and Q' },
  KC_C: { name: 'J', alias: 'DP_J', title: 'j and J' },
  KC_V: { name: 'K', alias: 'DP_K', title: 'k and K' },
  KC_B: { name: 'X', alias: 'DP_X', title: 'x and X' },
  KC_N: { name: 'B', alias: 'DP_B', title: 'b and B' },
  KC_M: { name: 'M', alias: 'DP_M', title: 'm and M' },
  KC_COMM: { name: 'W', alias: 'DP_W', title: 'w and W' },
  KC_DOT: { name: 'V', alias: 'DP_V', title: 'v and V' },
  KC_SLSH: { name: 'Z', alias: 'DP_Z', title: 'z and Z' },

  /* Shifted symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ ~ │ % │ 7 │ 5 │ 3 │ 1 │ 9 │ 0 │ 2 │ 4 │ 6 │ 8 │ ` │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │ : │ < │ > │   │   │   │   │   │   │   │ ? │ ^ │  |  │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴─────┤
   * │      │   │   │   │   │   │   │   │   │   │   │ _ │        │
   * ├──────┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴────────┤
   * │        │ " │   │   │   │   │   │   │   │   │   │          │
   * ├────┬───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  'S(KC_GRV)': { name: '~', alias: 'DP_TILD', title: '~' },
  KC_TILD: { name: '~', alias: 'DP_TILD', title: '~' },
  'S(KC_1)': { name: '%', alias: 'DP_PERC', title: '%' },
  KC_EXLM: { name: '%', alias: 'DP_PERC', title: '%' },
  'S(KC_2)': { name: '7', alias: 'DP_7', title: '7' },
  KC_AT: { name: '7', alias: 'DP_7', title: '7' },
  'S(KC_3)': { name: '5', alias: 'DP_5', title: '5' },
  KC_HASH: { name: '5', alias: 'DP_5', title: '5' },
  'S(KC_4)': { name: '3', alias: 'DP_3', title: '3' },
  KC_DLR: { name: '3', alias: 'DP_3', title: '3' },
  'S(KC_5)': { name: '1', alias: 'DP_1', title: '1' },
  KC_PERC: { name: '1', alias: 'DP_1', title: '1' },
  'S(KC_6)': { name: '9', alias: 'DP_9', title: '9' },
  KC_CIRC: { name: '9', alias: 'DP_9', title: '9' },
  'S(KC_7)': { name: '0', alias: 'DP_0', title: '0' },
  KC_AMPR: { name: '0', alias: 'DP_0', title: '0' },
  'S(KC_8)': { name: '2', alias: 'DP_2', title: '2' },
  KC_ASTR: { name: '2', alias: 'DP_2', title: '2' },
  'S(KC_9)': { name: '4', alias: 'DP_4', title: '4' },
  KC_LPRN: { name: '4', alias: 'DP_4', title: '4' },
  'S(KC_0)': { name: '6', alias: 'DP_6', title: '6' },
  KC_RPRN: { name: '6', alias: 'DP_6', title: '6' },
  'S(KC_MINS)': { name: '8', alias: 'DP_8', title: '8' },
  KC_UNDS: { name: '8', alias: 'DP_8', title: '8' },
  'S(KC_EQL)': { name: '`', alias: 'DP_GRV', title: '`' },
  KC_PLUS: { name: '`', alias: 'DP_GRV', title: '`' },
  // Row 2
  'S(KC_Q)': { name: ':', alias: 'DP_COLN', title: ':' },
  'S(KC_W)': { name: '<', alias: 'DP_LABK', title: '<' },
  'S(KC_E)': { name: '>', alias: 'DP_RABK', title: '>' },
  'S(KC_LBRC)': { name: '?', alias: 'DP_QUES', title: '?' },
  KC_LCBR: { name: '?', alias: 'DP_QUES', title: '?' },
  'S(KC_RBRC)': { name: '^', alias: 'DP_CIRC', title: '^' },
  KC_RCBR: { name: '^', alias: 'DP_CIRC', title: '^' },
  'S(KC_BSLS)': { name: '|', alias: 'DP_PIPE', title: '|' },
  KC_PIPE: { name: '|', alias: 'DP_PIPE', title: '|' },
  // Row 3
  'S(KC_QUOT)': { name: '_', alias: 'DP_UNDS', title: '_' },
  KC_DQUO: { name: '_', alias: 'DP_UNDS', title: '_' },
  // Row 4
  'S(KC_Z)': { name: '"', alias: 'DP_DQUO', title: '"' },

  /* Other keys */
  KC_NUHS: { name: '|\n\\', title: '\\ and |' },
  'S(KC_NUHS)': { name: '|', title: '|' },
  KC_NUBS: { name: '|\n\\', title: '\\ and |' },
  'S(KC_NUBS)': { name: '|', title: '|' },
  KC_LT: { name: 'W', alias: 'S(DP_W)', title: 'W' },
  KC_GT: { name: 'V', alias: 'S(DP_V)', title: 'V' },
  KC_COLN: { name: 'S', alias: 'S(DP_S)', title: 'S' },
  KC_QUES: { name: 'Z', alias: 'S(DP_Z)', title: 'Z' },

  SC_LSPO: { name: 'LS / 4', title: 'Left Shift when held, 4 when tapped' },
  SC_RSPC: { name: 'RS / 6', title: 'Right Shift when held, 6 when tapped' },
  SC_LCPO: { name: 'LC / 4', title: 'Left Control when held, 4 when tapped' },
  SC_RCPC: { name: 'RC / 6', title: 'Right Control when held, 6 when tapped' },
  SC_LAPO: { name: 'LA / 4', title: 'Left Alt when held, 4 when tapped' },
  SC_RAPC: { name: 'RA / 6', title: 'Right Alt when held, 6 when tapped' },

  QK_GESC: {
    name: '$/~\nEsc',
    title: 'Esc normally, but $ when GUI is active or ~ when Shift is active'
  }
};
