/* Copyright 2022 - Generated by convert_keymap_extras_header.js
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

export default {
  /*
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ º │ 1 │ 2 │ 3 │ 4 │ 5 │ 6 │ 7 │ 8 │ 9 │ 0 │ ' │ ¡ │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │ Q │ W │ E │ R │ T │ Y │ U │ I │ O │ P │ ` │ + │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │ A │ S │ D │ F │ G │ H │ J │ K │ L │ Ñ │ ´ │ Ç │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │ < │ Z │ X │ C │ V │ B │ N │ M │ , │ . │ - │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  KC_GRV: { name: 'ª\nº', alias: 'ES_MORD', title: 'º and ª' },
  KC_1: { name: '!\n1', alias: 'ES_1', title: '1 and !' },
  KC_2: { name: '"\n2', alias: 'ES_2', title: '2 and "' },
  KC_3: { name: '·\n3', alias: 'ES_3', title: '3 and ·' },
  KC_4: { name: '$\n4', alias: 'ES_4', title: '4 and $' },
  KC_5: { name: '%\n5', alias: 'ES_5', title: '5 and %' },
  KC_6: { name: '&\n6', alias: 'ES_6', title: '6 and &' },
  KC_7: { name: '/\n7', alias: 'ES_7', title: '7 and /' },
  KC_8: { name: '(\n8', alias: 'ES_8', title: '8 and (' },
  KC_9: { name: ')\n9', alias: 'ES_9', title: '9 and )' },
  KC_0: { name: '=\n0', alias: 'ES_0', title: '0 and =' },
  KC_MINS: { name: "?\n'", alias: 'ES_QUOT', title: "' and ?" },
  KC_EQL: { name: '¿\n¡', alias: 'ES_IEXL', title: '¡ and ¿' },
  // Row 2
  KC_Q: { name: 'Q', alias: 'ES_Q', title: 'q and Q' },
  KC_W: { name: 'W', alias: 'ES_W', title: 'w and W' },
  KC_E: { name: 'E', alias: 'ES_E', title: 'e and E' },
  KC_R: { name: 'R', alias: 'ES_R', title: 'r and R' },
  KC_T: { name: 'T', alias: 'ES_T', title: 't and T' },
  KC_Y: { name: 'Y', alias: 'ES_Y', title: 'y and Y' },
  KC_U: { name: 'U', alias: 'ES_U', title: 'u and U' },
  KC_I: { name: 'I', alias: 'ES_I', title: 'i and I' },
  KC_O: { name: 'O', alias: 'ES_O', title: 'o and O' },
  KC_P: { name: 'P', alias: 'ES_P', title: 'p and P' },
  KC_LBRC: { name: '^\n`', alias: 'ES_GRV', title: '◌̀ (dead) and ◌̂ (dead)' },
  KC_RBRC: { name: '*\n+', alias: 'ES_PLUS', title: '+ and *' },
  // Row 3
  KC_A: { name: 'A', alias: 'ES_A', title: 'a and A' },
  KC_S: { name: 'S', alias: 'ES_S', title: 's and S' },
  KC_D: { name: 'D', alias: 'ES_D', title: 'd and D' },
  KC_F: { name: 'F', alias: 'ES_F', title: 'f and F' },
  KC_G: { name: 'G', alias: 'ES_G', title: 'g and G' },
  KC_H: { name: 'H', alias: 'ES_H', title: 'h and H' },
  KC_J: { name: 'J', alias: 'ES_J', title: 'j and J' },
  KC_K: { name: 'K', alias: 'ES_K', title: 'k and K' },
  KC_L: { name: 'L', alias: 'ES_L', title: 'l and L' },
  KC_SCLN: { name: 'Ñ', alias: 'ES_NTIL', title: 'ñ and Ñ' },
  KC_QUOT: { name: '¨\n´', alias: 'ES_ACUT', title: '◌́ (dead) and ◌̈ (dead)' },
  KC_NUHS: { name: 'Ç', alias: 'ES_CCED', title: 'ç and Ç' },
  // Row 4
  KC_NUBS: { name: '>\n<', alias: 'ES_LABK', title: '< and >' },
  KC_Z: { name: 'Z', alias: 'ES_Z', title: 'z and Z' },
  KC_X: { name: 'X', alias: 'ES_X', title: 'x and X' },
  KC_C: { name: 'C', alias: 'ES_C', title: 'c and C' },
  KC_V: { name: 'V', alias: 'ES_V', title: 'v and V' },
  KC_B: { name: 'B', alias: 'ES_B', title: 'b and B' },
  KC_N: { name: 'N', alias: 'ES_N', title: 'n and N' },
  KC_M: { name: 'M', alias: 'ES_M', title: 'm and M' },
  KC_COMM: { name: ';\n,', alias: 'ES_COMM', title: ', and ;' },
  KC_DOT: { name: ':\n.', alias: 'ES_DOT', title: '. and :' },
  KC_SLSH: { name: '_\n-', alias: 'ES_MINS', title: '- and _' },

  /* Shifted symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ ª │ ! │ " │ · │ $ │ % │ & │ / │ ( │ ) │ = │ ? │ ¿ │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │   │   │   │   │   │   │   │   │   │   │ ^ │ * │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │   │   │   │   │   │   │   │   │   │   │ ¨ │   │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │ > │   │   │   │   │   │   │   │ ; │ : │ _ │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  'S(KC_GRV)': { name: 'ª', alias: 'ES_FORD', title: 'ª' },
  KC_TILD: { name: 'ª', alias: 'ES_FORD', title: 'ª' },
  'S(KC_1)': { name: '!', alias: 'ES_EXLM', title: '!' },
  KC_EXLM: { name: '!', alias: 'ES_EXLM', title: '!' },
  'S(KC_2)': { name: '"', alias: 'ES_DQUO', title: '"' },
  KC_AT: { name: '"', alias: 'ES_DQUO', title: '"' },
  'S(KC_3)': { name: '·', alias: 'ES_BULT', title: '·' },
  KC_HASH: { name: '·', alias: 'ES_BULT', title: '·' },
  'S(KC_4)': { name: '$', alias: 'ES_DLR', title: '$' },
  KC_DLR: { name: '$', alias: 'ES_DLR', title: '$' },
  'S(KC_5)': { name: '%', alias: 'ES_PERC', title: '%' },
  KC_PERC: { name: '%', alias: 'ES_PERC', title: '%' },
  'S(KC_6)': { name: '&', alias: 'ES_AMPR', title: '&' },
  KC_CIRC: { name: '&', alias: 'ES_AMPR', title: '&' },
  'S(KC_7)': { name: '/', alias: 'ES_SLSH', title: '/' },
  KC_AMPR: { name: '/', alias: 'ES_SLSH', title: '/' },
  'S(KC_8)': { name: '(', alias: 'ES_LPRN', title: '(' },
  KC_ASTR: { name: '(', alias: 'ES_LPRN', title: '(' },
  'S(KC_9)': { name: ')', alias: 'ES_RPRN', title: ')' },
  KC_LPRN: { name: ')', alias: 'ES_RPRN', title: ')' },
  'S(KC_0)': { name: '=', alias: 'ES_EQL', title: '=' },
  KC_RPRN: { name: '=', alias: 'ES_EQL', title: '=' },
  'S(KC_MINS)': { name: '?', alias: 'ES_QUES', title: '?' },
  KC_UNDS: { name: '?', alias: 'ES_QUES', title: '?' },
  'S(KC_EQL)': { name: '¿', alias: 'ES_IQUE', title: '¿' },
  KC_PLUS: { name: '¿', alias: 'ES_IQUE', title: '¿' },
  // Row 2
  'S(KC_LBRC)': { name: '^', alias: 'ES_CIRC', title: '◌̂ (dead)' },
  KC_LCBR: { name: '^', alias: 'ES_CIRC', title: '◌̂ (dead)' },
  'S(KC_RBRC)': { name: '*', alias: 'ES_ASTR', title: '*' },
  KC_RCBR: { name: '*', alias: 'ES_ASTR', title: '*' },
  // Row 3
  'S(KC_QUOT)': { name: '¨', alias: 'ES_DIAE', title: '◌̈ (dead)' },
  KC_DQUO: { name: '¨', alias: 'ES_DIAE', title: '◌̈ (dead)' },
  // Row 4
  'S(KC_NUBS)': { name: '>', alias: 'ES_RABK', title: '>' },
  'S(KC_COMM)': { name: ';', alias: 'ES_SCLN', title: ';' },
  KC_LT: { name: ';', alias: 'ES_SCLN', title: ';' },
  'S(KC_DOT)': { name: ':', alias: 'ES_COLN', title: ':' },
  KC_GT: { name: ':', alias: 'ES_COLN', title: ':' },
  'S(KC_SLSH)': { name: '_', alias: 'ES_UNDS', title: '_' },
  KC_QUES: { name: '_', alias: 'ES_UNDS', title: '_' },

  /* AltGr symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ \ │ | │ @ │ # │ ~ │ € │ ¬ │   │   │   │   │   │   │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │   │   │   │   │   │   │   │   │   │   │ [ │ ] │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │   │   │   │   │   │   │   │   │   │   │ { │ } │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │   │   │   │   │   │   │   │   │   │   │   │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  'ALGR(KC_GRV)': { name: '\\', alias: 'ES_BSLS', title: '\\' },
  'ALGR(KC_1)': { name: '|', alias: 'ES_PIPE', title: '|' },
  'ALGR(KC_2)': { name: '@', alias: 'ES_AT', title: '@' },
  'ALGR(KC_3)': { name: '#', alias: 'ES_HASH', title: '#' },
  'ALGR(KC_4)': { name: '~', alias: 'ES_TILD', title: '~' },
  'ALGR(KC_5)': { name: '€', alias: 'ES_EURO', title: '€' },
  'ALGR(KC_6)': { name: '¬', alias: 'ES_NOT', title: '¬' },
  // Row 2
  'ALGR(KC_LBRC)': { name: '[', alias: 'ES_LBRC', title: '[' },
  'ALGR(KC_RBRC)': { name: ']', alias: 'ES_RBRC', title: ']' },
  // Row 3
  'ALGR(KC_QUOT)': { name: '{', alias: 'ES_LCBR', title: '{' },
  'ALGR(KC_NUHS)': { name: '}', alias: 'ES_RCBR', title: '}' },

  /* Other keys */
  KC_BSLS: { name: 'Ç', title: 'Ć' },
  'S(KC_BSLS)': { name: 'Ç', title: 'Ç' },
  KC_COLN: { name: 'Ñ', alias: 'S(ES_NTIL)', title: 'Ñ' },
  KC_PIPE: { name: 'Ç', alias: 'ES_CCED', title: 'Ç' },

  SC_LSPO: { name: 'LS / )', title: 'Left Shift when held, ) when tapped' },
  SC_RSPC: { name: 'RS / =', title: 'Right Shift when held, = when tapped' },
  SC_LCPO: { name: 'LC / )', title: 'Left Control when held, ) when tapped' },
  SC_RCPC: { name: 'RC / =', title: 'Right Control when held, = when tapped' },
  SC_LAPO: { name: 'LA / )', title: 'Left Alt when held, ) when tapped' },
  SC_RAPC: { name: 'RA / =', title: 'Right Alt when held, = when tapped' },

  QK_GESC: {
    name: 'º/ª\nEsc',
    title: 'Esc normally, but º when GUI is active or ª when Shift is active'
  }
};
