/* Copyright 2022 - Generated by convert_keymap_extras_header.js
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

export default {
  /*
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ ` │ 1 │ 2 │ 3 │ 4 │ 5 │ 6 │ 7 │ 8 │ 9 │ 0 │ [ │ ] │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │ ' │ , │ . │ P │ Y │ F │ G │ C │ R │ L │ / │ = │  \  │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴─────┤
   * │      │ A │ O │ E │ U │ I │ D │ H │ T │ N │ S │ - │        │
   * ├──────┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴────────┤
   * │        │ ; │ Q │ J │ K │ X │ B │ M │ W │ V │ Z │          │
   * ├────┬───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  KC_GRV: { name: '~\n`', alias: 'DV_GRV', title: '` and ~' },
  KC_1: { name: '!\n1', alias: 'DV_1', title: '1 and !' },
  KC_2: { name: '@\n2', alias: 'DV_2', title: '2 and @' },
  KC_3: { name: '#\n3', alias: 'DV_3', title: '3 and #' },
  KC_4: { name: '$\n4', alias: 'DV_4', title: '4 and $' },
  KC_5: { name: '%\n5', alias: 'DV_5', title: '5 and %' },
  KC_6: { name: '^\n6', alias: 'DV_6', title: '6 and ^' },
  KC_7: { name: '&\n7', alias: 'DV_7', title: '7 and &' },
  KC_8: { name: '*\n8', alias: 'DV_8', title: '8 and *' },
  KC_9: { name: '(\n9', alias: 'DV_9', title: '9 and (' },
  KC_0: { name: ')\n0', alias: 'DV_0', title: '0 and )' },
  KC_MINS: { name: '{\n[', alias: 'DV_LBRC', title: '[ and {' },
  KC_EQL: { name: '}\n]', alias: 'DV_RBRC', title: '] and }' },
  // Row 2
  KC_Q: { name: '"\n\'', alias: 'DV_QUOT', title: '\' and "' },
  KC_W: { name: '<\n,', alias: 'DV_COMM', title: ', and <' },
  KC_E: { name: '>\n.', alias: 'DV_DOT', title: '. and >' },
  KC_R: { name: 'P', alias: 'DV_P', title: 'p and P' },
  KC_T: { name: 'Y', alias: 'DV_Y', title: 'y and Y' },
  KC_Y: { name: 'F', alias: 'DV_F', title: 'f and F' },
  KC_U: { name: 'G', alias: 'DV_G', title: 'g and G' },
  KC_I: { name: 'C', alias: 'DV_C', title: 'c and C' },
  KC_O: { name: 'R', alias: 'DV_R', title: 'r and R' },
  KC_P: { name: 'L', alias: 'DV_L', title: 'l and L' },
  KC_LBRC: { name: '?\n/', alias: 'DV_SLSH', title: '/ and ?' },
  KC_RBRC: { name: '+\n=', alias: 'DV_EQL', title: '= and +' },
  KC_BSLS: { name: '|\n\\', alias: 'DV_BSLS', title: '\\ and |' },
  // Row 3
  KC_A: { name: 'A', alias: 'DV_A', title: 'a and A' },
  KC_S: { name: 'O', alias: 'DV_O', title: 'o and O' },
  KC_D: { name: 'E', alias: 'DV_E', title: 'e and E' },
  KC_F: { name: 'U', alias: 'DV_U', title: 'u and U' },
  KC_G: { name: 'I', alias: 'DV_I', title: 'i and I' },
  KC_H: { name: 'D', alias: 'DV_D', title: 'd and D' },
  KC_J: { name: 'H', alias: 'DV_H', title: 'h and H' },
  KC_K: { name: 'T', alias: 'DV_T', title: 't and T' },
  KC_L: { name: 'N', alias: 'DV_N', title: 'n and N' },
  KC_SCLN: { name: 'S', alias: 'DV_S', title: 's and S' },
  KC_QUOT: { name: '_\n-', alias: 'DV_MINS', title: '- and _' },
  // Row 4
  KC_Z: { name: ':\n;', alias: 'DV_SCLN', title: '; and :' },
  KC_X: { name: 'Q', alias: 'DV_Q', title: 'q and Q' },
  KC_C: { name: 'J', alias: 'DV_J', title: 'j and J' },
  KC_V: { name: 'K', alias: 'DV_K', title: 'k and K' },
  KC_B: { name: 'X', alias: 'DV_X', title: 'x and X' },
  KC_N: { name: 'B', alias: 'DV_B', title: 'b and B' },
  KC_M: { name: 'M', alias: 'DV_M', title: 'm and M' },
  KC_COMM: { name: 'W', alias: 'DV_W', title: 'w and W' },
  KC_DOT: { name: 'V', alias: 'DV_V', title: 'v and V' },
  KC_SLSH: { name: 'Z', alias: 'DV_Z', title: 'z and Z' },

  /* Shifted symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ ~ │ ! │ @ │ # │ $ │ % │ ^ │ & │ * │ ( │ ) │ { │ } │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │ " │ < │ > │   │   │   │   │   │   │   │ ? │ + │  |  │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴─────┤
   * │      │   │   │   │   │   │   │   │   │   │   │ _ │        │
   * ├──────┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴────────┤
   * │        │ : │   │   │   │   │   │   │   │   │   │          │
   * ├────┬───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  'S(KC_GRV)': { name: '~', alias: 'DV_TILD', title: '~' },
  KC_TILD: { name: '~', alias: 'DV_TILD', title: '~' },
  'S(KC_1)': { name: '!', alias: 'DV_EXLM', title: '!' },
  KC_EXLM: { name: '!', alias: 'DV_EXLM', title: '!' },
  'S(KC_2)': { name: '@', alias: 'DV_AT', title: '@' },
  KC_AT: { name: '@', alias: 'DV_AT', title: '@' },
  'S(KC_3)': { name: '#', alias: 'DV_HASH', title: '#' },
  KC_HASH: { name: '#', alias: 'DV_HASH', title: '#' },
  'S(KC_4)': { name: '$', alias: 'DV_DLR', title: '$' },
  KC_DLR: { name: '$', alias: 'DV_DLR', title: '$' },
  'S(KC_5)': { name: '%', alias: 'DV_PERC', title: '%' },
  KC_PERC: { name: '%', alias: 'DV_PERC', title: '%' },
  'S(KC_6)': { name: '^', alias: 'DV_CIRC', title: '^' },
  KC_CIRC: { name: '^', alias: 'DV_CIRC', title: '^' },
  'S(KC_7)': { name: '&', alias: 'DV_AMPR', title: '&' },
  KC_AMPR: { name: '&', alias: 'DV_AMPR', title: '&' },
  'S(KC_8)': { name: '*', alias: 'DV_ASTR', title: '*' },
  KC_ASTR: { name: '*', alias: 'DV_ASTR', title: '*' },
  'S(KC_9)': { name: '(', alias: 'DV_LPRN', title: '(' },
  KC_LPRN: { name: '(', alias: 'DV_LPRN', title: '(' },
  'S(KC_0)': { name: ')', alias: 'DV_RPRN', title: ')' },
  KC_RPRN: { name: ')', alias: 'DV_RPRN', title: ')' },
  'S(KC_MINS)': { name: '{', alias: 'DV_LCBR', title: '{' },
  KC_UNDS: { name: '{', alias: 'DV_LCBR', title: '{' },
  'S(KC_EQL)': { name: '}', alias: 'DV_RCBR', title: '}' },
  KC_PLUS: { name: '}', alias: 'DV_RCBR', title: '}' },
  // Row 2
  'S(KC_Q)': { name: '"', alias: 'DV_DQUO', title: '"' },
  'S(KC_W)': { name: '<', alias: 'DV_LABK', title: '<' },
  'S(KC_E)': { name: '>', alias: 'DV_RABK', title: '>' },
  'S(KC_LBRC)': { name: '?', alias: 'DV_QUES', title: '?' },
  KC_LCBR: { name: '?', alias: 'DV_QUES', title: '?' },
  'S(KC_RBRC)': { name: '+', alias: 'DV_PLUS', title: '+' },
  KC_RCBR: { name: '+', alias: 'DV_PLUS', title: '+' },
  'S(KC_BSLS)': { name: '|', alias: 'DV_PIPE', title: '|' },
  KC_PIPE: { name: '|', alias: 'DV_PIPE', title: '|' },
  // Row 3
  'S(KC_QUOT)': { name: '_', alias: 'DV_UNDS', title: '_' },
  KC_DQUO: { name: '_', alias: 'DV_UNDS', title: '_' },
  // Row 4
  'S(KC_Z)': { name: ':', alias: 'DV_COLN', title: ':' },

  /* Other keys */
  KC_NUHS: { name: '|\n\\', title: '\\ and |' },
  'S(KC_NUHS)': { name: '|', title: '|' },
  KC_NUBS: { name: '|\n\\', title: '\\ and |' },
  'S(KC_NUBS)': { name: '|', title: '|' },
  KC_LT: { name: 'W', alias: 'S(DV_W)', title: 'W' },
  KC_GT: { name: 'V', alias: 'S(DV_V)', title: 'V' },
  KC_COLN: { name: 'S', alias: 'S(DV_S)', title: 'S' },
  KC_QUES: { name: 'Z', alias: 'S(DV_Z)', title: 'Z' },

  SC_LSPO: { name: 'LS / (', title: 'Left Shift when held, ( when tapped' },
  SC_RSPC: { name: 'RS / )', title: 'Right Shift when held, ) when tapped' },
  SC_LCPO: { name: 'LC / (', title: 'Left Control when held, ( when tapped' },
  SC_RCPC: { name: 'RC / )', title: 'Right Control when held, ) when tapped' },
  SC_LAPO: { name: 'LA / (', title: 'Left Alt when held, ( when tapped' },
  SC_RAPC: { name: 'RA / )', title: 'Right Alt when held, ) when tapped' },

  QK_GESC: {
    name: '`/~\nEsc',
    title: 'Esc normally, but ` when GUI is active or ~ when Shift is active'
  }
};
