/* Copyright 2022 - Generated by convert_keymap_extras_header.js
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

export default {
  /*
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ \ │ 1 │ 2 │ 3 │ 4 │ 5 │ 6 │ 7 │ 8 │ 9 │ 0 │ ' │ « │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │ Q │ W │ E │ R │ T │ Y │ U │ I │ O │ P │ + │ ´ │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │ A │ S │ D │ F │ G │ H │ J │ K │ L │ Ç │ º │ ~ │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │ < │ Z │ X │ C │ V │ B │ N │ M │ , │ . │ - │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  KC_GRV: { name: '|\n\\', alias: 'PT_BSLS', title: '\\ and |' },
  KC_1: { name: '!\n1', alias: 'PT_1', title: '1 and !' },
  KC_2: { name: '"\n2', alias: 'PT_2', title: '2 and "' },
  KC_3: { name: '#\n3', alias: 'PT_3', title: '3 and #' },
  KC_4: { name: '$\n4', alias: 'PT_4', title: '4 and $' },
  KC_5: { name: '%\n5', alias: 'PT_5', title: '5 and %' },
  KC_6: { name: '&\n6', alias: 'PT_6', title: '6 and &' },
  KC_7: { name: '/\n7', alias: 'PT_7', title: '7 and /' },
  KC_8: { name: '(\n8', alias: 'PT_8', title: '8 and (' },
  KC_9: { name: ')\n9', alias: 'PT_9', title: '9 and )' },
  KC_0: { name: '=\n0', alias: 'PT_0', title: '0 and =' },
  KC_MINS: { name: "?\n'", alias: 'PT_QUOT', title: "' and ?" },
  KC_EQL: { name: '»\n«', alias: 'PT_LDAQ', title: '« and »' },
  // Row 2
  KC_Q: { name: 'Q', alias: 'PT_Q', title: 'q and Q' },
  KC_W: { name: 'W', alias: 'PT_W', title: 'w and W' },
  KC_E: { name: 'E', alias: 'PT_E', title: 'e and E' },
  KC_R: { name: 'R', alias: 'PT_R', title: 'r and R' },
  KC_T: { name: 'T', alias: 'PT_T', title: 't and T' },
  KC_Y: { name: 'Y', alias: 'PT_Y', title: 'y and Y' },
  KC_U: { name: 'U', alias: 'PT_U', title: 'u and U' },
  KC_I: { name: 'I', alias: 'PT_I', title: 'i and I' },
  KC_O: { name: 'O', alias: 'PT_O', title: 'o and O' },
  KC_P: { name: 'P', alias: 'PT_P', title: 'p and P' },
  KC_LBRC: { name: '*\n+', alias: 'PT_PLUS', title: '+ and *' },
  KC_RBRC: { name: '`\n´', alias: 'PT_ACUT', title: '◌́ (dead) and ◌̀ (dead)' },
  // Row 3
  KC_A: { name: 'A', alias: 'PT_A', title: 'a and A' },
  KC_S: { name: 'S', alias: 'PT_S', title: 's and S' },
  KC_D: { name: 'D', alias: 'PT_D', title: 'd and D' },
  KC_F: { name: 'F', alias: 'PT_F', title: 'f and F' },
  KC_G: { name: 'G', alias: 'PT_G', title: 'g and G' },
  KC_H: { name: 'H', alias: 'PT_H', title: 'h and H' },
  KC_J: { name: 'J', alias: 'PT_J', title: 'j and J' },
  KC_K: { name: 'K', alias: 'PT_K', title: 'k and K' },
  KC_L: { name: 'L', alias: 'PT_L', title: 'l and L' },
  KC_SCLN: { name: 'Ç', alias: 'PT_CCED', title: 'ç and Ç' },
  KC_QUOT: { name: 'ª\nº', alias: 'PT_MORD', title: 'º and ª' },
  KC_NUHS: { name: '^\n~', alias: 'PT_TILD', title: '◌̃ (dead) and ◌̂ (dead)' },
  // Row 4
  KC_NUBS: { name: '>\n<', alias: 'PT_LABK', title: '< and >' },
  KC_Z: { name: 'Z', alias: 'PT_Z', title: 'z and Z' },
  KC_X: { name: 'X', alias: 'PT_X', title: 'x and X' },
  KC_C: { name: 'C', alias: 'PT_C', title: 'c and C' },
  KC_V: { name: 'V', alias: 'PT_V', title: 'v and V' },
  KC_B: { name: 'B', alias: 'PT_B', title: 'b and B' },
  KC_N: { name: 'N', alias: 'PT_N', title: 'n and N' },
  KC_M: { name: 'M', alias: 'PT_M', title: 'm and M' },
  KC_COMM: { name: ';\n,', alias: 'PT_COMM', title: ', and ;' },
  KC_DOT: { name: ':\n.', alias: 'PT_DOT', title: '. and :' },
  KC_SLSH: { name: '_\n-', alias: 'PT_MINS', title: '- and _' },

  /* Shifted symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ | │ ! │ " │ # │ $ │ % │ & │ / │ ( │ ) │ = │ ? │ » │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │   │   │   │   │   │   │   │   │   │   │ * │ ` │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │   │   │   │   │   │   │   │   │   │   │ ª │ ^ │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │ > │   │   │   │   │   │   │   │ ; │ : │ _ │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  'S(KC_GRV)': { name: '|', alias: 'PT_PIPE', title: '|' },
  KC_TILD: { name: '|', alias: 'PT_PIPE', title: '|' },
  'S(KC_1)': { name: '!', alias: 'PT_EXLM', title: '!' },
  KC_EXLM: { name: '!', alias: 'PT_EXLM', title: '!' },
  'S(KC_2)': { name: '"', alias: 'PT_DQUO', title: '"' },
  KC_AT: { name: '"', alias: 'PT_DQUO', title: '"' },
  'S(KC_3)': { name: '#', alias: 'PT_HASH', title: '#' },
  KC_HASH: { name: '#', alias: 'PT_HASH', title: '#' },
  'S(KC_4)': { name: '$', alias: 'PT_DLR', title: '$' },
  KC_DLR: { name: '$', alias: 'PT_DLR', title: '$' },
  'S(KC_5)': { name: '%', alias: 'PT_PERC', title: '%' },
  KC_PERC: { name: '%', alias: 'PT_PERC', title: '%' },
  'S(KC_6)': { name: '&', alias: 'PT_AMPR', title: '&' },
  KC_CIRC: { name: '&', alias: 'PT_AMPR', title: '&' },
  'S(KC_7)': { name: '/', alias: 'PT_SLSH', title: '/' },
  KC_AMPR: { name: '/', alias: 'PT_SLSH', title: '/' },
  'S(KC_8)': { name: '(', alias: 'PT_LPRN', title: '(' },
  KC_ASTR: { name: '(', alias: 'PT_LPRN', title: '(' },
  'S(KC_9)': { name: ')', alias: 'PT_RPRN', title: ')' },
  KC_LPRN: { name: ')', alias: 'PT_RPRN', title: ')' },
  'S(KC_0)': { name: '=', alias: 'PT_EQL', title: '=' },
  KC_RPRN: { name: '=', alias: 'PT_EQL', title: '=' },
  'S(KC_MINS)': { name: '?', alias: 'PT_QUES', title: '?' },
  KC_UNDS: { name: '?', alias: 'PT_QUES', title: '?' },
  'S(KC_EQL)': { name: '»', alias: 'PT_RDAQ', title: '»' },
  KC_PLUS: { name: '»', alias: 'PT_RDAQ', title: '»' },
  // Row 2
  'S(KC_LBRC)': { name: '*', alias: 'PT_ASTR', title: '*' },
  KC_LCBR: { name: '*', alias: 'PT_ASTR', title: '*' },
  'S(KC_RBRC)': { name: '`', alias: 'PT_GRV', title: '◌̀ (dead)' },
  KC_RCBR: { name: '`', alias: 'PT_GRV', title: '◌̀ (dead)' },
  // Row 3
  'S(KC_QUOT)': { name: 'ª', alias: 'PT_FORD', title: 'ª' },
  KC_DQUO: { name: 'ª', alias: 'PT_FORD', title: 'ª' },
  'S(KC_NUHS)': { name: '^', alias: 'PT_CIRC', title: '◌̂ (dead)' },
  // Row 4
  'S(KC_NUBS)': { name: '>', alias: 'PT_RABK', title: '>' },
  'S(KC_COMM)': { name: ';', alias: 'PT_SCLN', title: ';' },
  KC_LT: { name: ';', alias: 'PT_SCLN', title: ';' },
  'S(KC_DOT)': { name: ':', alias: 'PT_COLN', title: ':' },
  KC_GT: { name: ':', alias: 'PT_COLN', title: ':' },
  'S(KC_SLSH)': { name: '_', alias: 'PT_UNDS', title: '_' },
  KC_QUES: { name: '_', alias: 'PT_UNDS', title: '_' },

  /* AltGr symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │   │   │ @ │ £ │ § │   │   │ { │ [ │ ] │ } │   │   │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │   │   │ € │   │   │   │   │   │   │   │ ¨ │   │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │   │   │   │   │   │   │   │   │   │   │   │   │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │   │   │   │   │   │   │   │   │   │   │   │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  'ALGR(KC_2)': { name: '@', alias: 'PT_AT', title: '@' },
  'ALGR(KC_3)': { name: '£', alias: 'PT_PND', title: '£' },
  'ALGR(KC_4)': { name: '§', alias: 'PT_SECT', title: '§' },
  'ALGR(KC_7)': { name: '{', alias: 'PT_LCBR', title: '{' },
  'ALGR(KC_8)': { name: '[', alias: 'PT_LBRC', title: '[' },
  'ALGR(KC_9)': { name: ']', alias: 'PT_RBRC', title: ']' },
  'ALGR(KC_0)': { name: '}', alias: 'PT_RCBR', title: '}' },
  // Row 2
  'ALGR(KC_LBRC)': { name: '¨', alias: 'PT_DIAE', title: '◌̈ (dead)' },
  'ALGR(KC_E)': { name: '€', alias: 'PT_EURO', title: '€' },

  /* Other keys */
  KC_BSLS: { name: '^\n~', title: '◌̃ (dead) and ◌̂ (dead)' },
  'S(KC_BSLS)': { name: '^', title: '◌̂ (dead)' },
  KC_COLN: { name: 'Ç', alias: 'S(PT_CCED)', title: 'Ç' },
  KC_PIPE: { name: '^', alias: 'PT_CIRC', title: '^' },

  SC_LSPO: { name: 'LS / )', title: 'Left Shift when held, ) when tapped' },
  SC_RSPC: { name: 'RS / =', title: 'Right Shift when held, = when tapped' },
  SC_LCPO: { name: 'LC / )', title: 'Left Control when held, ) when tapped' },
  SC_RCPC: { name: 'RC / =', title: 'Right Control when held, = when tapped' },
  SC_LAPO: { name: 'LA / )', title: 'Left Alt when held, ) when tapped' },
  SC_RAPC: { name: 'RA / =', title: 'Right Alt when held, = when tapped' },

  QK_GESC: {
    name: '\\/|\nEsc',
    title: 'Esc normally, but \\ when GUI is active or | when Shift is active'
  }
};
