/* Copyright 2022 - Generated by convert_keymap_extras_header.js
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

export default {
  /*
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ ' │ 1 │ 2 │ 3 │ 4 │ 5 │ 6 │ 7 │ 8 │ 9 │ 0 │ - │ = │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │ Q │ W │ E │ R │ T │ Y │ U │ I │ O │ P │ ´ │ [ │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │ A │ S │ D │ F │ G │ H │ J │ K │ L │ Ç │ ~ │ ] │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴────┤
   * │    │ \ │ Z │ X │ C │ V │ B │ N │ M │ , │ . │ ; │ / │      │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬──┴─┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  KC_GRV: { name: '"\n\'', alias: 'BR_QUOT', title: '\' and "' },
  KC_1: { name: '!\n1', alias: 'BR_1', title: '1 and !' },
  KC_2: { name: '@\n2', alias: 'BR_2', title: '2 and @' },
  KC_3: { name: '#\n3', alias: 'BR_3', title: '3 and #' },
  KC_4: { name: '$\n4', alias: 'BR_4', title: '4 and $' },
  KC_5: { name: '%\n5', alias: 'BR_5', title: '5 and %' },
  KC_6: { name: '¨\n6', alias: 'BR_6', title: '6 and ◌̈ (dead)' },
  KC_7: { name: '&\n7', alias: 'BR_7', title: '7 and &' },
  KC_8: { name: '*\n8', alias: 'BR_8', title: '8 and *' },
  KC_9: { name: '(\n9', alias: 'BR_9', title: '9 and (' },
  KC_0: { name: ')\n0', alias: 'BR_0', title: '0 and )' },
  KC_MINS: { name: '_\n-', alias: 'BR_MINS', title: '- and _' },
  KC_EQL: { name: '+\n=', alias: 'BR_EQL', title: '= and +' },
  // Row 2
  KC_Q: { name: 'Q', alias: 'BR_Q', title: 'q and Q' },
  KC_W: { name: 'W', alias: 'BR_W', title: 'w and W' },
  KC_E: { name: 'E', alias: 'BR_E', title: 'e and E' },
  KC_R: { name: 'R', alias: 'BR_R', title: 'r and R' },
  KC_T: { name: 'T', alias: 'BR_T', title: 't and T' },
  KC_Y: { name: 'Y', alias: 'BR_Y', title: 'y and Y' },
  KC_U: { name: 'U', alias: 'BR_U', title: 'u and U' },
  KC_I: { name: 'I', alias: 'BR_I', title: 'i and I' },
  KC_O: { name: 'O', alias: 'BR_O', title: 'o and O' },
  KC_P: { name: 'P', alias: 'BR_P', title: 'p and P' },
  KC_LBRC: {
    name: '`\n´',
    alias: 'BR_ACUT',
    title: '◌́ (dead) and ◌̀ (dead)'
  },
  KC_RBRC: { name: '{\n[', alias: 'BR_LBRC', title: '[ and {' },
  // Row 3
  KC_A: { name: 'A', alias: 'BR_A', title: 'a and A' },
  KC_S: { name: 'S', alias: 'BR_S', title: 's and S' },
  KC_D: { name: 'D', alias: 'BR_D', title: 'd and D' },
  KC_F: { name: 'F', alias: 'BR_F', title: 'f and F' },
  KC_G: { name: 'G', alias: 'BR_G', title: 'g and G' },
  KC_H: { name: 'H', alias: 'BR_H', title: 'h and H' },
  KC_J: { name: 'J', alias: 'BR_J', title: 'j and J' },
  KC_K: { name: 'K', alias: 'BR_K', title: 'k and K' },
  KC_L: { name: 'L', alias: 'BR_L', title: 'l and L' },
  KC_SCLN: { name: 'Ç', alias: 'BR_CCED', title: 'ç and Ç' },
  KC_QUOT: { name: '^\n~', alias: 'BR_TILD', title: '◌̃ (dead) and ◌̂ (dead)' },
  KC_BSLS: { name: '}\n]', alias: 'BR_RBRC', title: '] and }' },
  // Row 4
  KC_NUBS: { name: '|\n\\', alias: 'BR_BSLS', title: '\\ and |' },
  KC_Z: { name: 'Z', alias: 'BR_Z', title: 'z and Z' },
  KC_X: { name: 'X', alias: 'BR_X', title: 'x and X' },
  KC_C: { name: 'C', alias: 'BR_C', title: 'c and C' },
  KC_V: { name: 'V', alias: 'BR_V', title: 'v and V' },
  KC_B: { name: 'B', alias: 'BR_B', title: 'b and B' },
  KC_N: { name: 'N', alias: 'BR_N', title: 'n and N' },
  KC_M: { name: 'M', alias: 'BR_M', title: 'm and M' },
  KC_COMM: { name: '<\n,', alias: 'BR_COMM', title: ', and <' },
  KC_DOT: { name: '>\n.', alias: 'BR_DOT', title: '. and >' },
  KC_SLSH: { name: ':\n;', alias: 'BR_SCLN', title: '; and :' },
  KC_INT1: { name: '?\n/', alias: 'BR_SLSH', title: '/ and ?' },
  // Numpad
  KC_PCMM: { name: '.', alias: 'BR_PDOT', title: 'Keypad .' },
  KC_PDOT: { name: ',', alias: 'BR_PCMM', title: 'Keypad ,' },

  /* Shifted symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ " │ ! │ @ │ # │ $ │ % │ ¨ │ & │ * │ ( │ ) │ _ │ + │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │   │   │   │   │   │   │   │   │   │   │ ` │ { │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │   │   │   │   │   │   │   │   │   │   │ ^ │ } │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴────┤
   * │    │ | │   │   │   │   │   │   │   │ < │ > │ : │ ? │      │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬──┴─┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  'S(KC_GRV)': { name: '"', alias: 'BR_DQUO', title: '"' },
  KC_TILD: { name: '"', alias: 'BR_DQUO', title: '"' },
  'S(KC_1)': { name: '!', alias: 'BR_EXLM', title: '!' },
  KC_EXLM: { name: '!', alias: 'BR_EXLM', title: '!' },
  'S(KC_2)': { name: '@', alias: 'BR_AT', title: '@' },
  KC_AT: { name: '@', alias: 'BR_AT', title: '@' },
  'S(KC_3)': { name: '#', alias: 'BR_HASH', title: '#' },
  KC_HASH: { name: '#', alias: 'BR_HASH', title: '#' },
  'S(KC_4)': { name: '$', alias: 'BR_DLR', title: '$' },
  KC_DLR: { name: '$', alias: 'BR_DLR', title: '$' },
  'S(KC_5)': { name: '%', alias: 'BR_PERC', title: '%' },
  KC_PERC: { name: '%', alias: 'BR_PERC', title: '%' },
  'S(KC_6)': { name: '¨', alias: 'BR_DIAE', title: '◌̈ (dead)' },
  KC_CIRC: { name: '¨', alias: 'BR_DIAE', title: '◌̈ (dead)' },
  'S(KC_7)': { name: '&', alias: 'BR_AMPR', title: '&' },
  KC_AMPR: { name: '&', alias: 'BR_AMPR', title: '&' },
  'S(KC_8)': { name: '*', alias: 'BR_ASTR', title: '*' },
  KC_ASTR: { name: '*', alias: 'BR_ASTR', title: '*' },
  'S(KC_9)': { name: '(', alias: 'BR_LPRN', title: '(' },
  KC_LPRN: { name: '(', alias: 'BR_LPRN', title: '(' },
  'S(KC_0)': { name: ')', alias: 'BR_RPRN', title: ')' },
  KC_RPRN: { name: ')', alias: 'BR_RPRN', title: ')' },
  'S(KC_MINS)': { name: '_', alias: 'BR_UNDS', title: '_' },
  KC_UNDS: { name: '_', alias: 'BR_UNDS', title: '_' },
  'S(KC_EQL)': { name: '+', alias: 'BR_PLUS', title: '+' },
  KC_PLUS: { name: '+', alias: 'BR_PLUS', title: '+' },
  // Row 2
  'S(KC_LBRC)': { name: '`', alias: 'BR_GRV', title: '◌̀ (dead)' },
  KC_LCBR: { name: '`', alias: 'BR_GRV', title: '◌̀ (dead)' },
  'S(KC_RBRC)': { name: '{', alias: 'BR_LCBR', title: '{' },
  KC_RCBR: { name: '{', alias: 'BR_LCBR', title: '{' },
  // Row 3
  'S(KC_QUOT)': { name: '^', alias: 'BR_CIRC', title: '◌̂ (dead)' },
  KC_DQUO: { name: '^', alias: 'BR_CIRC', title: '◌̂ (dead)' },
  'S(KC_BSLS)': { name: '}', alias: 'BR_RCBR', title: '}' },
  KC_PIPE: { name: '}', alias: 'BR_RCBR', title: '}' },
  // Row 4
  'S(KC_NUBS)': { name: '|', alias: 'BR_PIPE', title: '|' },
  'S(KC_COMM)': { name: '<', alias: 'BR_LABK', title: '<' },
  KC_LT: { name: '<', alias: 'BR_LABK', title: '<' },
  'S(KC_DOT)': { name: '>', alias: 'BR_RABK', title: '>' },
  KC_GT: { name: '>', alias: 'BR_RABK', title: '>' },
  'S(KC_SLSH)': { name: ':', alias: 'BR_COLN', title: ':' },
  KC_QUES: { name: ':', alias: 'BR_COLN', title: ':' },
  'S(KC_INT1)': { name: '?', alias: 'BR_QUES', title: '?' },

  /* AltGr symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │   │ ¹ │ ² │ ³ │ £ │ ¢ │ ¬ │   │   │   │   │   │ § │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │   │   │ ° │   │   │   │   │   │   │   │   │ ª │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │   │   │   │   │   │   │   │   │   │   │   │ º │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴────┤
   * │    │   │   │   │ ₢ │   │   │   │   │   │   │   │   │      │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬──┴─┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  'ALGR(KC_1)': { name: '¹', alias: 'BR_SUP1', title: '¹' },
  'ALGR(KC_2)': { name: '²', alias: 'BR_SUP2', title: '²' },
  'ALGR(KC_3)': { name: '³', alias: 'BR_SUP3', title: '³' },
  'ALGR(KC_4)': { name: '£', alias: 'BR_PND', title: '£' },
  'ALGR(KC_5)': { name: '¢', alias: 'BR_CENT', title: '¢' },
  'ALGR(KC_6)': { name: '¬', alias: 'BR_NOT', title: '¬' },
  'ALGR(KC_EQL)': { name: '§', alias: 'BR_SECT', title: '§' },
  // Row 2
  'ALGR(KC_E)': { name: '°', alias: 'BR_DEG', title: '°' },
  'ALGR(KC_RBRC)': { name: 'ª', alias: 'BR_FORD', title: 'ª' },
  // Row 3
  'ALGR(KC_BSLS)': { name: 'º', alias: 'BR_MORD', title: 'º' },
  // Row 4
  'ALGR(KC_C)': { name: '₢', alias: 'BR_CRUZ', title: '₢' },

  /* Other keys */
  KC_NUHS: { name: '}\n]', title: '] and }' },
  'S(KC_NUHS)': { name: '}', title: '}' },
  KC_COLN: { name: 'Ç', alias: 'S(BR_CCED)', title: 'Ç' },

  SC_LSPO: { name: 'LS / (', title: 'Left Shift when held, ( when tapped' },
  SC_RSPC: { name: 'RS / )', title: 'Right Shift when held, ) when tapped' },
  SC_LCPO: { name: 'LC / (', title: 'Left Control when held, ( when tapped' },
  SC_RCPC: { name: 'RC / )', title: 'Right Control when held, ) when tapped' },
  SC_LAPO: { name: 'LA / (', title: 'Left Alt when held, ( when tapped' },
  SC_RAPC: { name: 'RA / )', title: 'Right Alt when held, ) when tapped' },

  QK_GESC: {
    name: '\'/"\nEsc',
    title: 'Esc normally, but \' when GUI is active or " when Shift is active'
  }
};
