/* Copyright 2022 - Generated by convert_keymap_extras_header.js
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

export default {
  /*
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬─────┐
   * │ \ │ 1 │ 2 │ 3 │ 4 │ 5 │ 6 │ 7 │ 8 │ 9 │ 0 │ ' │ ì │     │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬───┤
   * │     │ Q │ W │ E │ R │ T │ Y │ U │ I │ O │ P │ è │ + │   │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐  │
   * │      │ A │ S │ D │ F │ G │ H │ J │ K │ L │ ò │ à │ ù │  │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴──┤
   * │    │ < │ Z │ X │ C │ V │ B │ N │ M │ , │ . │ - │        │
   * ├────┴┬──┴─┬─┴───┼───┴───┴───┴───┴───┴───┼───┴─┬─┴──┬─────┤
   * │     │    │     │                       │     │    │     │
   * └─────┴────┴─────┴───────────────────────┴─────┴────┴─────┘
   */
  // Row 1
  KC_GRV: { name: '|\n\\', alias: 'IT_BSLS', title: '\\ and |' },
  KC_1: { name: '!\n1', alias: 'IT_1', title: '1 and !' },
  KC_2: { name: '"\n2', alias: 'IT_2', title: '2 and "' },
  KC_3: { name: '£\n3', alias: 'IT_3', title: '3 and £' },
  KC_4: { name: '$\n4', alias: 'IT_4', title: '4 and $' },
  KC_5: { name: '%\n5', alias: 'IT_5', title: '5 and %' },
  KC_6: { name: '&\n6', alias: 'IT_6', title: '6 and &' },
  KC_7: { name: '/\n7', alias: 'IT_7', title: '7 and /' },
  KC_8: { name: '(\n8', alias: 'IT_8', title: '8 and (' },
  KC_9: { name: ')\n9', alias: 'IT_9', title: '9 and )' },
  KC_0: { name: '=\n0', alias: 'IT_0', title: '0 and =' },
  KC_MINS: { name: "?\n'", alias: 'IT_QUOT', title: "' and ?" },
  KC_EQL: { name: '^\nì', alias: 'IT_IGRV', title: 'ì and ^' },
  // Row 2
  KC_Q: { name: 'Q', alias: 'IT_Q', title: 'q and Q' },
  KC_W: { name: 'W', alias: 'IT_W', title: 'w and W' },
  KC_E: { name: 'E', alias: 'IT_E', title: 'e and E' },
  KC_R: { name: 'R', alias: 'IT_R', title: 'r and R' },
  KC_T: { name: 'T', alias: 'IT_T', title: 't and T' },
  KC_Y: { name: 'Y', alias: 'IT_Y', title: 'y and Y' },
  KC_U: { name: 'U', alias: 'IT_U', title: 'u and U' },
  KC_I: { name: 'I', alias: 'IT_I', title: 'i and I' },
  KC_O: { name: 'O', alias: 'IT_O', title: 'o and O' },
  KC_P: { name: 'P', alias: 'IT_P', title: 'p and P' },
  KC_LBRC: { name: 'é\nè', alias: 'IT_EGRV', title: 'è and é' },
  KC_RBRC: { name: '*\n+', alias: 'IT_PLUS', title: '+ and *' },
  // Row 3
  KC_A: { name: 'A', alias: 'IT_A', title: 'a and A' },
  KC_S: { name: 'S', alias: 'IT_S', title: 's and S' },
  KC_D: { name: 'D', alias: 'IT_D', title: 'd and D' },
  KC_F: { name: 'F', alias: 'IT_F', title: 'f and F' },
  KC_G: { name: 'G', alias: 'IT_G', title: 'g and G' },
  KC_H: { name: 'H', alias: 'IT_H', title: 'h and H' },
  KC_J: { name: 'J', alias: 'IT_J', title: 'j and J' },
  KC_K: { name: 'K', alias: 'IT_K', title: 'k and K' },
  KC_L: { name: 'L', alias: 'IT_L', title: 'l and L' },
  KC_SCLN: { name: 'ç\nò', alias: 'IT_OGRV', title: 'ò and ç' },
  KC_QUOT: { name: '°\nà', alias: 'IT_AGRV', title: 'à and °' },
  KC_NUHS: { name: '§\nù', alias: 'IT_UGRV', title: 'ù and §' },
  // Row 4
  KC_NUBS: { name: '>\n<', alias: 'IT_LABK', title: '< and >' },
  KC_Z: { name: 'Z', alias: 'IT_Z', title: 'z and Z' },
  KC_X: { name: 'X', alias: 'IT_X', title: 'x and X' },
  KC_C: { name: 'C', alias: 'IT_C', title: 'c and C' },
  KC_V: { name: 'V', alias: 'IT_V', title: 'v and V' },
  KC_B: { name: 'B', alias: 'IT_B', title: 'b and B' },
  KC_N: { name: 'N', alias: 'IT_N', title: 'n and N' },
  KC_M: { name: 'M', alias: 'IT_M', title: 'm and M' },
  KC_COMM: { name: ';\n,', alias: 'IT_COMM', title: ', and ;' },
  KC_DOT: { name: ':\n.', alias: 'IT_DOT', title: '. and :' },
  KC_SLSH: { name: '_\n-', alias: 'IT_MINS', title: '- and _' },

  /* Shifted symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬─────┐
   * │ | │ ! │ " │ £ │ $ │ % │ & │ / │ ( │ ) │ = │ ? │ ^ │     │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬───┤
   * │     │   │   │   │   │   │   │   │   │   │   │ é │ * │   │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐  │
   * │      │   │   │   │   │   │   │   │   │   │ ç │ ° │ § │  │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴──┤
   * │    │ > │   │   │   │   │   │   │   │ ; │ : │ _ │        │
   * ├────┴┬──┴─┬─┴───┼───┴───┴───┴───┴───┴───┼───┴─┬─┴──┬─────┤
   * │     │    │     │                       │     │    │     │
   * └─────┴────┴─────┴───────────────────────┴─────┴────┴─────┘
   */
  // Row 1
  'S(KC_GRV)': { name: '|', alias: 'IT_PIPE', title: '|' },
  KC_TILD: { name: '|', alias: 'IT_PIPE', title: '|' },
  'S(KC_1)': { name: '!', alias: 'IT_EXLM', title: '!' },
  KC_EXLM: { name: '!', alias: 'IT_EXLM', title: '!' },
  'S(KC_2)': { name: '"', alias: 'IT_DQUO', title: '"' },
  KC_AT: { name: '"', alias: 'IT_DQUO', title: '"' },
  'S(KC_3)': { name: '£', alias: 'IT_PND', title: '£' },
  KC_HASH: { name: '£', alias: 'IT_PND', title: '£' },
  'S(KC_4)': { name: '$', alias: 'IT_DLR', title: '$' },
  KC_DLR: { name: '$', alias: 'IT_DLR', title: '$' },
  'S(KC_5)': { name: '%', alias: 'IT_PERC', title: '%' },
  KC_PERC: { name: '%', alias: 'IT_PERC', title: '%' },
  'S(KC_6)': { name: '&', alias: 'IT_AMPR', title: '&' },
  KC_CIRC: { name: '&', alias: 'IT_AMPR', title: '&' },
  'S(KC_7)': { name: '/', alias: 'IT_SLSH', title: '/' },
  KC_AMPR: { name: '/', alias: 'IT_SLSH', title: '/' },
  'S(KC_8)': { name: '(', alias: 'IT_LPRN', title: '(' },
  KC_ASTR: { name: '(', alias: 'IT_LPRN', title: '(' },
  'S(KC_9)': { name: ')', alias: 'IT_RPRN', title: ')' },
  KC_LPRN: { name: ')', alias: 'IT_RPRN', title: ')' },
  'S(KC_0)': { name: '=', alias: 'IT_EQL', title: '=' },
  KC_RPRN: { name: '=', alias: 'IT_EQL', title: '=' },
  'S(KC_MINS)': { name: '?', alias: 'IT_QUES', title: '?' },
  KC_UNDS: { name: '?', alias: 'IT_QUES', title: '?' },
  'S(KC_EQL)': { name: '^', alias: 'IT_CIRC', title: '^' },
  KC_PLUS: { name: '^', alias: 'IT_CIRC', title: '^' },
  // Row 2
  'S(KC_LBRC)': { name: 'é', alias: 'IT_EACU', title: 'é' },
  KC_LCBR: { name: 'é', alias: 'IT_EACU', title: 'é' },
  'S(KC_RBRC)': { name: '*', alias: 'IT_ASTR', title: '*' },
  KC_RCBR: { name: '*', alias: 'IT_ASTR', title: '*' },
  // Row 3
  'S(KC_SCLN)': { name: 'ç', alias: 'IT_LCCE', title: 'c' },
  KC_COLN: { name: 'ç', alias: 'IT_LCCE', title: 'c' },
  'S(KC_QUOT)': { name: '°', alias: 'IT_DEG', title: '°' },
  KC_DQUO: { name: '°', alias: 'IT_DEG', title: '°' },
  'S(KC_NUHS)': { name: '§', alias: 'IT_SECT', title: '§' },
  // Row 4
  'S(KC_NUBS)': { name: '>', alias: 'IT_RABK', title: '>' },
  'S(KC_COMM)': { name: ';', alias: 'IT_SCLN', title: ';' },
  KC_LT: { name: ';', alias: 'IT_SCLN', title: ';' },
  'S(KC_DOT)': { name: ':', alias: 'IT_COLN', title: ':' },
  KC_GT: { name: ':', alias: 'IT_COLN', title: ':' },
  'S(KC_SLSH)': { name: '_', alias: 'IT_UNDS', title: '_' },
  KC_QUES: { name: '_', alias: 'IT_UNDS', title: '_' },

  /* Alted symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬─────┐
   * │ ` │ « │ “ │ ‘ │ ¥ │ ~ │ ‹ │ ÷ │ ´ │ ` │ ≠ │ ¡ │ ˆ │     │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬───┤
   * │     │ „ │ Ω │ € │ ® │ ™ │ Æ │ ¨ │ Œ │ Ø │ π │ [ │ ] │   │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐  │
   * │      │ Å │ ß │ ∂ │ ƒ │ ∞ │ ∆ │ ª │ º │ ¬ │ @ │ # │ ¶ │  │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴──┤
   * │    │ ≤ │ ∑ │ † │ © │ √ │ ∫ │ ˜ │ µ │ … │ • │ – │        │
   * ├────┴┬──┴─┬─┴───┼───┴───┴───┴───┴───┴───┼───┴─┬─┴──┬─────┤
   * │     │    │     │                       │     │    │     │
   * └─────┴────┴─────┴───────────────────────┴─────┴────┴─────┘
   */
  // Row 1
  'A(KC_GRV)': { name: '`', alias: 'IT_GRV', title: '`' },
  'A(KC_1)': { name: '«', alias: 'IT_LDAQ', title: '«' },
  'A(KC_2)': { name: '“', alias: 'IT_LDQU', title: '“' },
  'A(KC_3)': { name: '‘', alias: 'IT_LSQU', title: '‘' },
  'A(KC_4)': { name: '¥', alias: 'IT_YEN', title: '¥' },
  'A(KC_5)': { name: '~', alias: 'IT_TILD', title: '~' },
  'A(KC_6)': { name: '‹', alias: 'IT_LSAQ', title: '‹' },
  'A(KC_7)': { name: '÷', alias: 'IT_DIV', title: '÷' },
  'A(KC_8)': { name: '´', alias: 'IT_ACUT', title: '◌́ (dead)' },
  'A(KC_9)': { name: '`', alias: 'IT_DGRV', title: '◌̀ (dead)' },
  'A(KC_0)': { name: '≠', alias: 'IT_NEQL', title: '≠' },
  'A(KC_MINS)': { name: '¡', alias: 'IT_IEXL', title: '¡' },
  'A(KC_EQL)': { name: 'ˆ', alias: 'IT_DCIR', title: '◌̂ (dead)' },
  // Row 2
  'A(KC_Q)': { name: '„', alias: 'IT_DLQU', title: '„' },
  'A(KC_W)': { name: 'Ω', alias: 'IT_OMEG', title: 'Ω' },
  'A(KC_E)': { name: '€', alias: 'IT_EURO', title: '€' },
  'A(KC_R)': { name: '®', alias: 'IT_REGD', title: '®' },
  'A(KC_T)': { name: '™', alias: 'IT_TM', title: '™' },
  'A(KC_Y)': { name: 'Æ', alias: 'IT_AE', title: 'Æ' },
  'A(KC_U)': { name: '¨', alias: 'IT_DIAE', title: '◌̈ (dead)' },
  'A(KC_I)': { name: 'Œ', alias: 'IT_OE', title: 'Œ' },
  'A(KC_O)': { name: 'Ø', alias: 'IT_OSTR', title: 'Ø' },
  'A(KC_P)': { name: 'π', alias: 'IT_PI', title: 'π' },
  'A(KC_LBRC)': { name: '[', alias: 'IT_LBRC', title: '[' },
  'A(KC_RBRC)': { name: ']', alias: 'IT_RBRC', title: ']' },
  // Row 3
  'A(KC_A)': { name: 'Å', alias: 'IT_ARNG', title: 'Å' },
  'A(KC_S)': { name: 'ß', alias: 'IT_SS', title: 'ß' },
  'A(KC_D)': { name: '∂', alias: 'IT_PDIF', title: '∂' },
  'A(KC_F)': { name: 'ƒ', alias: 'IT_FHK', title: 'ƒ' },
  'A(KC_G)': { name: '∞', alias: 'IT_INFN', title: '∞' },
  'A(KC_H)': { name: '∆', alias: 'IT_INCR', title: '∆' },
  'A(KC_J)': { name: 'ª', alias: 'IT_FORD', title: 'ª' },
  'A(KC_K)': { name: 'º', alias: 'IT_MORD', title: 'º' },
  'A(KC_L)': { name: '¬', alias: 'IT_NOT', title: '¬' },
  'A(KC_SCLN)': { name: '@', alias: 'IT_AT', title: '@' },
  'A(KC_QUOT)': { name: '#', alias: 'IT_HASH', title: '#' },
  'A(KC_NUHS)': { name: '¶', alias: 'IT_PILC', title: '¶' },
  // Row 4
  'A(KC_NUBS)': { name: '≤', alias: 'IT_LTEQ', title: '≤' },
  'A(KC_Z)': { name: '∑', alias: 'IT_NARS', title: '∑' },
  'A(KC_X)': { name: '†', alias: 'IT_DAGG', title: '†' },
  'A(KC_C)': { name: '©', alias: 'IT_COPY', title: '©' },
  'A(KC_V)': { name: '√', alias: 'IT_SQRT', title: '√' },
  'A(KC_B)': { name: '∫', alias: 'IT_INTG', title: '∫' },
  'A(KC_N)': { name: '˜', alias: 'IT_STIL', title: '˜ (dead)' },
  'A(KC_M)': { name: 'µ', alias: 'IT_MICR', title: 'µ' },
  'A(KC_COMM)': { name: '…', alias: 'IT_ELLP', title: '…' },
  'A(KC_DOT)': { name: '•', alias: 'IT_BULT', title: '•' },
  'A(KC_SLSH)': { name: '–', alias: 'IT_NDSH', title: '–' },

  /* Shift+Alted symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬─────┐
   * │ ı │ » │ ” │ ’ │ ¢ │ ‰ │ › │ ⁄ │  │   │ ≈ │ ¿ │ ± │     │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬───┤
   * │     │ ‚ │ À │ È │ Ì │ Ò │   │ Ù │   │   │ ∏ │ { │ } │   │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐  │
   * │      │   │ ¯ │ ˘ │ ˙ │ ˚ │ ¸ │ ˝ │ ˛ │ ˇ │ Ç │   │ ◊ │  │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴──┤
   * │    │ ≥ │   │ ‡ │ Á │ É │ Í │ Ó │ Ú │   │ · │ — │        │
   * ├────┴┬──┴─┬─┴───┼───┴───┴───┴───┴───┴───┼───┴─┬─┴──┬─────┤
   * │     │    │     │                       │     │    │     │
   * └─────┴────┴─────┴───────────────────────┴─────┴────┴─────┘
   */
  // Row 1
  'S(A(KC_GRV))': { name: 'ı', alias: 'IT_DLSI', title: 'ı' },
  'S(A(KC_1))': { name: '»', alias: 'IT_RDAQ', title: '»' },
  'S(A(KC_2))': { name: '”', alias: 'IT_RDQU', title: '”' },
  'S(A(KC_3))': { name: '’', alias: 'IT_RSQU', title: '’' },
  'S(A(KC_4))': { name: '¢', alias: 'IT_CENT', title: '¢' },
  'S(A(KC_5))': { name: '‰', alias: 'IT_PERM', title: '‰' },
  'S(A(KC_6))': { name: '›', alias: 'IT_RSAQ', title: '›' },
  'S(A(KC_7))': { name: '⁄', alias: 'IT_FRSL', title: '⁄' },
  'S(A(KC_8))': { name: '', alias: 'IT_APPL', title: 'Apple logo' },
  'S(A(KC_0))': { name: '≈', alias: 'IT_AEQL', title: '≈' },
  'S(A(KC_MINS))': { name: '¿', alias: 'IT_IQUE', title: '¿' },
  'S(A(KC_EQL))': { name: '±', alias: 'IT_PLMN', title: '±' },
  // Row 2
  'S(A(KC_Q))': { name: '‚', alias: 'IT_SLQU', title: '‚' },
  'S(A(KC_W))': { name: 'À', alias: 'IT_CAGR', title: 'À' },
  'S(A(KC_E))': { name: 'È', alias: 'IT_CEGR', title: 'È' },
  'S(A(KC_R))': { name: 'Ì', alias: 'IT_CIGR', title: 'Ì' },
  'S(A(KC_T))': { name: 'Ò', alias: 'IT_COGR', title: 'Ò' },
  'S(A(KC_U))': { name: 'Ù', alias: 'IT_CUGR', title: 'Ù' },
  'S(A(KC_P))': { name: '∏', alias: 'IT_NARP', title: '∏' },
  'S(A(KC_LBRC))': { name: '{', alias: 'IT_LCBR', title: '{' },
  'S(A(KC_RBRC))': { name: '}', alias: 'IT_RCBR', title: '}' },
  // Row 3
  'S(A(KC_S))': { name: '¯', alias: 'IT_MACR', title: '¯' },
  'S(A(KC_D))': { name: '˘', alias: 'IT_BREV', title: '˘' },
  'S(A(KC_F))': { name: '˙', alias: 'IT_DOTA', title: '˙' },
  'S(A(KC_G))': { name: '˚', alias: 'IT_RNGA', title: '˚' },
  'S(A(KC_H))': { name: '¸', alias: 'IT_CEDL', title: '¸' },
  'S(A(KC_J))': { name: '˝', alias: 'IT_DACU', title: '˝' },
  'S(A(KC_K))': { name: '˛', alias: 'IT_OGON', title: '˛' },
  'S(A(KC_L))': { name: 'ˇ', alias: 'IT_CARN', title: 'ˇ' },
  'S(A(KC_SCLN))': { name: 'Ç', alias: 'IT_CCCE', title: 'Ç' },
  'S(A(KC_NUHS))': { name: '◊', alias: 'IT_LOZN', title: '◊' },
  // Row 4
  'S(A(KC_NUBS))': { name: '≥', alias: 'IT_GTEQ', title: '≥' },
  'S(A(KC_X))': { name: '‡', alias: 'IT_DDAG', title: '‡' },
  'S(A(KC_C))': { name: 'Á', alias: 'IT_CAAC', title: 'Á' },
  'S(A(KC_V))': { name: 'É', alias: 'IT_CEAC', title: 'É' },
  'S(A(KC_B))': { name: 'Í', alias: 'IT_CIAC', title: 'Í' },
  'S(A(KC_N))': { name: 'Ó', alias: 'IT_COAC', title: 'Ó' },
  'S(A(KC_M))': { name: 'Ú', alias: 'IT_CUAC', title: 'Ú' },
  'S(A(KC_DOT))': { name: '·', alias: 'IT_MDDT', title: '·' },
  'S(A(KC_SLSH))': { name: '—', alias: 'IT_MDSH', title: '—' },

  /* Other keys */
  KC_BSLS: { name: '§\nù', title: 'ù and §' },
  'S(KC_BSLS)': { name: '§', title: '§' },
  KC_PIPE: { name: '§', alias: 'IT_SECT', title: '§' },

  SC_LSPO: { name: 'LS / )', title: 'Left Shift when held, ) when tapped' },
  SC_RSPC: { name: 'RS / =', title: 'Right Shift when held, = when tapped' },
  SC_LCPO: { name: 'LC / )', title: 'Left Control when held, ) when tapped' },
  SC_RCPC: { name: 'RC / =', title: 'Right Control when held, = when tapped' },
  SC_LAPO: { name: 'LA / )', title: 'Left Alt when held, ) when tapped' },
  SC_RAPC: { name: 'RA / =', title: 'Right Alt when held, = when tapped' },

  QK_GESC: {
    name: '\\/|\nEsc',
    title: 'Esc normally, but \\ when GUI is active or | when Shift is active'
  }
};
