/* Copyright 2022 - Generated by convert_keymap_extras_header.js
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

export default {
  /*
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ ' │ 1 │ 2 │ 3 │ 4 │ 5 │ 6 │ 7 │ 8 │ 9 │ 0 │ - │ = │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │ Й │ Ц │ У │ К │ Е │ Н │ Г │ Ш │ Щ │ З │ Х │ Ї │  \  │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴─────┤
   * │      │ Ф │ І │ В │ А │ П │ Р │ О │ Л │ Д │ Ж │ Є │        │
   * ├──────┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴────────┤
   * │        │ Я │ Ч │ С │ М │ И │ Т │ Ь │ Б │ Ю │ . │          │
   * ├────┬───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  KC_GRV: { name: "₴\n'", alias: 'UA_QUOT', title: "' and ₴" },
  KC_1: { name: '!\n1', alias: 'UA_1', title: '1 and !' },
  KC_2: { name: '"\n2', alias: 'UA_2', title: '2 and "' },
  KC_3: { name: '№\n3', alias: 'UA_3', title: '3 and №' },
  KC_4: { name: ';\n4', alias: 'UA_4', title: '4 and ;' },
  KC_5: { name: '%\n5', alias: 'UA_5', title: '5 and %' },
  KC_6: { name: ':\n6', alias: 'UA_6', title: '6 and :' },
  KC_7: { name: '?\n7', alias: 'UA_7', title: '7 and ?' },
  KC_8: { name: '*\n8', alias: 'UA_8', title: '8 and *' },
  KC_9: { name: '(\n9', alias: 'UA_9', title: '9 and (' },
  KC_0: { name: ')\n0', alias: 'UA_0', title: '0 and )' },
  KC_MINS: { name: '_\n-', alias: 'UA_MINS', title: '- and _' },
  KC_EQL: { name: '+\n=', alias: 'UA_EQL', title: '= and +' },
  // Row 2
  KC_Q: { name: 'Й', alias: 'UA_YOT', title: 'й and Й' },
  KC_W: { name: 'Ц', alias: 'UA_TSE', title: 'ц and Ц' },
  KC_E: { name: 'У', alias: 'UA_U', title: 'у and У' },
  KC_R: { name: 'К', alias: 'UA_KA', title: 'к and К' },
  KC_T: { name: 'Е', alias: 'UA_E', title: 'е and Е' },
  KC_Y: { name: 'Н', alias: 'UA_EN', title: 'н and Н' },
  KC_U: { name: 'Г', alias: 'UA_HE', title: 'г and Г' },
  KC_I: { name: 'Ш', alias: 'UA_SHA', title: 'ш and Ш' },
  KC_O: { name: 'Щ', alias: 'UA_SHCH', title: 'щ and Щ' },
  KC_P: { name: 'З', alias: 'UA_ZE', title: 'з and З' },
  KC_LBRC: { name: 'Х', alias: 'UA_KHA', title: 'х and Х' },
  KC_RBRC: { name: 'Ї', alias: 'UA_YI', title: 'ї and Ї' },
  KC_BSLS: { name: '/\n\\', alias: 'UA_BSLS', title: '\\ and /' },
  // Row 3
  KC_A: { name: 'Ф', alias: 'UA_EF', title: 'ф and Ф' },
  KC_S: { name: 'І', alias: 'UA_I', title: 'і and І' },
  KC_D: { name: 'В', alias: 'UA_VE', title: 'в and В' },
  KC_F: { name: 'А', alias: 'UA_A', title: 'а and А' },
  KC_G: { name: 'П', alias: 'UA_PE', title: 'п and П' },
  KC_H: { name: 'Р', alias: 'UA_ER', title: 'р and Р' },
  KC_J: { name: 'О', alias: 'UA_O', title: 'о and О' },
  KC_K: { name: 'Л', alias: 'UA_EL', title: 'л and Л' },
  KC_L: { name: 'Д', alias: 'UA_DE', title: 'д and Д' },
  KC_SCLN: { name: 'Ж', alias: 'UA_ZHE', title: 'ж and Ж' },
  KC_QUOT: { name: 'Є', alias: 'UA_YE', title: 'є and Є' },
  // Row 4
  KC_Z: { name: 'Я', alias: 'UA_YA', title: 'я and Я' },
  KC_X: { name: 'Ч', alias: 'UA_CHE', title: 'ч and Ч' },
  KC_C: { name: 'С', alias: 'UA_ES', title: 'с and С' },
  KC_V: { name: 'М', alias: 'UA_EM', title: 'м and М' },
  KC_B: { name: 'И', alias: 'UA_Y', title: 'и and И' },
  KC_N: { name: 'Т', alias: 'UA_TE', title: 'т and Т' },
  KC_M: { name: 'Ь', alias: 'UA_SOFT', title: 'ь and Ь' },
  KC_COMM: { name: 'Б', alias: 'UA_BE', title: 'б and Б' },
  KC_DOT: { name: 'Ю', alias: 'UA_YU', title: 'ю and Ю' },
  KC_SLSH: { name: ',\n.', alias: 'UA_DOT', title: '. and ,' },

  /* Shifted symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ ₴ │ ! │ " │ № │ ; │ % │ : │ ? │ * │ ( │ ) │ _ │ + │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │   │   │   │   │   │   │   │   │   │   │   │   │  /  │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴─────┤
   * │      │   │   │   │   │   │   │   │   │   │   │   │        │
   * ├──────┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴────────┤
   * │        │   │   │   │   │   │   │   │   │   │ , │          │
   * ├────┬───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  'S(KC_GRV)': { name: '₴', alias: 'UA_HRYV', title: '₴' },
  KC_TILD: { name: '₴', alias: 'UA_HRYV', title: '₴' },
  'S(KC_1)': { name: '!', alias: 'UA_EXLM', title: '!' },
  KC_EXLM: { name: '!', alias: 'UA_EXLM', title: '!' },
  'S(KC_2)': { name: '"', alias: 'UA_DQUO', title: '"' },
  KC_AT: { name: '"', alias: 'UA_DQUO', title: '"' },
  'S(KC_3)': { name: '№', alias: 'UA_NUM', title: '№' },
  KC_HASH: { name: '№', alias: 'UA_NUM', title: '№' },
  'S(KC_4)': { name: ';', alias: 'UA_SCLN', title: ';' },
  KC_DLR: { name: ';', alias: 'UA_SCLN', title: ';' },
  'S(KC_5)': { name: '%', alias: 'UA_PERC', title: '%' },
  KC_PERC: { name: '%', alias: 'UA_PERC', title: '%' },
  'S(KC_6)': { name: ':', alias: 'UA_COLN', title: ':' },
  KC_CIRC: { name: ':', alias: 'UA_COLN', title: ':' },
  'S(KC_7)': { name: '?', alias: 'UA_QUES', title: '?' },
  KC_AMPR: { name: '?', alias: 'UA_QUES', title: '?' },
  'S(KC_8)': { name: '*', alias: 'UA_ASTR', title: '*' },
  KC_ASTR: { name: '*', alias: 'UA_ASTR', title: '*' },
  'S(KC_9)': { name: '(', alias: 'UA_LPRN', title: '(' },
  KC_LPRN: { name: '(', alias: 'UA_LPRN', title: '(' },
  'S(KC_0)': { name: ')', alias: 'UA_RPRN', title: ')' },
  KC_RPRN: { name: ')', alias: 'UA_RPRN', title: ')' },
  'S(KC_MINS)': { name: '_', alias: 'UA_UNDS', title: '_' },
  KC_UNDS: { name: '_', alias: 'UA_UNDS', title: '_' },
  'S(KC_EQL)': { name: '+', alias: 'UA_PLUS', title: '+' },
  KC_PLUS: { name: '+', alias: 'UA_PLUS', title: '+' },
  // Row 2
  'S(KC_BSLS)': { name: '/', alias: 'UA_SLSH', title: '/' },
  KC_PIPE: { name: '/', alias: 'UA_SLSH', title: '/' },
  // Row 4
  'S(KC_SLSH)': { name: ',', alias: 'UA_COMM', title: ',' },
  KC_QUES: { name: ',', alias: 'UA_COMM', title: ',' },

  /* AltGr symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │   │   │   │   │   │   │   │   │   │   │   │   │   │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │   │   │   │   │   │   │ ґ │   │   │   │   │   │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴─────┤
   * │      │   │   │   │   │   │   │   │   │   │   │   │        │
   * ├──────┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴────────┤
   * │        │   │   │   │   │   │   │   │   │   │   │          │
   * ├────┬───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 2
  'ALGR(KC_U)': { name: 'ґ', alias: 'UA_GE', title: 'ґ' },

  /* Other keys */
  KC_NUHS: { name: '/\n\\', title: '\\ and /' },
  'S(KC_NUHS)': { name: '/', title: '/' },
  KC_NUBS: { name: '/\n\\', title: '\\ and /' },
  'S(KC_NUBS)': { name: '/', title: '/' },
  KC_LCBR: { name: 'Х', alias: 'S(UA_KHA)', title: 'Х' },
  KC_RCBR: { name: 'Ї', alias: 'S(UA_YI)', title: 'Ї' },
  KC_LT: { name: 'Б', alias: 'S(UA_BE)', title: 'Б' },
  KC_GT: { name: 'Ю', alias: 'S(UA_YU)', title: 'Ю' },
  KC_COLN: { name: 'Ж', alias: 'S(UA_ZHE)', title: 'Ж' },
  KC_DQUO: { name: 'Є', alias: 'S(UA_YE)', title: 'Є' },

  SC_LSPO: { name: 'LS / (', title: 'Left Shift when held, ( when tapped' },
  SC_RSPC: { name: 'RS / )', title: 'Right Shift when held, ) when tapped' },
  SC_LCPO: { name: 'LC / (', title: 'Left Control when held, ( when tapped' },
  SC_RCPC: { name: 'RC / )', title: 'Right Control when held, ) when tapped' },
  SC_LAPO: { name: 'LA / (', title: 'Left Alt when held, ( when tapped' },
  SC_RAPC: { name: 'RA / )', title: 'Right Alt when held, ) when tapped' },

  QK_GESC: {
    name: "' / ₴\nEsc",
    title: "Esc normally, but ' when GUI is active or ₴ when Shift is active"
  }
};
