/* Copyright 2022 - Generated by convert_keymap_extras_header.js
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

export default {
  /*
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬─────┐
   * │ @ │ & │ é │ " │ ' │ ( │ § │ è │ ! │ ç │ à │ ) │ - │     │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬───┤
   * │     │ A │ Z │ E │ R │ T │ Y │ U │ I │ O │ P │ ^ │ $ │   │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐  │
   * │      │ Q │ S │ D │ F │ G │ H │ J │ K │ L │ M │ ù │ ` │  │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴──┤
   * │    │ < │ W │ X │ C │ V │ B │ N │ , │ ; │ : │ = │        │
   * ├────┴┬──┴─┬─┴───┼───┴───┴───┴───┴───┴───┼───┴─┬─┴──┬─────┤
   * │     │    │     │                       │     │    │     │
   * └─────┴────┴─────┴───────────────────────┴─────┴────┴─────┘
   */
  // Row 11
  KC_GRV: { name: '#\n@', alias: 'FR_AT', title: '@ and #' },
  KC_1: { name: '1\n&', alias: 'FR_AMPR', title: '& and 1' },
  KC_2: { name: '2\né', alias: 'FR_LEAC', title: 'é and 2' },
  KC_3: { name: '3\n"', alias: 'FR_DQUO', title: '" and 3' },
  KC_4: { name: "4\n'", alias: 'FR_QUOT', title: "' and 4" },
  KC_5: { name: '5\n(', alias: 'FR_LPRN', title: '( and 5' },
  KC_6: { name: '6\n§', alias: 'FR_SECT', title: '§ and 6' },
  KC_7: { name: '7\nè', alias: 'FR_LEGR', title: 'è and 7' },
  KC_8: { name: '8\n!', alias: 'FR_EXLM', title: '! and 8' },
  KC_9: { name: '9\nç', alias: 'FR_LCCE', title: 'ç and 9' },
  KC_0: { name: '0\nà', alias: 'FR_LAGR', title: 'à and 0' },
  KC_MINS: { name: '°\n)', alias: 'FR_RPRN', title: ') and °' },
  KC_EQL: { name: '_\n-', alias: 'FR_MINS', title: '- and _' },
  // Row 2
  KC_Q: { name: 'A', alias: 'FR_A', title: 'a and A' },
  KC_W: { name: 'Z', alias: 'FR_Z', title: 'z and Z' },
  KC_E: { name: 'E', alias: 'FR_E', title: 'e and E' },
  KC_R: { name: 'R', alias: 'FR_R', title: 'r and R' },
  KC_T: { name: 'T', alias: 'FR_T', title: 't and T' },
  KC_Y: { name: 'Y', alias: 'FR_Y', title: 'y and Y' },
  KC_U: { name: 'U', alias: 'FR_U', title: 'u and U' },
  KC_I: { name: 'I', alias: 'FR_I', title: 'i and I' },
  KC_O: { name: 'O', alias: 'FR_O', title: 'o and O' },
  KC_P: { name: 'P', alias: 'FR_P', title: 'p and P' },
  KC_LBRC: { name: '¨\n^', alias: 'FR_CIRC', title: '^ and ¨' },
  KC_RBRC: { name: '*\n$', alias: 'FR_DLR', title: '$ and *' },
  // Row 3
  KC_A: { name: 'Q', alias: 'FR_Q', title: 'q and Q' },
  KC_S: { name: 'S', alias: 'FR_S', title: 's and S' },
  KC_D: { name: 'D', alias: 'FR_D', title: 'd and D' },
  KC_F: { name: 'F', alias: 'FR_F', title: 'f and F' },
  KC_G: { name: 'G', alias: 'FR_G', title: 'g and G' },
  KC_H: { name: 'H', alias: 'FR_H', title: 'h and H' },
  KC_J: { name: 'J', alias: 'FR_J', title: 'j and J' },
  KC_K: { name: 'K', alias: 'FR_K', title: 'k and K' },
  KC_L: { name: 'L', alias: 'FR_L', title: 'l and L' },
  KC_SCLN: { name: 'M', alias: 'FR_M', title: 'm and M' },
  KC_QUOT: { name: '%\nù', alias: 'FR_LUGR', title: 'ù and %' },
  KC_NUHS: { name: '£\n`', alias: 'FR_GRV', title: '` and £' },
  // Row 4
  KC_NUBS: { name: '>\n<', alias: 'FR_LABK', title: '< and >' },
  KC_Z: { name: 'W', alias: 'FR_W', title: 'w and W' },
  KC_X: { name: 'X', alias: 'FR_X', title: 'x and X' },
  KC_C: { name: 'C', alias: 'FR_C', title: 'c and C' },
  KC_V: { name: 'V', alias: 'FR_V', title: 'v and V' },
  KC_B: { name: 'B', alias: 'FR_B', title: 'b and B' },
  KC_N: { name: 'N', alias: 'FR_N', title: 'n and N' },
  KC_M: { name: '?\n,', alias: 'FR_COMM', title: ', and ?' },
  KC_COMM: { name: '.\n;', alias: 'FR_SCLN', title: '; and .' },
  KC_DOT: { name: '/\n:', alias: 'FR_COLN', title: ': and /' },
  KC_SLSH: { name: '+\n=', alias: 'FR_EQL', title: '= and +' },

  /* Shifted symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬─────┐
   * │ # │ 1 │ 2 │ 3 │ 4 │ 5 │ 6 │ 7 │ 8 │ 9 │ 0 │ ° │ _ │     │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬───┤
   * │     │   │   │   │   │   │   │   │   │   │   │ ¨ │ * │   │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐  │
   * │      │   │   │   │   │   │   │   │   │   │   │ % │ £ │  │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴──┤
   * │    │ > │   │   │   │   │   │   │ ? │ . │ / │ + │        │
   * ├────┴┬──┴─┬─┴───┼───┴───┴───┴───┴───┴───┼───┴─┬─┴──┬─────┤
   * │     │    │     │                       │     │    │     │
   * └─────┴────┴─────┴───────────────────────┴─────┴────┴─────┘
   */
  // Row 1
  'S(KC_GRV)': { name: '#', alias: 'FR_HASH', title: '#' },
  KC_TILD: { name: '#', alias: 'FR_HASH', title: '#' },
  'S(KC_1)': { name: '1', alias: 'FR_1', title: '1' },
  KC_EXLM: { name: '1', alias: 'FR_1', title: '1' },
  'S(KC_2)': { name: '2', alias: 'FR_2', title: '2' },
  KC_AT: { name: '2', alias: 'FR_2', title: '2' },
  'S(KC_3)': { name: '3', alias: 'FR_3', title: '3' },
  KC_HASH: { name: '3', alias: 'FR_3', title: '3' },
  'S(KC_4)': { name: '4', alias: 'FR_4', title: '4' },
  KC_DLR: { name: '4', alias: 'FR_4', title: '4' },
  'S(KC_5)': { name: '5', alias: 'FR_5', title: '5' },
  KC_PERC: { name: '5', alias: 'FR_5', title: '5' },
  'S(KC_6)': { name: '6', alias: 'FR_6', title: '6' },
  KC_CIRC: { name: '6', alias: 'FR_6', title: '6' },
  'S(KC_7)': { name: '7', alias: 'FR_7', title: '7' },
  KC_AMPR: { name: '7', alias: 'FR_7', title: '7' },
  'S(KC_8)': { name: '8', alias: 'FR_8', title: '8' },
  KC_ASTR: { name: '8', alias: 'FR_8', title: '8' },
  'S(KC_9)': { name: '9', alias: 'FR_9', title: '9' },
  KC_LPRN: { name: '9', alias: 'FR_9', title: '9' },
  'S(KC_0)': { name: '0', alias: 'FR_0', title: '0' },
  KC_RPRN: { name: '0', alias: 'FR_0', title: '0' },
  'S(KC_MINS)': { name: '°', alias: 'FR_DEG', title: '°' },
  KC_UNDS: { name: '°', alias: 'FR_DEG', title: '°' },
  'S(KC_EQL)': { name: '_', alias: 'FR_UNDS', title: '_' },
  KC_PLUS: { name: '_', alias: 'FR_UNDS', title: '_' },
  // Row 2
  'S(KC_LBRC)': { name: '¨', alias: 'FR_DIAE', title: '◌̈ (dead)' },
  KC_LCBR: { name: '¨', alias: 'FR_DIAE', title: '◌̈ (dead)' },
  'S(KC_RBRC)': { name: '*', alias: 'FR_ASTR', title: '*' },
  KC_RCBR: { name: '*', alias: 'FR_ASTR', title: '*' },
  // Row 3
  'S(KC_QUOT)': { name: '%', alias: 'FR_PERC', title: '%' },
  KC_DQUO: { name: '%', alias: 'FR_PERC', title: '%' },
  'S(KC_NUHS)': { name: '£', alias: 'FR_PND', title: '£' },
  // Row 4
  'S(KC_NUBS)': { name: '>', alias: 'FR_RABK', title: '>' },
  'S(KC_M)': { name: '?', alias: 'FR_QUES', title: '?' },
  'S(KC_COMM)': { name: '.', alias: 'FR_DOT', title: '.' },
  KC_LT: { name: '.', alias: 'FR_DOT', title: '.' },
  'S(KC_DOT)': { name: '/', alias: 'FR_SLSH', title: '/' },
  KC_GT: { name: '/', alias: 'FR_SLSH', title: '/' },
  'S(KC_SLSH)': { name: '+', alias: 'FR_PLUS', title: '+' },
  KC_QUES: { name: '+', alias: 'FR_PLUS', title: '+' },

  /* Alted symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬─────┐
   * │ • │  │ ë │ “ │ ‘ │ { │ ¶ │ « │ ¡ │ Ç │ Ø │ } │ — │     │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬───┤
   * │     │ Æ │ Â │ Ê │ ® │ † │ Ú │ º │ î │ Œ │ π │ Ô │ € │   │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐  │
   * │      │ ‡ │ Ò │ ∂ │ ƒ │ ﬁ │ Ì │ Ï │ È │ ¬ │ µ │ Ù │   │  │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴──┤
   * │    │ ≤ │ ‹ │ ≈ │ © │ ◊ │ ß │ ~ │ ∞ │ … │ ÷ │ ≠ │        │
   * ├────┴┬──┴─┬─┴───┼───┴───┴───┴───┴───┴───┼───┴─┬─┴──┬─────┤
   * │     │    │     │                       │     │    │     │
   * └─────┴────┴─────┴───────────────────────┴─────┴────┴─────┘
   */
  // Row 1
  'A(KC_GRV)': { name: '•', alias: 'FR_BULT', title: '•' },
  'A(KC_1)': { name: '', alias: 'FR_APPL', title: 'Apple logo' },
  'A(KC_2)': { name: 'ë', alias: 'FR_LEDI', title: 'ë' },
  'A(KC_3)': { name: '“', alias: 'FR_LDQU', title: '“' },
  'A(KC_4)': { name: '‘', alias: 'FR_LSQU', title: '‘' },
  'A(KC_5)': { name: '{', alias: 'FR_LCBR', title: '{' },
  'A(KC_6)': { name: '¶', alias: 'FR_PILC', title: '¶' },
  'A(KC_7)': { name: '«', alias: 'FR_LDAQ', title: '«' },
  'A(KC_8)': { name: '¡', alias: 'FR_IEXL', title: '¡' },
  'A(KC_9)': { name: 'Ç', alias: 'FR_CCCE', title: 'Ç' },
  'A(KC_0)': { name: 'Ø', alias: 'FR_OSTR', title: 'Ø' },
  'A(KC_MINS)': { name: '}', alias: 'FR_RCBR', title: '}' },
  'A(KC_EQL)': { name: '—', alias: 'FR_MDSH', title: '—' },
  // Row 2
  'A(KC_Q)': { name: 'Æ', alias: 'FR_AE', title: 'Æ' },
  'A(KC_W)': { name: 'Â', alias: 'FR_CACI', title: 'Â' },
  'A(KC_E)': { name: 'Ê', alias: 'FR_ECIR', title: 'Ê' },
  'A(KC_R)': { name: '®', alias: 'FR_REGD', title: '®' },
  'A(KC_T)': { name: '†', alias: 'FR_DAGG', title: '†' },
  'A(KC_Y)': { name: 'Ú', alias: 'FR_CUAC', title: 'Ú' },
  'A(KC_U)': { name: 'º', alias: 'FR_MORD', title: 'º' },
  'A(KC_I)': { name: 'î', alias: 'FR_LICI', title: 'î' },
  'A(KC_O)': { name: 'Œ', alias: 'FR_OE', title: 'Œ' },
  'A(KC_P)': { name: 'π', alias: 'FR_PI', title: 'π' },
  'A(KC_LBRC)': { name: 'Ô', alias: 'FR_OCIR', title: 'Ô' },
  'A(KC_RBRC)': { name: '€', alias: 'FR_EURO', title: '€' },
  // Row 3
  'A(KC_A)': { name: '‡', alias: 'FR_DDAG', title: '‡' },
  'A(KC_S)': { name: 'Ò', alias: 'FR_COGR', title: 'Ò' },
  'A(KC_D)': { name: '∂', alias: 'FR_PDIF', title: '∂' },
  'A(KC_F)': { name: 'ƒ', alias: 'FR_FHK', title: 'ƒ' },
  'A(KC_G)': { name: 'ﬁ', alias: 'FR_FI', title: 'ﬁ' },
  'A(KC_H)': { name: 'Ì', alias: 'FR_CIGR', title: 'Ì' },
  'A(KC_J)': { name: 'Ï', alias: 'FR_CIDI', title: 'Ï' },
  'A(KC_K)': { name: 'È', alias: 'FR_CEGR', title: 'È' },
  'A(KC_L)': { name: '¬', alias: 'FR_NOT', title: '¬' },
  'A(KC_SCLN)': { name: 'µ', alias: 'FR_MICR', title: 'µ' },
  'A(KC_QUOT)': { name: 'Ù', alias: 'FR_CUGR', title: 'Ù' },
  // Row 4
  'A(KC_NUBS)': { name: '≤', alias: 'FR_LTEQ', title: '≤' },
  'A(KC_Z)': { name: '‹', alias: 'FR_LSAQ', title: '‹' },
  'A(KC_X)': { name: '≈', alias: 'FR_AEQL', title: '≈' },
  'A(KC_C)': { name: '©', alias: 'FR_COPY', title: '©' },
  'A(KC_V)': { name: '◊', alias: 'FR_LOZN', title: '◊' },
  'A(KC_B)': { name: 'ß', alias: 'FR_SS', title: 'ß' },
  'A(KC_N)': { name: '~', alias: 'FR_TILD', title: '◌̃ (dead)' },
  'A(KC_M)': { name: '∞', alias: 'FR_INFN', title: '∞' },
  'A(KC_COMM)': { name: '…', alias: 'FR_ELLP', title: '…' },
  'A(KC_DOT)': { name: '÷', alias: 'FR_DIV', title: '÷' },
  'A(KC_SLSH)': { name: '≠', alias: 'FR_NEQL', title: '≠' },

  /* Shift+Alted symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬─────┐
   * │ Ÿ │ ´ │ „ │   │   │ [ │ å │ » │ Û │ Á │   │ ] │ – │     │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬───┤
   * │     │   │ Å │   │ ‚ │ ™ │   │ ª │ ï │   │ ∏ │   │ ¥ │   │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐  │
   * │      │ Ω │ ∑ │ ∆ │ · │ ﬂ │ Î │ Í │ Ë │ | │ Ó │ ‰ │   │  │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴──┤
   * │    │ ≥ │ › │ ⁄ │ ¢ │ √ │ ∫ │ ı │ ¿ │   │ \ │ ± │        │
   * ├────┴┬──┴─┬─┴───┼───┴───┴───┴───┴───┴───┼───┴─┬─┴──┬─────┤
   * │     │    │     │                       │     │    │     │
   * └─────┴────┴─────┴───────────────────────┴─────┴────┴─────┘
   */
  // Row 1
  'S(A(KC_GRV))': { name: 'Ÿ', alias: 'FR_CYDI', title: 'Ÿ' },
  'S(A(KC_1))': { name: '´', alias: 'FR_ACUT', title: '◌́ (dead)' },
  'S(A(KC_2))': { name: '„', alias: 'FR_DLQU', title: '„' },
  'S(A(KC_5))': { name: '[', alias: 'FR_LBRC', title: '[' },
  'S(A(KC_6))': { name: 'å', alias: 'FR_LARI', title: 'å' },
  'S(A(KC_7))': { name: '»', alias: 'FR_RDAQ', title: '»' },
  'S(A(KC_8))': { name: 'Û', alias: 'FR_CUCI', title: 'Û' },
  'S(A(KC_9))': { name: 'Á', alias: 'FR_CAAC', title: 'Á' },
  'S(A(KC_MINS))': { name: ']', alias: 'FR_RBRC', title: ']' },
  'S(A(KC_EQL))': { name: '–', alias: 'FR_NDSH', title: '–' },
  // Row 2
  'S(A(KC_W))': { name: 'Å', alias: 'FR_CARI', title: 'Å' },
  'S(A(KC_R))': { name: '‚', alias: 'FR_SLQU', title: '‚' },
  'S(A(KC_T))': { name: '™', alias: 'FR_TM', title: '™' },
  'S(A(KC_U))': { name: 'ª', alias: 'FR_FORD', title: 'ª' },
  'S(A(KC_I))': { name: 'ï', alias: 'FR_LIDI', title: 'ï' },
  'S(A(KC_P))': { name: '∏', alias: 'FR_NARP', title: '∏' },
  'S(A(KC_RBRC))': { name: '¥', alias: 'FR_YEN', title: '¥' },
  // Row 3
  'S(A(KC_A))': { name: 'Ω', alias: 'FR_OMEG', title: 'Ω' },
  'S(A(KC_S))': { name: '∑', alias: 'FR_NARS', title: '∑' },
  'S(A(KC_D))': { name: '∆', alias: 'FR_INCR', title: '∆' },
  'S(A(KC_F))': { name: '·', alias: 'FR_MDDT', title: '·' },
  'S(A(KC_G))': { name: 'ﬂ', alias: 'FR_FL', title: 'ﬂ' },
  'S(A(KC_H))': { name: 'Î', alias: 'FR_CICI', title: 'Î' },
  'S(A(KC_J))': { name: 'Í', alias: 'FR_CIAC', title: 'Í' },
  'S(A(KC_K))': { name: 'Ë', alias: 'FR_CEDI', title: 'Ë' },
  'S(A(KC_L))': { name: '|', alias: 'FR_PIPE', title: '|' },
  'S(A(KC_SCLN))': { name: 'Ó', alias: 'FR_COAC', title: 'Ó' },
  'S(A(KC_QUOT))': { name: '‰', alias: 'FR_PERM', title: '‰' },
  // Row 4
  'S(A(KC_NUBS))': { name: '≥', alias: 'FR_GTEQ', title: '≥' },
  'S(A(KC_Z))': { name: '›', alias: 'FR_RSAQ', title: '›' },
  'S(A(KC_X))': { name: '⁄', alias: 'FR_FRSL', title: '⁄' },
  'S(A(KC_C))': { name: '¢', alias: 'FR_CENT', title: '¢' },
  'S(A(KC_V))': { name: '√', alias: 'FR_SQRT', title: '√' },
  'S(A(KC_B))': { name: '∫', alias: 'FR_INTG', title: '∫' },
  'S(A(KC_N))': { name: 'ı', alias: 'FR_DLSI', title: 'ı' },
  'S(A(KC_M))': { name: '¿', alias: 'FR_IQUE', title: '¿' },
  'S(A(KC_DOT))': { name: '\\', alias: 'FR_BSLS', title: '\\' },
  'S(A(KC_SLSH))': { name: '±', alias: 'FR_PLMN', title: '±' },

  /* Other keys */
  KC_BSLS: { name: '£\n`', title: '` and £' },
  'S(KC_BSLS)': { name: '£', title: '£' },
  KC_COLN: { name: 'M', alias: 'S(FR_M)', title: 'M' },
  KC_PIPE: { name: '£', alias: 'FR_PND', title: '£' },

  SC_LSPO: { name: 'LS / 9', title: 'Left Shift when held, 9 when tapped' },
  SC_RSPC: { name: 'RS / 0', title: 'Right Shift when held, 0 when tapped' },
  SC_LCPO: { name: 'LC / 9', title: 'Left Control when held, 9 when tapped' },
  SC_RCPC: { name: 'RC / 0', title: 'Right Control when held, 0 when tapped' },
  SC_LAPO: { name: 'LA / 9', title: 'Left Alt when held, 9 when tapped' },
  SC_RAPC: { name: 'RA / 0', title: 'Right Alt when held, 0 when tapped' },

  QK_GESC: {
    name: '@/#\nEsc',
    title: 'Esc normally, but @ when GUI is active or # when Shift is active'
  }
};
