/* Copyright 2022 - Generated by convert_keymap_extras_header.js
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

export default {
  /*
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ ¸ │ 1 │ 2 │ 3 │ 4 │ 5 │ 6 │ 7 │ 8 │ 9 │ 0 │ ' │ + │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │ Q │ W │ E │ R │ T │ Z │ U │ I │ O │ P │ Š │ Đ │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │ A │ S │ D │ F │ G │ H │ J │ K │ L │ Č │ Ć │ Ž │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │ < │ Y │ X │ C │ V │ B │ N │ M │ , │ . │ - │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  KC_GRV: { name: '¨\n¸', alias: 'SI_CEDL', title: '◌̧ (dead) and ◌̈ (dead)' },
  KC_1: { name: '!\n1', alias: 'SI_1', title: '1 and !' },
  KC_2: { name: '"\n2', alias: 'SI_2', title: '2 and "' },
  KC_3: { name: '#\n3', alias: 'SI_3', title: '3 and #' },
  KC_4: { name: '$\n4', alias: 'SI_4', title: '4 and $' },
  KC_5: { name: '%\n5', alias: 'SI_5', title: '5 and %' },
  KC_6: { name: '&\n6', alias: 'SI_6', title: '6 and &' },
  KC_7: { name: '/\n7', alias: 'SI_7', title: '7 and /' },
  KC_8: { name: '(\n8', alias: 'SI_8', title: '8 and (' },
  KC_9: { name: ')\n9', alias: 'SI_9', title: '9 and )' },
  KC_0: { name: '=\n0', alias: 'SI_0', title: '0 and =' },
  KC_MINS: { name: "?\n'", alias: 'SI_QUOT', title: "' and ?" },
  KC_EQL: { name: '*\n+', alias: 'SI_PLUS', title: '+ and *' },
  // Row 2
  KC_Q: { name: 'Q', alias: 'SI_Q', title: 'q and Q' },
  KC_W: { name: 'W', alias: 'SI_W', title: 'w and W' },
  KC_E: { name: 'E', alias: 'SI_E', title: 'e and E' },
  KC_R: { name: 'R', alias: 'SI_R', title: 'r and R' },
  KC_T: { name: 'T', alias: 'SI_T', title: 't and T' },
  KC_Y: { name: 'Z', alias: 'SI_Z', title: 'z and Z' },
  KC_U: { name: 'U', alias: 'SI_U', title: 'u and U' },
  KC_I: { name: 'I', alias: 'SI_I', title: 'i and I' },
  KC_O: { name: 'O', alias: 'SI_O', title: 'o and O' },
  KC_P: { name: 'P', alias: 'SI_P', title: 'p and P' },
  KC_LBRC: { name: 'Š', alias: 'SI_SCAR', title: 'š and Š' },
  KC_RBRC: { name: 'Đ', alias: 'SI_DSTR', title: 'đ and Đ' },
  // Row 3
  KC_A: { name: 'A', alias: 'SI_A', title: 'a and A' },
  KC_S: { name: 'S', alias: 'SI_S', title: 's and S' },
  KC_D: { name: 'D', alias: 'SI_D', title: 'd and D' },
  KC_F: { name: 'F', alias: 'SI_F', title: 'f and F' },
  KC_G: { name: 'G', alias: 'SI_G', title: 'g and G' },
  KC_H: { name: 'H', alias: 'SI_H', title: 'h and H' },
  KC_J: { name: 'J', alias: 'SI_J', title: 'j and J' },
  KC_K: { name: 'K', alias: 'SI_K', title: 'k and K' },
  KC_L: { name: 'L', alias: 'SI_L', title: 'l and L' },
  KC_SCLN: { name: 'Č', alias: 'SI_CCAR', title: 'č and Č' },
  KC_QUOT: { name: 'Ć', alias: 'SI_CACU', title: 'ć and Ć' },
  KC_NUHS: { name: 'Ž', alias: 'SI_ZCAR', title: 'ž and Ž' },
  // Row 4
  KC_NUBS: { name: '>\n<', alias: 'SI_LABK', title: '< and >' },
  KC_Z: { name: 'Y', alias: 'SI_Y', title: 'y and Y' },
  KC_X: { name: 'X', alias: 'SI_X', title: 'x and X' },
  KC_C: { name: 'C', alias: 'SI_C', title: 'c and C' },
  KC_V: { name: 'V', alias: 'SI_V', title: 'v and V' },
  KC_B: { name: 'B', alias: 'SI_B', title: 'b and B' },
  KC_N: { name: 'N', alias: 'SI_N', title: 'n and N' },
  KC_M: { name: 'M', alias: 'SI_M', title: 'm and M' },
  KC_COMM: { name: ';\n,', alias: 'SI_COMM', title: ', and ;' },
  KC_DOT: { name: ':\n.', alias: 'SI_DOT', title: '. and :' },
  KC_SLSH: { name: '_\n-', alias: 'SI_MINS', title: '- and _' },

  /* Shifted symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ ¨ │ ! │ " │ # │ $ │ % │ & │ / │ ( │ ) │ = │ ? │ * │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │   │   │   │   │   │   │   │   │   │   │   │   │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │   │   │   │   │   │   │   │   │   │   │   │   │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │ > │   │   │   │   │   │   │   │ ; │ : │ _ │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  'S(KC_GRV)': { name: '¨', alias: 'SI_DIAE', title: '◌̈ (dead)' },
  KC_TILD: { name: '¨', alias: 'SI_DIAE', title: '◌̈ (dead)' },
  'S(KC_1)': { name: '!', alias: 'SI_EXLM', title: '!' },
  KC_EXLM: { name: '!', alias: 'SI_EXLM', title: '!' },
  'S(KC_2)': { name: '"', alias: 'SI_DQUO', title: '"' },
  KC_AT: { name: '"', alias: 'SI_DQUO', title: '"' },
  'S(KC_3)': { name: '#', alias: 'SI_HASH', title: '#' },
  KC_HASH: { name: '#', alias: 'SI_HASH', title: '#' },
  'S(KC_4)': { name: '$', alias: 'SI_DLR', title: '$' },
  KC_DLR: { name: '$', alias: 'SI_DLR', title: '$' },
  'S(KC_5)': { name: '%', alias: 'SI_PERC', title: '%' },
  KC_PERC: { name: '%', alias: 'SI_PERC', title: '%' },
  'S(KC_6)': { name: '&', alias: 'SI_AMPR', title: '&' },
  KC_CIRC: { name: '&', alias: 'SI_AMPR', title: '&' },
  'S(KC_7)': { name: '/', alias: 'SI_SLSH', title: '/' },
  KC_AMPR: { name: '/', alias: 'SI_SLSH', title: '/' },
  'S(KC_8)': { name: '(', alias: 'SI_LPRN', title: '(' },
  KC_ASTR: { name: '(', alias: 'SI_LPRN', title: '(' },
  'S(KC_9)': { name: ')', alias: 'SI_RPRN', title: ')' },
  KC_LPRN: { name: ')', alias: 'SI_RPRN', title: ')' },
  'S(KC_0)': { name: '=', alias: 'SI_EQL', title: '=' },
  KC_RPRN: { name: '=', alias: 'SI_EQL', title: '=' },
  'S(KC_MINS)': { name: '?', alias: 'SI_QUES', title: '?' },
  KC_UNDS: { name: '?', alias: 'SI_QUES', title: '?' },
  'S(KC_EQL)': { name: '*', alias: 'SI_ASTR', title: '*' },
  KC_PLUS: { name: '*', alias: 'SI_ASTR', title: '*' },
  // Row 4
  'S(KC_NUBS)': { name: '>', alias: 'SI_RABK', title: '>' },
  'S(KC_COMM)': { name: ';', alias: 'SI_SCLN', title: ';' },
  KC_LT: { name: ';', alias: 'SI_SCLN', title: ';' },
  'S(KC_DOT)': { name: ':', alias: 'SI_COLN', title: ':' },
  KC_GT: { name: ':', alias: 'SI_COLN', title: ':' },
  'S(KC_SLSH)': { name: '_', alias: 'SI_UNDS', title: '_' },
  KC_QUES: { name: '_', alias: 'SI_UNDS', title: '_' },

  /* AltGr symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │   │ ~ │ ˇ │ ^ │ ˘ │ ° │ ˛ │ ` │ ˙ │ ´ │ ˝ │   │   │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │ \ │ | │ € │   │   │   │   │   │   │   │ ÷ │ × │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │   │   │   │ [ │ ] │   │   │ ł │ Ł │   │ ß │ ¤ │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │   │   │   │   │ @ │ { │ } │ § │   │   │   │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  'ALGR(KC_1)': { name: '~', alias: 'SI_TILD', title: '~' },
  'ALGR(KC_2)': { name: 'ˇ', alias: 'SI_CARN', title: '◌̌ (dead)' },
  'ALGR(KC_3)': { name: '^', alias: 'SI_CIRC', title: '◌̂ (dead)' },
  'ALGR(KC_4)': { name: '˘', alias: 'SI_BREV', title: '◌̆ (dead)' },
  'ALGR(KC_5)': { name: '°', alias: 'SI_RNGA', title: '◌̊ (dead)' },
  'ALGR(KC_6)': { name: '˛', alias: 'SI_OGON', title: '◌̨ (dead)' },
  'ALGR(KC_7)': { name: '`', alias: 'SI_GRV', title: '`' },
  'ALGR(KC_8)': { name: '˙', alias: 'SI_DOTA', title: '◌̇ (dead)' },
  'ALGR(KC_9)': { name: '´', alias: 'SI_ACUT', title: '◌́ (dead)' },
  'ALGR(KC_0)': { name: '˝', alias: 'SI_DACU', title: '◌̋ (dead)' },
  // Row 2
  'ALGR(KC_Q)': { name: '\\', alias: 'SI_BSLS', title: '\\' },
  'ALGR(KC_W)': { name: '|', alias: 'SI_PIPE', title: '|' },
  'ALGR(KC_E)': { name: '€', alias: 'SI_EURO', title: '€' },
  'ALGR(KC_LBRC)': { name: '÷', alias: 'SI_DIV', title: '÷' },
  'ALGR(KC_RBRC)': { name: '×', alias: 'SI_MUL', title: '×' },
  // Row 3
  'ALGR(KC_F)': { name: '[', alias: 'SI_LBRC', title: '[' },
  'ALGR(KC_G)': { name: ']', alias: 'SI_RBRC', title: ']' },
  'ALGR(KC_K)': { name: 'ł', alias: 'SI_LLST', title: 'ł' },
  'ALGR(KC_L)': { name: 'Ł', alias: 'SI_CLST', title: 'Ł' },
  'ALGR(KC_QUOT)': { name: 'ß', alias: 'SI_SS', title: 'ß' },
  'ALGR(KC_NUHS)': { name: '¤', alias: 'SI_CURR', title: '¤' },
  // Row 4
  'ALGR(KC_V)': { name: '@', alias: 'SI_AT', title: '@' },
  'ALGR(KC_B)': { name: '{', alias: 'SI_LCBR', title: '{' },
  'ALGR(KC_N)': { name: '}', alias: 'SI_RCBR', title: '}' },
  'ALGR(KC_M)': { name: '§', alias: 'SI_SECT', title: '§' },

  /* Other keys */
  KC_BSLS: { name: 'Ž', title: 'Ž' },
  'S(KC_BSLS)': { name: 'Ž', title: 'Ž' },
  KC_LCBR: { name: 'Š', alias: 'S(SI_SCAR)', title: 'Š' },
  KC_RCBR: { name: 'Đ', alias: 'S(SI_DSTR)', title: 'Đ' },
  KC_COLN: { name: 'Č', alias: 'S(SI_CCAR)', title: 'Č' },
  KC_PIPE: { name: 'Ž', alias: 'SI_ZCAR', title: 'Ž' },
  KC_DQUO: { name: 'Ć', alias: 'S(SI_CACU)', title: 'Ć' },

  SC_LSPO: { name: 'LS / )', title: 'Left Shift when held, ) when tapped' },
  SC_RSPC: { name: 'RS / =', title: 'Right Shift when held, = when tapped' },
  SC_LCPO: { name: 'LC / )', title: 'Left Control when held, ) when tapped' },
  SC_RCPC: { name: 'RC / =', title: 'Right Control when held, = when tapped' },
  SC_LAPO: { name: 'LA / )', title: 'Left Alt when held, ) when tapped' },
  SC_RAPC: { name: 'RA / =', title: 'Right Alt when held, = when tapped' },

  QK_GESC: {
    name: '¸/¨\nEsc',
    title: 'Esc normally, but ¸ when GUI is active or ¨ when Shift is active'
  }
};
