/* Copyright 2022 - Generated by convert_keymap_extras_header.js
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

export default {
  /*
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ ` │ 1 │ 2 │ 3 │ 4 │ 5 │ 6 │ 7 │ 8 │ 9 │ 0 │ - │ = │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │ Q │ W │ E │ R │ T │ Y │ U │ I │ O │ P │ [ │ ] │  ₩  │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴─────┤
   * │      │ A │ S │ D │ F │ G │ H │ J │ K │ L │ ; │ ' │        │
   * ├──────┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴────────┤
   * │        │ Z │ X │ C │ V │ B │ N │ M │ , │ . │ / │          │
   * ├─────┬──┴┬──┴──┬┴──┬┴───┴───┴───┴──┬┴──┬┴───┴┬──┴┬───┬─────┤
   * │     │   │     │Hnj│               │H↔Y│     │   │   │     │
   * └─────┴───┴─────┴───┴───────────────┴───┴─────┴───┴───┴─────┘
   */
  // Row 1
  KC_GRV: { name: '~\n`', alias: 'KR_GRV', title: '` and ~' },
  KC_1: { name: '!\n1', alias: 'KR_1', title: '1 and !' },
  KC_2: { name: '@\n2', alias: 'KR_2', title: '2 and @' },
  KC_3: { name: '#\n3', alias: 'KR_3', title: '3 and #' },
  KC_4: { name: '$\n4', alias: 'KR_4', title: '4 and $' },
  KC_5: { name: '%\n5', alias: 'KR_5', title: '5 and %' },
  KC_6: { name: '^\n6', alias: 'KR_6', title: '6 and ^' },
  KC_7: { name: '&\n7', alias: 'KR_7', title: '7 and &' },
  KC_8: { name: '*\n8', alias: 'KR_8', title: '8 and *' },
  KC_9: { name: '(\n9', alias: 'KR_9', title: '9 and (' },
  KC_0: { name: ')\n0', alias: 'KR_0', title: '0 and )' },
  KC_MINS: { name: '_\n-', alias: 'KR_MINS', title: '- and _' },
  KC_EQL: { name: '+\n=', alias: 'KR_EQL', title: '= and +' },
  // Row 2
  KC_Q: { name: 'Q', alias: 'KR_Q', title: 'q and Q' },
  KC_W: { name: 'W', alias: 'KR_W', title: 'w and W' },
  KC_E: { name: 'E', alias: 'KR_E', title: 'e and E' },
  KC_R: { name: 'R', alias: 'KR_R', title: 'r and R' },
  KC_T: { name: 'T', alias: 'KR_T', title: 't and T' },
  KC_Y: { name: 'Y', alias: 'KR_Y', title: 'y and Y' },
  KC_U: { name: 'U', alias: 'KR_U', title: 'u and U' },
  KC_I: { name: 'I', alias: 'KR_I', title: 'i and I' },
  KC_O: { name: 'O', alias: 'KR_O', title: 'o and O' },
  KC_P: { name: 'P', alias: 'KR_P', title: 'p and P' },
  KC_LBRC: { name: '{\n[', alias: 'KR_LBRC', title: '[ and {' },
  KC_RBRC: { name: '}\n]', alias: 'KR_RBRC', title: '] and }' },
  KC_BSLS: { name: '|\n₩', alias: 'KR_WON', title: '₩ and |' },
  // Row 3
  KC_A: { name: 'A', alias: 'KR_A', title: 'a and A' },
  KC_S: { name: 'S', alias: 'KR_S', title: 's and S' },
  KC_D: { name: 'D', alias: 'KR_D', title: 'd and D' },
  KC_F: { name: 'F', alias: 'KR_F', title: 'f and F' },
  KC_G: { name: 'G', alias: 'KR_G', title: 'g and G' },
  KC_H: { name: 'H', alias: 'KR_H', title: 'h and H' },
  KC_J: { name: 'J', alias: 'KR_J', title: 'j and J' },
  KC_K: { name: 'K', alias: 'KR_K', title: 'k and K' },
  KC_L: { name: 'L', alias: 'KR_L', title: 'l and L' },
  KC_SCLN: { name: ':\n;', alias: 'KR_SCLN', title: '; and :' },
  KC_QUOT: { name: '"\n\'', alias: 'KR_QUOT', title: '\' and "' },
  // Row 4
  KC_Z: { name: 'Z', alias: 'KR_Z', title: 'z and Z' },
  KC_X: { name: 'X', alias: 'KR_X', title: 'x and X' },
  KC_C: { name: 'C', alias: 'KR_C', title: 'c and C' },
  KC_V: { name: 'V', alias: 'KR_V', title: 'v and V' },
  KC_B: { name: 'B', alias: 'KR_B', title: 'b and B' },
  KC_N: { name: 'N', alias: 'KR_N', title: 'n and N' },
  KC_M: { name: 'M', alias: 'KR_M', title: 'm and M' },
  KC_COMM: { name: '<\n,', alias: 'KR_COMM', title: ', and <' },
  KC_DOT: { name: '>\n.', alias: 'KR_DOT', title: '. and >' },
  KC_SLSH: { name: '?\n/', alias: 'KR_SLSH', title: '/ and ?' },
  // Row 5
  KC_LNG2: { name: '한자', alias: 'KR_HANJ', title: '한자 (Hanja)' },
  KC_LNG1: {
    name: '한 / 영',
    alias: 'KR_HAEN',
    title: '한 (Han) ↔ 영 (Yeong)'
  },

  /* Shifted symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ ~ │ ! │ @ │ # │ $ │ % │ ^ │ & │ * │ ( │ ) │ _ │ + │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │   │   │   │   │   │   │   │   │   │   │ { │ } │  |  │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴─────┤
   * │      │   │   │   │   │   │   │   │   │   │ : │ " │        │
   * ├──────┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴────────┤
   * │        │   │   │   │   │   │   │   │ < │ > │ ? │          │
   * ├─────┬──┴┬──┴──┬┴──┬┴───┴───┴───┴──┬┴──┬┴───┴┬──┴┬───┬─────┤
   * │     │   │     │   │               │   │     │   │   │     │
   * └─────┴───┴─────┴───┴───────────────┴───┴─────┴───┴───┴─────┘
   */
  // Row 1
  'S(KC_GRV)': { name: '~', alias: 'KR_TILD', title: '~' },
  KC_TILD: { name: '~', alias: 'KR_TILD', title: '~' },
  'S(KC_1)': { name: '!', alias: 'KR_EXLM', title: '!' },
  KC_EXLM: { name: '!', alias: 'KR_EXLM', title: '!' },
  'S(KC_2)': { name: '@', alias: 'KR_AT', title: '@' },
  KC_AT: { name: '@', alias: 'KR_AT', title: '@' },
  'S(KC_3)': { name: '#', alias: 'KR_HASH', title: '#' },
  KC_HASH: { name: '#', alias: 'KR_HASH', title: '#' },
  'S(KC_4)': { name: '$', alias: 'KR_DLR', title: '$' },
  KC_DLR: { name: '$', alias: 'KR_DLR', title: '$' },
  'S(KC_5)': { name: '%', alias: 'KR_PERC', title: '%' },
  KC_PERC: { name: '%', alias: 'KR_PERC', title: '%' },
  'S(KC_6)': { name: '^', alias: 'KR_CIRC', title: '^' },
  KC_CIRC: { name: '^', alias: 'KR_CIRC', title: '^' },
  'S(KC_7)': { name: '&', alias: 'KR_AMPR', title: '&' },
  KC_AMPR: { name: '&', alias: 'KR_AMPR', title: '7' },
  'S(KC_8)': { name: '*', alias: 'KR_ASTR', title: '*' },
  KC_ASTR: { name: '*', alias: 'KR_ASTR', title: '*' },
  'S(KC_9)': { name: '(', alias: 'KR_LPRN', title: '(' },
  KC_LPRN: { name: '(', alias: 'KR_LPRN', title: '(' },
  'S(KC_0)': { name: ')', alias: 'KR_RPRN', title: ')' },
  KC_RPRN: { name: ')', alias: 'KR_RPRN', title: ')' },
  'S(KC_MINS)': { name: '_', alias: 'KR_UNDS', title: '_' },
  KC_UNDS: { name: '_', alias: 'KR_UNDS', title: '_' },
  'S(KC_EQL)': { name: '+', alias: 'KR_PLUS', title: '+' },
  KC_PLUS: { name: '+', alias: 'KR_PLUS', title: '+' },
  // Row 2
  'S(KC_LBRC)': { name: '{', alias: 'KR_LCBR', title: '{' },
  KC_LCBR: { name: '{', alias: 'KR_LCBR', title: '{' },
  'S(KC_RBRC)': { name: '}', alias: 'KR_RCBR', title: '}' },
  KC_RCBR: { name: '}', alias: 'KR_RCBR', title: '}' },
  'S(KC_BSLS)': { name: '|', alias: 'KR_PIPE', title: '|' },
  KC_PIPE: { name: '|', alias: 'KR_PIPE', title: '|' },
  // Row 3
  'S(KC_SCLN)': { name: ':', alias: 'KR_COLN', title: ':' },
  KC_COLN: { name: ':', alias: 'KR_COLN', title: ':' },
  'S(KC_QUOT)': { name: '"', alias: 'KR_DQUO', title: '"' },
  KC_DQUO: { name: '"', alias: 'KR_DQUO', title: '"' },
  // Row 4
  'S(KC_COMM)': { name: '<', alias: 'KR_LABK', title: '<' },
  KC_LT: { name: '<', alias: 'KR_LABK', title: '<' },
  'S(KC_DOT)': { name: '>', alias: 'KR_RABK', title: '>' },
  KC_GT: { name: '>', alias: 'KR_RABK', title: '>' },
  'S(KC_SLSH)': { name: '?', alias: 'KR_QUES', title: '?' },
  KC_QUES: { name: '?', alias: 'KR_QUES', title: '?' },

  /* Other keys */
  KC_NUHS: { name: '|\n₩', title: '₩ and |' },
  'S(KC_NUHS)': { name: '|', title: '|' },
  KC_NUBS: { name: '|\n₩', title: '₩ and |' },
  'S(KC_NUBS)': { name: '|', title: '|' },

  SC_LSPO: { name: 'LS / (', title: 'Left Shift when held, ( when tapped' },
  SC_RSPC: { name: 'RS / )', title: 'Right Shift when held, ) when tapped' },
  SC_LCPO: { name: 'LC / (', title: 'Left Control when held, ( when tapped' },
  SC_RCPC: { name: 'RC / )', title: 'Right Control when held, ) when tapped' },
  SC_LAPO: { name: 'LA / (', title: 'Left Alt when held, ( when tapped' },
  SC_RAPC: { name: 'RA / )', title: 'Right Alt when held, ) when tapped' },

  QK_GESC: {
    name: '`/~\nEsc',
    title: 'Esc normally, but ` when GUI is active or ~ when Shift is active'
  }
};
