/* Copyright 2022 - Generated by convert_keymap_extras_header.js
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

export default {
  /*
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ ˇ │ 1 │ 2 │ 3 │ 4 │ 5 │ 6 │ 7 │ 8 │ 9 │ 0 │ + │ ´ │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │ Q │ W │ E │ R │ T │ Y │ U │ I │ O │ P │ Ü │ Õ │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │ A │ S │ D │ F │ G │ H │ J │ K │ L │ Ö │ Ä │ ' │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │ < │ Z │ X │ C │ V │ B │ N │ M │ , │ . │ - │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  KC_GRV: { name: '~\nˇ', alias: 'EE_CARN', title: '◌̌ (dead) and ◌̃ (dead)' },
  KC_1: { name: '!\n1', alias: 'EE_1', title: '1 and !' },
  KC_2: { name: '"\n2', alias: 'EE_2', title: '2 and "' },
  KC_3: { name: '#\n3', alias: 'EE_3', title: '3 and #' },
  KC_4: { name: '¤\n4', alias: 'EE_4', title: '4 and ¤' },
  KC_5: { name: '%\n5', alias: 'EE_5', title: '5 and %' },
  KC_6: { name: '&\n6', alias: 'EE_6', title: '6 and &' },
  KC_7: { name: '/\n7', alias: 'EE_7', title: '7 and /' },
  KC_8: { name: '(\n8', alias: 'EE_8', title: '8 and (' },
  KC_9: { name: ')\n9', alias: 'EE_9', title: '9 and )' },
  KC_0: { name: '=\n0', alias: 'EE_0', title: '0 and =' },
  KC_MINS: { name: '?\n+', alias: 'EE_PLUS', title: '+ and ?' },
  KC_EQL: { name: '`\n´', alias: 'EE_ACUT', title: '◌́ (dead) and ◌̀ (dead)' },
  // Row 2
  KC_Q: { name: 'Q', alias: 'EE_Q', title: 'q and Q' },
  KC_W: { name: 'W', alias: 'EE_W', title: 'w and W' },
  KC_E: { name: 'E', alias: 'EE_E', title: 'e and E' },
  KC_R: { name: 'R', alias: 'EE_R', title: 'r and R' },
  KC_T: { name: 'T', alias: 'EE_T', title: 't and T' },
  KC_Y: { name: 'Y', alias: 'EE_Y', title: 'y and Y' },
  KC_U: { name: 'U', alias: 'EE_U', title: 'u and U' },
  KC_I: { name: 'I', alias: 'EE_I', title: 'i and I' },
  KC_O: { name: 'O', alias: 'EE_O', title: 'o and O' },
  KC_P: { name: 'P', alias: 'EE_P', title: 'p and P' },
  KC_LBRC: { name: 'Ü', alias: 'EE_UDIA', title: 'ü and Ü' },
  KC_RBRC: { name: 'Õ', alias: 'EE_OTIL', title: 'õ and Õ' },
  // Row 3
  KC_A: { name: 'A', alias: 'EE_A', title: 'a and A' },
  KC_S: { name: 'S', alias: 'EE_S', title: 's and S' },
  KC_D: { name: 'D', alias: 'EE_D', title: 'd and D' },
  KC_F: { name: 'F', alias: 'EE_F', title: 'f and F' },
  KC_G: { name: 'G', alias: 'EE_G', title: 'g and G' },
  KC_H: { name: 'H', alias: 'EE_H', title: 'h and H' },
  KC_J: { name: 'J', alias: 'EE_J', title: 'j and J' },
  KC_K: { name: 'K', alias: 'EE_K', title: 'k and K' },
  KC_L: { name: 'L', alias: 'EE_L', title: 'l and L' },
  KC_SCLN: { name: 'Ö', alias: 'EE_ODIA', title: 'ö and Ö' },
  KC_QUOT: { name: 'Ä', alias: 'EE_ADIA', title: 'ä and Ä' },
  KC_NUHS: { name: "*\n'", alias: 'EE_QUOT', title: "' and *" },
  // Row 4
  KC_NUBS: { name: '>\n<', alias: 'EE_LABK', title: '< and >' },
  KC_Z: { name: 'Z', alias: 'EE_Z', title: 'z and Z' },
  KC_X: { name: 'X', alias: 'EE_X', title: 'x and X' },
  KC_C: { name: 'C', alias: 'EE_C', title: 'c and C' },
  KC_V: { name: 'V', alias: 'EE_V', title: 'v and V' },
  KC_B: { name: 'B', alias: 'EE_B', title: 'b and B' },
  KC_N: { name: 'N', alias: 'EE_N', title: 'n and N' },
  KC_M: { name: 'M', alias: 'EE_M', title: 'm and M' },
  KC_COMM: { name: ';\n,', alias: 'EE_COMM', title: ', and ;' },
  KC_DOT: { name: ':\n.', alias: 'EE_DOT', title: '. and :' },
  KC_SLSH: { name: '_\n-', alias: 'EE_MINS', title: '- and _' },

  /* Shifted symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ ~ │ ! │ " │ # │ ¤ │ % │ & │ / │ ( │ ) │ = │ ? │ ` │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │   │   │   │   │   │   │   │   │   │   │   │   │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │   │   │   │   │   │   │   │   │   │   │   │ * │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │ > │   │   │   │   │   │   │   │ ; │ : │ _ │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  'S(KC_GRV)': { name: '~', alias: 'EE_TILD', title: '◌̃ (dead)' },
  KC_TILD: { name: '~', alias: 'EE_TILD', title: '◌̃ (dead)' },
  'S(KC_1)': { name: '!', alias: 'EE_EXLM', title: '!' },
  KC_EXLM: { name: '!', alias: 'EE_EXLM', title: '!' },
  'S(KC_2)': { name: '"', alias: 'EE_DQUO', title: '"' },
  KC_AT: { name: '"', alias: 'EE_DQUO', title: '"' },
  'S(KC_3)': { name: '#', alias: 'EE_HASH', title: '#' },
  KC_HASH: { name: '#', alias: 'EE_HASH', title: '#' },
  'S(KC_4)': { name: '¤', alias: 'EE_CURR', title: '¤' },
  KC_DLR: { name: '¤', alias: 'EE_CURR', title: '¤' },
  'S(KC_5)': { name: '%', alias: 'EE_PERC', title: '%' },
  KC_PERC: { name: '%', alias: 'EE_PERC', title: '%' },
  'S(KC_6)': { name: '&', alias: 'EE_AMPR', title: '&' },
  KC_CIRC: { name: '&', alias: 'EE_AMPR', title: '&' },
  'S(KC_7)': { name: '/', alias: 'EE_SLSH', title: '/' },
  KC_AMPR: { name: '/', alias: 'EE_SLSH', title: '/' },
  'S(KC_8)': { name: '(', alias: 'EE_LPRN', title: '(' },
  KC_ASTR: { name: '(', alias: 'EE_LPRN', title: '(' },
  'S(KC_9)': { name: ')', alias: 'EE_RPRN', title: ')' },
  KC_LPRN: { name: ')', alias: 'EE_RPRN', title: ')' },
  'S(KC_0)': { name: '=', alias: 'EE_EQL', title: '=' },
  KC_RPRN: { name: '=', alias: 'EE_EQL', title: '=' },
  'S(KC_MINS)': { name: '?', alias: 'EE_QUES', title: '?' },
  KC_UNDS: { name: '?', alias: 'EE_QUES', title: '?' },
  'S(KC_EQL)': { name: '`', alias: 'EE_GRV', title: '◌̀ (dead)' },
  KC_PLUS: { name: '`', alias: 'EE_GRV', title: '◌̀ (dead)' },
  // Row 3
  'S(KC_NUHS)': { name: '*', alias: 'EE_ASTR', title: '*' },
  // Row 4
  'S(KC_NUBS)': { name: '>', alias: 'EE_RABK', title: '>' },
  'S(KC_COMM)': { name: ';', alias: 'EE_SCLN', title: ';' },
  KC_LT: { name: ';', alias: 'EE_SCLN', title: ';' },
  'S(KC_DOT)': { name: ':', alias: 'EE_COLN', title: ':' },
  KC_GT: { name: ':', alias: 'EE_COLN', title: ':' },
  'S(KC_SLSH)': { name: '_', alias: 'EE_UNDS', title: '_' },
  KC_QUES: { name: '_', alias: 'EE_UNDS', title: '_' },

  /* AltGr symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │   │   │ @ │ £ │ $ │ € │   │ { │ [ │ ] │ } │ \ │   │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │   │   │   │   │   │   │   │   │   │   │   │ § │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │   │ š │   │   │   │   │   │   │   │   │ ^ │ ½ │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │ | │ ž │   │   │   │   │   │   │   │   │   │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  'ALGR(KC_2)': { name: '@', alias: 'EE_AT', title: '@' },
  'ALGR(KC_3)': { name: '£', alias: 'EE_PND', title: '£' },
  'ALGR(KC_4)': { name: '$', alias: 'EE_DLR', title: '$' },
  'ALGR(KC_5)': { name: '€', alias: 'EE_EURO', title: '€' },
  'ALGR(KC_7)': { name: '{', alias: 'EE_LCBR', title: '{' },
  'ALGR(KC_8)': { name: '[', alias: 'EE_LBRC', title: '[' },
  'ALGR(KC_9)': { name: ']', alias: 'EE_RBRC', title: ']' },
  'ALGR(KC_0)': { name: '}', alias: 'EE_RCBR', title: '}' },
  'ALGR(KC_MINS)': { name: '\\', alias: 'EE_BSLS', title: '\\' },
  // Row 2
  'ALGR(KC_RBRC)': { name: '§', alias: 'EE_SECT', title: '§' },
  // Row 3
  'ALGR(KC_S)': { name: 'š', alias: 'EE_SCAR', title: 'š' },
  'ALGR(KC_QUOT)': { name: '^', alias: 'EE_CIRC', title: '◌̂ (dead)' },
  'ALGR(KC_NUHS)': { name: '½', alias: 'EE_HALF', title: '½' },
  // Row 4
  'ALGR(KC_NUBS)': { name: '|', alias: 'EE_PIPE', title: '|' },
  'ALGR(KC_Z)': { name: 'ž', alias: 'EE_ZCAR', title: 'ž' },

  /* Other keys */
  KC_BSLS: { name: "*\n'", title: "' and *" },
  'S(KC_BSLS)': { name: '*', title: '&*' },
  KC_LCBR: { name: 'Ü', alias: 'S(EE_UDIA)', title: 'Ü' },
  KC_RCBR: { name: 'Õ', alias: 'S(EE_OTIL)', title: 'Õ' },
  KC_COLN: { name: 'Ö', alias: 'S(EE_ODIA)', title: 'Ö' },
  KC_PIPE: { name: '*', alias: 'EE_ASTR', title: '*' },
  KC_DQUO: { name: 'Ä', alias: 'S(EE_ADIA)', title: 'Ä' },

  SC_LSPO: { name: 'LS / )', title: 'Left Shift when held, ) when tapped' },
  SC_RSPC: { name: 'RS / =', title: 'Right Shift when held, = when tapped' },
  SC_LCPO: { name: 'LC / )', title: 'Left Control when held, ) when tapped' },
  SC_RCPC: { name: 'RC / =', title: 'Right Control when held, = when tapped' },
  SC_LAPO: { name: 'LA / )', title: 'Left Alt when held, ) when tapped' },
  SC_RAPC: { name: 'RA / =', title: 'Right Alt when held, = when tapped' },

  QK_GESC: {
    name: 'ˇ/~\nEsc',
    title: 'Esc normally, but ˇ when GUI is active or ~ when Shift is active'
  }
};
