/* Copyright 2022 - Generated by convert_keymap_extras_header.js
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

export default {
  /*
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ ` │ 1 │ 2 │ 3 │ 4 │ 5 │ 6 │ 7 │ 8 │ 9 │ 0 │ ' │ + │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │ Љ │ Њ │ Е │ Р │ Т │ З │ У │ И │ О │ П │ Ш │ Ђ │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │ А │ С │ Д │ Ф │ Г │ Х │ Ј │ К │ Л │ Ч │ Ћ │ Ж │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │ < │ Ѕ │ Џ │ Ц │ В │ Б │ Н │ М │ , │ . │ - │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  KC_GRV: { name: '~\n`', alias: 'RS_GRV', title: '` and ~' },
  KC_1: { name: '!\n1', alias: 'RS_1', title: '1 and !' },
  KC_2: { name: '"\n2', alias: 'RS_2', title: '2 and "' },
  KC_3: { name: '#\n3', alias: 'RS_3', title: '3 and #' },
  KC_4: { name: '$\n4', alias: 'RS_4', title: '4 and $' },
  KC_5: { name: '%\n5', alias: 'RS_5', title: '5 and %' },
  KC_6: { name: '&\n6', alias: 'RS_6', title: '6 and &' },
  KC_7: { name: '/\n7', alias: 'RS_7', title: '7 and /' },
  KC_8: { name: '(\n8', alias: 'RS_8', title: '8 and (' },
  KC_9: { name: ')\n9', alias: 'RS_9', title: '9 and )' },
  KC_0: { name: '=\n0', alias: 'RS_0', title: '0 and =' },
  KC_MINS: { name: "?\n'", alias: 'RS_QUOT', title: "' (dead) and ?" },
  KC_EQL: { name: '*\n+', alias: 'RS_PLUS', title: '+ and *' },
  // Row 2
  KC_Q: { name: 'Љ', alias: 'RS_LJE', title: 'љ and Љ' },
  KC_W: { name: 'Њ', alias: 'RS_NJE', title: 'њ and Њ' },
  KC_E: { name: 'Е', alias: 'RS_IE', title: 'е and Е' },
  KC_R: { name: 'Р', alias: 'RS_ER', title: 'р and Р' },
  KC_T: { name: 'Т', alias: 'RS_TE', title: 'т and Т' },
  KC_Y: { name: 'З', alias: 'RS_ZE', title: 'з and З' },
  KC_U: { name: 'У', alias: 'RS_U', title: 'у and У' },
  KC_I: { name: 'И', alias: 'RS_I', title: 'и and И' },
  KC_O: { name: 'О', alias: 'RS_O', title: 'о and О' },
  KC_P: { name: 'П', alias: 'RS_PE', title: 'п and П' },
  KC_LBRC: { name: 'Ш', alias: 'RS_SHA', title: 'ш and Ш' },
  KC_RBRC: { name: 'Ђ', alias: 'RS_DJE', title: 'ђ and Ђ' },
  // Row 3
  KC_A: { name: 'А', alias: 'RS_A', title: 'а and А' },
  KC_S: { name: 'С', alias: 'RS_ES', title: 'с and С' },
  KC_D: { name: 'Д', alias: 'RS_DE', title: 'д and Д' },
  KC_F: { name: 'Ф', alias: 'RS_EF', title: 'ф and Ф' },
  KC_G: { name: 'Г', alias: 'RS_GHE', title: 'г and Г' },
  KC_H: { name: 'Х', alias: 'RS_HA', title: 'х and Х' },
  KC_J: { name: 'Ј', alias: 'RS_JE', title: 'ј and Ј' },
  KC_K: { name: 'К', alias: 'RS_KA', title: 'к and К' },
  KC_L: { name: 'Л', alias: 'RS_EL', title: 'л and Л' },
  KC_SCLN: { name: 'Ч', alias: 'RS_CHE', title: 'ч and Ч' },
  KC_QUOT: { name: 'Ћ', alias: 'RS_TSHE', title: 'ћ and Ћ' },
  KC_NUHS: { name: 'Ж', alias: 'RS_ZHE', title: 'ж and Ж' },
  // Row 4
  KC_NUBS: { name: '>\n<', alias: 'RS_LABK', title: '< and >' },
  KC_Z: { name: 'Ѕ', alias: 'RS_DZE', title: 'ѕ and Ѕ' },
  KC_X: { name: 'Џ', alias: 'RS_DZHE', title: 'џ and Џ' },
  KC_C: { name: 'Ц', alias: 'RS_TSE', title: 'ц and Ц' },
  KC_V: { name: 'В', alias: 'RS_VE', title: 'в and В' },
  KC_B: { name: 'Б', alias: 'RS_BE', title: 'б and Б' },
  KC_N: { name: 'Н', alias: 'RS_EN', title: 'н and Н' },
  KC_M: { name: 'М', alias: 'RS_EM', title: 'м and М' },
  KC_COMM: { name: ';\n,', alias: 'RS_COMM', title: ', and ;' },
  KC_DOT: { name: ':\n.', alias: 'RS_DOT', title: '. and :' },
  KC_SLSH: { name: '_\n-', alias: 'RS_MINS', title: '- and _' },

  /* Shifted symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ ~ │ ! │ " │ # │ $ │ % │ & │ / │ ( │ ) │ = │ ? │ * │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │   │   │   │   │   │   │   │   │   │   │   │   │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │   │   │   │   │   │   │   │   │   │   │   │   │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │ > │   │   │   │   │   │   │   │ ; │ : │ _ │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  'S(KC_GRV)': { name: '~', alias: 'RS_TILD', title: '~' },
  KC_TILD: { name: '~', alias: 'RS_TILD', title: '~' },
  'S(KC_1)': { name: '!', alias: 'RS_EXLM', title: '!' },
  KC_EXLM: { name: '!', alias: 'RS_EXLM', title: '!' },
  'S(KC_2)': { name: '"', alias: 'RS_DQUO', title: '"' },
  KC_AT: { name: '"', alias: 'RS_DQUO', title: '"' },
  'S(KC_3)': { name: '#', alias: 'RS_HASH', title: '#' },
  KC_HASH: { name: '#', alias: 'RS_HASH', title: '#' },
  'S(KC_4)': { name: '$', alias: 'RS_DLR', title: '$' },
  KC_DLR: { name: '$', alias: 'RS_DLR', title: '$' },
  'S(KC_5)': { name: '%', alias: 'RS_PERC', title: '%' },
  KC_PERC: { name: '%', alias: 'RS_PERC', title: '%' },
  'S(KC_6)': { name: '&', alias: 'RS_AMPR', title: '&' },
  KC_CIRC: { name: '&', alias: 'RS_AMPR', title: '&' },
  'S(KC_7)': { name: '/', alias: 'RS_SLSH', title: '/' },
  KC_AMPR: { name: '/', alias: 'RS_SLSH', title: '/' },
  'S(KC_8)': { name: '(', alias: 'RS_LPRN', title: '(' },
  KC_ASTR: { name: '(', alias: 'RS_LPRN', title: '(' },
  'S(KC_9)': { name: ')', alias: 'RS_RPRN', title: ')' },
  KC_LPRN: { name: ')', alias: 'RS_RPRN', title: ')' },
  'S(KC_0)': { name: '=', alias: 'RS_EQL', title: '=' },
  KC_RPRN: { name: '=', alias: 'RS_EQL', title: '=' },
  'S(KC_MINS)': { name: '?', alias: 'RS_QUES', title: '?' },
  KC_UNDS: { name: '?', alias: 'RS_QUES', title: '?' },
  'S(KC_EQL)': { name: '*', alias: 'RS_ASTR', title: '*' },
  KC_PLUS: { name: '*', alias: 'RS_ASTR', title: '*' },
  // Row 4
  'S(KC_NUBS)': { name: '>', alias: 'RS_RABK', title: '>' },
  'S(KC_COMM)': { name: ';', alias: 'RS_SCLN', title: ';' },
  KC_LT: { name: ';', alias: 'RS_SCLN', title: ';' },
  'S(KC_DOT)': { name: ':', alias: 'RS_COLN', title: ':' },
  KC_GT: { name: ':', alias: 'RS_COLN', title: ':' },
  'S(KC_SLSH)': { name: '_', alias: 'RS_UNDS', title: '_' },
  KC_QUES: { name: '_', alias: 'RS_UNDS', title: '_' },

  /* AltGr symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │   │   │   │   │   │   │   │   │   │   │   │   │   │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │   │   │ € │   │   │   │   │   │   │   │   │   │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │   │   │   │   │   │   │   │   │   │   │   │   │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │   │   │   │   │   │   │   │   │   │   │   │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 2
  'ALGR(KC_E)': { name: '€', alias: 'RS_EURO', title: '€' },

  /* Other keys */
  KC_BSLS: { name: 'Ж', title: 'Ж' },
  'S(KC_BSLS)': { name: 'Ж', title: 'Ж' },
  KC_LCBR: { name: 'Ш', alias: 'S(RS_SHA)', title: 'Ш' },
  KC_RCBR: { name: 'Ђ', alias: 'S(RS_DJE)', title: 'Ђ' },
  KC_COLN: { name: 'Ч', alias: 'S(RS_CHE)', title: 'Ч' },
  KC_PIPE: { name: 'Ж', alias: 'RS_ZHE', title: 'Ж' },
  KC_DQUO: { name: 'Ћ', alias: 'S(RS_TSHE)', title: 'Ћ' },

  SC_LSPO: { name: 'LS / )', title: 'Left Shift when held, ) when tapped' },
  SC_RSPC: { name: 'RS / =', title: 'Right Shift when held, = when tapped' },
  SC_LCPO: { name: 'LC / )', title: 'Left Control when held, ) when tapped' },
  SC_RCPC: { name: 'RC / =', title: 'Right Control when held, = when tapped' },
  SC_LAPO: { name: 'LA / )', title: 'Left Alt when held, ) when tapped' },
  SC_RAPC: { name: 'RA / =', title: 'Right Alt when held, = when tapped' },

  QK_GESC: {
    name: '`/~\nEsc',
    title: 'Esc normally, but ` when GUI is active or ~ when Shift is active'
  }
};
