/* Copyright 2022 - Generated by convert_keymap_extras_header.js
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

export default {
  /*
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ ½ │ 1 │ 2 │ 3 │ 4 │ 5 │ 6 │ 7 │ 8 │ 9 │ 0 │ + │ ´ │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │ Q │ W │ E │ R │ T │ Y │ U │ I │ O │ P │ Å │ ¨ │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │ A │ S │ D │ F │ G │ H │ J │ K │ L │ Æ │ Ø │ ' │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │ < │ Z │ X │ C │ V │ B │ N │ M │ , │ . │ - │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  KC_GRV: { name: '§\n½', alias: 'DK_HALF', title: '½ and §' },
  KC_1: { name: '!\n1', alias: 'DK_1', title: '1 and !' },
  KC_2: { name: '"\n2', alias: 'DK_2', title: '2 and "' },
  KC_3: { name: '#\n3', alias: 'DK_3', title: '3 and #' },
  KC_4: { name: '¤\n4', alias: 'DK_4', title: '4 and ¤' },
  KC_5: { name: '%\n5', alias: 'DK_5', title: '5 and %' },
  KC_6: { name: '&\n6', alias: 'DK_6', title: '6 and &' },
  KC_7: { name: '/\n7', alias: 'DK_7', title: '7 and /' },
  KC_8: { name: '(\n8', alias: 'DK_8', title: '8 and (' },
  KC_9: { name: ')\n9', alias: 'DK_9', title: '9 and )' },
  KC_0: { name: '=\n0', alias: 'DK_0', title: '0 and =' },
  KC_MINS: { name: '?\n+', alias: 'DK_PLUS', title: ' and ' },
  KC_EQL: { name: '`\n´', alias: 'DK_ACUT', title: '◌́ (dead) and ◌̀ (dead)' },
  // Row 2
  KC_Q: { name: 'Q', alias: 'DK_Q', title: 'q and Q' },
  KC_W: { name: 'W', alias: 'DK_W', title: 'w and W' },
  KC_E: { name: 'E', alias: 'DK_E', title: 'e and E' },
  KC_R: { name: 'R', alias: 'DK_R', title: 'r and R' },
  KC_T: { name: 'T', alias: 'DK_T', title: 't and T' },
  KC_Y: { name: 'Y', alias: 'DK_Y', title: 'y and Y' },
  KC_U: { name: 'U', alias: 'DK_U', title: 'u and U' },
  KC_I: { name: 'I', alias: 'DK_I', title: 'i and I' },
  KC_O: { name: 'O', alias: 'DK_O', title: 'o and O' },
  KC_P: { name: 'P', alias: 'DK_P', title: 'p and P' },
  KC_LBRC: { name: 'Å', alias: 'DK_ARNG', title: 'å and Å' },
  KC_RBRC: { name: '^\n¨', alias: 'DK_DIAE', title: '◌̈ (dead) and ◌̂ (dead)' },
  // Row 3
  KC_A: { name: 'A', alias: 'DK_A', title: 'a and A' },
  KC_S: { name: 'S', alias: 'DK_S', title: 's and S' },
  KC_D: { name: 'D', alias: 'DK_D', title: 'd and D' },
  KC_F: { name: 'F', alias: 'DK_F', title: 'f and F' },
  KC_G: { name: 'G', alias: 'DK_G', title: 'g and G' },
  KC_H: { name: 'H', alias: 'DK_H', title: 'h and H' },
  KC_J: { name: 'J', alias: 'DK_J', title: 'j and J' },
  KC_K: { name: 'K', alias: 'DK_K', title: 'k and K' },
  KC_L: { name: 'L', alias: 'DK_L', title: 'l and L' },
  KC_SCLN: { name: 'Æ', alias: 'DK_AE', title: 'æ and Æ' },
  KC_QUOT: { name: 'Ø', alias: 'DK_OSTR', title: 'ø and Ø' },
  KC_NUHS: { name: "*\n'", alias: 'DK_QUOT', title: "' and *" },
  // Row 4
  KC_NUBS: { name: '>\n<', alias: 'DK_LABK', title: '< and >' },
  KC_Z: { name: 'Z', alias: 'DK_Z', title: 'z and Z' },
  KC_X: { name: 'X', alias: 'DK_X', title: 'x and X' },
  KC_C: { name: 'C', alias: 'DK_C', title: 'c and C' },
  KC_V: { name: 'V', alias: 'DK_V', title: 'v and V' },
  KC_B: { name: 'B', alias: 'DK_B', title: 'b and B' },
  KC_N: { name: 'N', alias: 'DK_N', title: 'n and N' },
  KC_M: { name: 'M', alias: 'DK_M', title: 'm and M' },
  KC_COMM: { name: ';\n,', alias: 'DK_COMM', title: ', and ;' },
  KC_DOT: { name: ':\n.', alias: 'DK_DOT', title: '. and :' },
  KC_SLSH: { name: '_\n-', alias: 'DK_MINS', title: '- and _' },

  /* Shifted symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ § │ ! │ " │ # │ ¤ │ % │ & │ / │ ( │ ) │ = │ ? │ ` │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │   │   │   │   │   │   │   │   │   │   │   │ ^ │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │   │   │   │   │   │   │   │   │   │   │   │ * │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │ > │   │   │   │   │   │   │   │ ; │ : │ _ │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  'S(KC_GRV)': { name: '§', alias: 'DK_SECT', title: '§' },
  KC_TILD: { name: '§', alias: 'DK_SECT', title: '§' },
  'S(KC_1)': { name: '!', alias: 'DK_EXLM', title: '!' },
  KC_EXLM: { name: '!', alias: 'DK_EXLM', title: '!' },
  'S(KC_2)': { name: '"', alias: 'DK_DQUO', title: '"' },
  KC_AT: { name: '"', alias: 'DK_DQUO', title: '"' },
  'S(KC_3)': { name: '#', alias: 'DK_HASH', title: '#' },
  KC_HASH: { name: '#', alias: 'DK_HASH', title: '#' },
  'S(KC_4)': { name: '¤', alias: 'DK_CURR', title: '¤' },
  KC_DLR: { name: '¤', alias: 'DK_CURR', title: '¤' },
  'S(KC_5)': { name: '%', alias: 'DK_PERC', title: '%' },
  KC_PERC: { name: '%', alias: 'DK_PERC', title: '%' },
  'S(KC_6)': { name: '&', alias: 'DK_AMPR', title: '&' },
  KC_CIRC: { name: '&', alias: 'DK_AMPR', title: '&' },
  'S(KC_7)': { name: '/', alias: 'DK_SLSH', title: '/' },
  KC_AMPR: { name: '/', alias: 'DK_SLSH', title: '/' },
  'S(KC_8)': { name: '(', alias: 'DK_LPRN', title: '(' },
  KC_ASTR: { name: '(', alias: 'DK_LPRN', title: '(' },
  'S(KC_9)': { name: ')', alias: 'DK_RPRN', title: ')' },
  KC_LPRN: { name: ')', alias: 'DK_RPRN', title: ')' },
  'S(KC_0)': { name: '=', alias: 'DK_EQL', title: '=' },
  KC_RPRN: { name: '=', alias: 'DK_EQL', title: '=' },
  'S(KC_MINS)': { name: '?', alias: 'DK_QUES', title: '?' },
  KC_UNDS: { name: '?', alias: 'DK_QUES', title: '?' },
  'S(KC_EQL)': { name: '`', alias: 'DK_GRV', title: '◌̀ (dead)' },
  KC_PLUS: { name: '`', alias: 'DK_GRV', title: '◌̀ (dead)' },
  // Row 2
  'S(KC_RBRC)': { name: '^', alias: 'DK_CIRC', title: '◌̂ (dead)' },
  KC_RCBR: { name: '^', alias: 'DK_CIRC', title: '◌̂ (dead)' },
  // Row 3
  'S(KC_NUHS)': { name: '*', alias: 'DK_ASTR', title: '*' },
  // Row 4
  'S(KC_NUBS)': { name: '>', alias: 'DK_RABK', title: '>' },
  'S(KC_COMM)': { name: ';', alias: 'DK_SCLN', title: ';' },
  KC_LT: { name: ';', alias: 'DK_SCLN', title: ';' },
  'S(KC_DOT)': { name: ':', alias: 'DK_COLN', title: ':' },
  KC_GT: { name: ':', alias: 'DK_COLN', title: ':' },
  'S(KC_SLSH)': { name: '_', alias: 'DK_UNDS', title: '_' },
  KC_QUES: { name: '_', alias: 'DK_UNDS', title: '_' },

  /* AltGr symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │   │   │ @ │ £ │ $ │ € │   │ { │ [ │ ] │ } │   │ | │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │   │   │   │   │   │   │   │   │   │   │   │ ~ │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │   │   │   │   │   │   │   │   │   │   │   │   │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │ \ │   │   │   │   │   │   │ µ │   │   │   │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  'ALGR(KC_2)': { name: '@', alias: 'DK_AT', title: '@' },
  'ALGR(KC_3)': { name: '£', alias: 'DK_PND', title: '£' },
  'ALGR(KC_4)': { name: '$', alias: 'DK_DLR', title: '$' },
  'ALGR(KC_5)': { name: '€', alias: 'DK_EURO', title: '€' },
  'ALGR(KC_7)': { name: '{', alias: 'DK_LCBR', title: '{' },
  'ALGR(KC_8)': { name: '[', alias: 'DK_LBRC', title: '[' },
  'ALGR(KC_9)': { name: ']', alias: 'DK_RBRC', title: ']' },
  'ALGR(KC_0)': { name: '}', alias: 'DK_RCBR', title: '}' },
  'ALGR(KC_EQL)': { name: '|', alias: 'DK_PIPE', title: '|' },
  // Row 2
  'ALGR(KC_RBRC)': { name: '~', alias: 'DK_TILD', title: '◌̃ (dead)' },
  // Row 4
  'ALGR(KC_NUBS)': { name: '\\', alias: 'DK_BSLS', title: '\\' },
  'ALGR(KC_M)': { name: 'µ', alias: 'DK_MICR', title: 'µ' },

  /* Other keys */
  KC_BSLS: { name: "*\n'", title: "' and *" },
  'S(KC_BSLS)': { name: '*', title: '*' },
  KC_LCBR: { name: 'Å', alias: 'S(DK_ARNG)', title: 'Å' },
  KC_COLN: { name: 'Æ', alias: 'S(DK_AE)', title: 'Æ' },
  KC_PIPE: { name: '*', alias: 'DK_ASTR', title: '*' },
  KC_DQUO: { name: 'Ø', alias: 'S(DK_OSTR)', title: 'Ø' },

  SC_LSPO: { name: 'LS / )', title: 'Left Shift when held, ) when tapped' },
  SC_RSPC: { name: 'RS / =', title: 'Right Shift when held, = when tapped' },
  SC_LCPO: { name: 'LC / )', title: 'Left Control when held, ) when tapped' },
  SC_RCPC: { name: 'RC / =', title: 'Right Control when held, = when tapped' },
  SC_LAPO: { name: 'LA / )', title: 'Left Alt when held, ) when tapped' },
  SC_RAPC: { name: 'RA / =', title: 'Right Alt when held, = when tapped' },

  QK_GESC: {
    name: '½/§\nEsc',
    title: 'Esc normally, but ½ when GUI is active or § when Shift is active'
  }
};
