/* Copyright 2022 - Generated by convert_keymap_extras_header.js
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

export default {
  /*
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ ° │ 1 │ 2 │ 3 │ 4 │ 5 │ 6 │ 7 │ 8 │ 9 │ 0 │ Ö │ - │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │ Q │ W │ E │ R │ T │ Y │ U │ I │ O │ P │ Ð │ ' │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │ A │ S │ D │ F │ G │ H │ J │ K │ L │ Æ │ ´ │ + │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │ < │ Z │ X │ C │ V │ B │ N │ M │ , │ . │ Þ │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  KC_GRV: { name: '¨\n°', alias: 'IS_RNGA', title: '◌̊ (dead) and ◌̈ (dead)' },
  KC_1: { name: '!\n1', alias: 'IS_1', title: '1 and !' },
  KC_2: { name: '"\n2', alias: 'IS_2', title: '2 and "' },
  KC_3: { name: '#\n3', alias: 'IS_3', title: '3 and #' },
  KC_4: { name: '$\n4', alias: 'IS_4', title: '4 and $' },
  KC_5: { name: '%\n5', alias: 'IS_5', title: '5 and %' },
  KC_6: { name: '&\n6', alias: 'IS_6', title: '6 and &' },
  KC_7: { name: '/\n7', alias: 'IS_7', title: '7 and /' },
  KC_8: { name: '(\n8', alias: 'IS_8', title: '8 and (' },
  KC_9: { name: ')\n9', alias: 'IS_9', title: '9 and )' },
  KC_0: { name: '=\n0', alias: 'IS_0', title: '0 and =' },
  KC_MINS: { name: 'Ö', alias: 'IS_ODIA', title: 'ö and Ö' },
  KC_EQL: { name: '_\n-', alias: 'IS_MINS', title: '- and _' },
  // Row 2
  KC_Q: { name: 'Q', alias: 'IS_Q', title: 'q and Q' },
  KC_W: { name: 'W', alias: 'IS_W', title: 'w and W' },
  KC_E: { name: 'E', alias: 'IS_E', title: 'e and E' },
  KC_R: { name: 'R', alias: 'IS_R', title: 'r and R' },
  KC_T: { name: 'T', alias: 'IS_T', title: 't and T' },
  KC_Y: { name: 'Y', alias: 'IS_Y', title: 'y and Y' },
  KC_U: { name: 'U', alias: 'IS_U', title: 'u and U' },
  KC_I: { name: 'I', alias: 'IS_I', title: 'i and I' },
  KC_O: { name: 'O', alias: 'IS_O', title: 'o and O' },
  KC_P: { name: 'P', alias: 'IS_P', title: 'p and P' },
  KC_LBRC: { name: 'Ð', alias: 'IS_ETH', title: 'ð and Ð' },
  KC_RBRC: { name: "?\n'", alias: 'IS_QUOT', title: "' and ?" },
  // Row 3
  KC_A: { name: 'A', alias: 'IS_A', title: 'a and A' },
  KC_S: { name: 'S', alias: 'IS_S', title: 's and S' },
  KC_D: { name: 'D', alias: 'IS_D', title: 'd and D' },
  KC_F: { name: 'F', alias: 'IS_F', title: 'f and F' },
  KC_G: { name: 'G', alias: 'IS_G', title: 'g and G' },
  KC_H: { name: 'H', alias: 'IS_H', title: 'h and H' },
  KC_J: { name: 'J', alias: 'IS_J', title: 'j and J' },
  KC_K: { name: 'K', alias: 'IS_K', title: 'k and K' },
  KC_L: { name: 'L', alias: 'IS_L', title: 'l and L' },
  KC_SCLN: { name: 'Æ', alias: 'IS_AE', title: 'æ and Æ' },
  KC_QUOT: { name: '´', alias: 'IS_ACUT', title: '◌́ (dead)' },
  KC_NUHS: { name: '*\n+', alias: 'IS_PLUS', title: '+ and *' },
  // Row 4
  KC_NUBS: { name: '>\n<', alias: 'IS_LABK', title: '< and >' },
  KC_Z: { name: 'Z', alias: 'IS_Z', title: 'z and Z' },
  KC_X: { name: 'X', alias: 'IS_X', title: 'x and X' },
  KC_C: { name: 'C', alias: 'IS_C', title: 'c and C' },
  KC_V: { name: 'V', alias: 'IS_V', title: 'v and V' },
  KC_B: { name: 'B', alias: 'IS_B', title: 'b and B' },
  KC_N: { name: 'N', alias: 'IS_N', title: 'n and N' },
  KC_M: { name: 'M', alias: 'IS_M', title: 'm and M' },
  KC_COMM: { name: ';\n,', alias: 'IS_COMM', title: ', and ;' },
  KC_DOT: { name: ':\n.', alias: 'IS_DOT', title: '. and :' },
  KC_SLSH: { name: 'Þ', alias: 'IS_THRN', title: 'þ and Þ' },

  /* Shifted symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ ¨ │ ! │ " │ # │ $ │ % │ & │ / │ ( │ ) │ = │   │ _ │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │   │   │   │   │   │   │   │   │   │   │   │ ? │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │   │   │   │   │   │   │   │   │   │   │   │ * │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │ > │   │   │   │   │   │   │   │ ; │ : │   │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  'S(KC_GRV)': { name: '¨', alias: 'IS_DIAE', title: '◌̈ (dead)' },
  KC_TILD: { name: '¨', alias: 'IS_DIAE', title: '◌̈ (dead)' },
  'S(KC_1)': { name: '!', alias: 'IS_EXLM', title: '!' },
  KC_EXLM: { name: '!', alias: 'IS_EXLM', title: '!' },
  'S(KC_2)': { name: '"', alias: 'IS_DQUO', title: '"' },
  KC_AT: { name: '"', alias: 'IS_DQUO', title: '"' },
  'S(KC_3)': { name: '#', alias: 'IS_HASH', title: '#' },
  KC_HASH: { name: '#', alias: 'IS_HASH', title: '#' },
  'S(KC_4)': { name: '$', alias: 'IS_DLR', title: '$' },
  KC_DLR: { name: '$', alias: 'IS_DLR', title: '$' },
  'S(KC_5)': { name: '%', alias: 'IS_PERC', title: '%' },
  KC_PERC: { name: '%', alias: 'IS_PERC', title: '%' },
  'S(KC_6)': { name: '&', alias: 'IS_AMPR', title: '&' },
  KC_CIRC: { name: '&', alias: 'IS_AMPR', title: '&' },
  'S(KC_7)': { name: '/', alias: 'IS_SLSH', title: '/' },
  KC_AMPR: { name: '/', alias: 'IS_SLSH', title: '/' },
  'S(KC_8)': { name: '(', alias: 'IS_LPRN', title: '(' },
  KC_ASTR: { name: '(', alias: 'IS_LPRN', title: '(' },
  'S(KC_9)': { name: ')', alias: 'IS_RPRN', title: ')' },
  KC_LPRN: { name: ')', alias: 'IS_RPRN', title: ')' },
  'S(KC_0)': { name: '=', alias: 'IS_EQL', title: '=' },
  KC_RPRN: { name: '=', alias: 'IS_EQL', title: '=' },
  'S(KC_EQL)': { name: '_', alias: 'IS_UNDS', title: '_' },
  KC_PLUS: { name: '_', alias: 'IS_UNDS', title: '_' },
  // Row 2
  'S(KC_RBRC)': { name: '?', alias: 'IS_QUES', title: '?' },
  KC_RCBR: { name: '?', alias: 'IS_QUES', title: '?' },
  // Row 3
  'S(KC_NUHS)': { name: '*', alias: 'IS_ASTR', title: '*' },
  // Row 4
  'S(KC_NUBS)': { name: '>', alias: 'IS_RABK', title: '>' },
  'S(KC_COMM)': { name: ';', alias: 'IS_SCLN', title: ';' },
  KC_LT: { name: ';', alias: 'IS_SCLN', title: ';' },
  'S(KC_DOT)': { name: ':', alias: 'IS_COLN', title: ':' },
  KC_GT: { name: ':', alias: 'IS_COLN', title: ':' },

  /* AltGr symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ ° │   │   │   │   │   │   │ { │ [ │ ] │ } │ \ │   │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │ @ │   │ € │   │   │   │   │   │   │   │   │ ~ │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │   │   │   │   │   │   │   │   │   │   │ ^ │ ` │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │ | │   │   │   │   │   │   │ µ │   │   │   │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  'ALGR(KC_GRV)': { name: '°', alias: 'IS_DEG', title: '°' },
  'ALGR(KC_7)': { name: '{', alias: 'IS_LCBR', title: '{' },
  'ALGR(KC_8)': { name: '[', alias: 'IS_LBRC', title: '[' },
  'ALGR(KC_9)': { name: ']', alias: 'IS_RBRC', title: ']' },
  'ALGR(KC_0)': { name: '}', alias: 'IS_RCBR', title: '}' },
  'ALGR(KC_MINS)': { name: '\\', alias: 'IS_BSLS', title: '\\' },
  // Row 2
  'ALGR(KC_Q)': { name: '@', alias: 'IS_AT', title: '@' },
  'ALGR(KC_E)': { name: '€', alias: 'IS_EURO', title: '€' },
  'ALGR(KC_RBRC)': { name: '~', alias: 'IS_TILD', title: '~' },
  // Row 3
  'ALGR(KC_QUOT)': { name: '^', alias: 'IS_CIRC', title: '◌̂ (dead)' },
  'ALGR(KC_NUHS)': { name: '`', alias: 'IS_GRV', title: '◌̀ (dead)' },
  // Row 4
  'ALGR(KC_NUBS)': { name: '|', alias: 'IS_PIPE', title: '|' },
  'ALGR(KC_M)': { name: 'µ', alias: 'IS_MICR', title: 'µ' },

  /* Other keys */
  KC_BSLS: { name: '*\n+', title: '+ and *' },
  'S(KC_BSLS)': { name: '*', title: '*' },
  KC_UNDS: { name: 'Ö', alias: 'S(IS_ODIA)', title: 'Ö' },
  KC_LCBR: { name: 'Ð', alias: 'S(IS_ETH)', title: 'Ð' },
  KC_COLN: { name: 'Æ', alias: 'S(IS_AE)', title: 'Æ' },
  KC_PIPE: { name: '*', alias: 'IS_ASTR', title: '*' },
  KC_QUES: { name: 'Þ', alias: 'S(IS_THRN)', title: 'Þ' },
  KC_DQUO: { name: '´', alias: 'S(IS_ACUT)', title: '´' },

  SC_LSPO: { name: 'LS / )', title: 'Left Shift when held, ) when tapped' },
  SC_RSPC: { name: 'RS / =', title: 'Right Shift when held, = when tapped' },
  SC_LCPO: { name: 'LC / )', title: 'Left Control when held, ) when tapped' },
  SC_RCPC: { name: 'RC / =', title: 'Right Control when held, = when tapped' },
  SC_LAPO: { name: 'LA / )', title: 'Left Alt when held, ) when tapped' },
  SC_RAPC: { name: 'RA / =', title: 'Right Alt when held, = when tapped' },

  QK_GESC: {
    name: '°/¨\nEsc',
    title: 'Esc normally, but ° when GUI is active or ¨ when Shift is active'
  }
};
