/* Copyright 2022 - Generated by convert_keymap_extras_header.js
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

export default {
  /*
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ / │ 1 │ 2 │ 3 │ 4 │ 5 │ 6 │ 7 │ 8 │ 9 │ 0 │ - │ = │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │ Q │ W │ E │ R │ T │ Y │ U │ I │ O │ P │ ^ │ Ç │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │ A │ S │ D │ F │ G │ H │ J │ K │ L │ ; │ È │ À │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │ Ù │ Z │ X │ C │ V │ B │ N │ M │ , │ . │ É │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  KC_GRV: { name: '\\\n/', alias: 'CA_SLSH', title: '/ and \\' },
  KC_1: { name: '!\n1', alias: 'CA_1', title: '1 and !' },
  KC_2: { name: '@\n2', alias: 'CA_2', title: '2 and @' },
  KC_3: { name: '#\n3', alias: 'CA_3', title: '3 and #' },
  KC_4: { name: '$\n4', alias: 'CA_4', title: '4 and $' },
  KC_5: { name: '%\n5', alias: 'CA_5', title: '5 and %' },
  KC_6: { name: '?\n6', alias: 'CA_6', title: '6 and ?' },
  KC_7: { name: '&\n7', alias: 'CA_7', title: '7 and &' },
  KC_8: { name: '*\n8', alias: 'CA_8', title: '8 and *' },
  KC_9: { name: '(\n9', alias: 'CA_9', title: '9 and (' },
  KC_0: { name: ')\n0', alias: 'CA_0', title: '0 and )' },
  KC_MINS: { name: '_\n-', alias: 'CA_MINS', title: '- and _' },
  KC_EQL: { name: '+\n=', alias: 'CA_EQL', title: '= and +' },
  // Row 2
  KC_Q: { name: 'Q', alias: 'CA_Q', title: 'q and Q' },
  KC_W: { name: 'W', alias: 'CA_W', title: 'w and W' },
  KC_E: { name: 'E', alias: 'CA_E', title: 'e and E' },
  KC_R: { name: 'R', alias: 'CA_R', title: 'r and R' },
  KC_T: { name: 'T', alias: 'CA_T', title: 't and T' },
  KC_Y: { name: 'Y', alias: 'CA_Y', title: 'y and Y' },
  KC_U: { name: 'U', alias: 'CA_U', title: 'u and U' },
  KC_I: { name: 'I', alias: 'CA_I', title: 'i and I' },
  KC_O: { name: 'O', alias: 'CA_O', title: 'o and O' },
  KC_P: { name: 'P', alias: 'CA_P', title: 'p and P' },
  KC_LBRC: { name: '¨\n^', alias: 'CA_CIRC', title: '◌̂ (dead) and ◌̈ (dead)' },
  KC_RBRC: { name: 'Ç', alias: 'CA_CCED', title: 'ç and Ç' },
  // Row 3
  KC_A: { name: 'A', alias: 'CA_A', title: 'a and A' },
  KC_S: { name: 'S', alias: 'CA_S', title: 's and S' },
  KC_D: { name: 'D', alias: 'CA_D', title: 'd and D' },
  KC_F: { name: 'F', alias: 'CA_F', title: 'f and F' },
  KC_G: { name: 'G', alias: 'CA_G', title: 'g and G' },
  KC_H: { name: 'H', alias: 'CA_H', title: 'h and H' },
  KC_J: { name: 'J', alias: 'CA_J', title: 'j and J' },
  KC_K: { name: 'K', alias: 'CA_K', title: 'k and K' },
  KC_L: { name: 'L', alias: 'CA_L', title: 'l and L' },
  KC_SCLN: { name: ':\n;', alias: 'CA_SCLN', title: '; and :' },
  KC_QUOT: { name: 'È', alias: 'CA_EGRV', title: 'è and È' },
  KC_NUHS: { name: 'À', alias: 'CA_AGRV', title: 'à and À' },
  // Row 4
  KC_NUBS: { name: 'Ù', alias: 'CA_UGRV', title: 'ù and Ù' },
  KC_Z: { name: 'Z', alias: 'CA_Z', title: 'z and Z' },
  KC_X: { name: 'X', alias: 'CA_X', title: 'x and X' },
  KC_C: { name: 'C', alias: 'CA_C', title: 'c and C' },
  KC_V: { name: 'V', alias: 'CA_V', title: 'v and V' },
  KC_B: { name: 'B', alias: 'CA_B', title: 'b and B' },
  KC_N: { name: 'N', alias: 'CA_N', title: 'n and N' },
  KC_M: { name: 'M', alias: 'CA_M', title: 'm and M' },
  KC_COMM: { name: "'\n,", alias: 'CA_COMM', title: ", and '" },
  KC_DOT: { name: '"\n.', alias: 'CA_DOT', title: '. and "' },
  KC_SLSH: { name: 'É', alias: 'CA_EACU', title: 'é and É' },

  /* Shifted symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ \ │ ! │ @ │ # │ $ │ % │ ? │ & │ * │ ( │ ) │ _ │ + │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │   │   │   │   │   │   │   │   │   │   │ ¨ │   │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │   │   │   │   │   │   │   │   │   │ : │   │   │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │   │   │   │   │   │   │   │   │ ' │ " │   │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  'S(KC_GRV)': { name: '\\', alias: 'CA_BSLS', title: '\\' },
  KC_TILD: { name: '\\', alias: 'CA_BSLS', title: '\\' },
  'S(KC_1)': { name: '!', alias: 'CA_EXLM', title: '!' },
  KC_EXLM: { name: '!', alias: 'CA_EXLM', title: '!' },
  'S(KC_2)': { name: '@', alias: 'CA_AT', title: '@' },
  KC_AT: { name: '@', alias: 'CA_AT', title: '@' },
  'S(KC_3)': { name: '#', alias: 'CA_HASH', title: '#' },
  KC_HASH: { name: '#', alias: 'CA_HASH', title: '#' },
  'S(KC_4)': { name: '$', alias: 'CA_DLR', title: '$' },
  KC_DLR: { name: '$', alias: 'CA_DLR', title: '$' },
  'S(KC_5)': { name: '%', alias: 'CA_PERC', title: '%' },
  KC_PERC: { name: '%', alias: 'CA_PERC', title: '%' },
  'S(KC_6)': { name: '?', alias: 'CA_QUES', title: '?' },
  KC_CIRC: { name: '?', alias: 'CA_QUES', title: '?' },
  'S(KC_7)': { name: '&', alias: 'CA_AMPR', title: '&' },
  KC_AMPR: { name: '&', alias: 'CA_AMPR', title: '&' },
  'S(KC_8)': { name: '*', alias: 'CA_ASTR', title: '*' },
  KC_ASTR: { name: '*', alias: 'CA_ASTR', title: '*' },
  'S(KC_9)': { name: '(', alias: 'CA_LPRN', title: '(' },
  KC_LPRN: { name: '(', alias: 'CA_LPRN', title: '(' },
  'S(KC_0)': { name: ')', alias: 'CA_RPRN', title: ')' },
  KC_RPRN: { name: ')', alias: 'CA_RPRN', title: ')' },
  'S(KC_MINS)': { name: '_', alias: 'CA_UNDS', title: '_' },
  KC_UNDS: { name: '_', alias: 'CA_UNDS', title: '_' },
  'S(KC_EQL)': { name: '+', alias: 'CA_PLUS', title: '+' },
  KC_PLUS: { name: '+', alias: 'CA_PLUS', title: '+' },
  // Row 2
  'S(KC_LBRC)': { name: '¨', alias: 'CA_DIAE', title: '◌̈ (dead)' },
  KC_LCBR: { name: '¨', alias: 'CA_DIAE', title: '◌̈ (dead)' },
  // Row 3
  'S(KC_SCLN)': { name: ':', alias: 'CA_COLN', title: ':' },
  KC_COLN: { name: ':', alias: 'CA_COLN', title: ':' },
  // Row 4
  'S(KC_COMM)': { name: "'", alias: 'CA_QUOT', title: "'" },
  KC_LT: { name: "'", alias: 'CA_QUOT', title: "'" },
  'S(KC_DOT)': { name: '"', alias: 'CA_DQUO', title: '"' },
  KC_GT: { name: '"', alias: 'CA_DQUO', title: '"' },

  /* AltGr symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ | │   │   │   │ ¤ │   │   │ { │ } │ [ │ ] │   │ ¬ │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │   │   │ € │   │   │   │   │   │   │   │ ` │ ~ │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │   │   │   │   │   │   │   │   │   │ ° │   │   │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │   │ « │ » │   │   │   │   │   │ < │ > │   │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  'ALGR(KC_GRV)': { name: '|', alias: 'CA_PIPE', title: '|' },
  'ALGR(KC_4)': { name: '¤', alias: 'CA_CURR', title: '¤' },
  'ALGR(KC_7)': { name: '{', alias: 'CA_LCBR', title: '{' },
  'ALGR(KC_8)': { name: '}', alias: 'CA_RCBR', title: '}' },
  'ALGR(KC_9)': { name: '[', alias: 'CA_LBRC', title: '[' },
  'ALGR(KC_0)': { name: ']', alias: 'CA_RBRC', title: ']' },
  'ALGR(KC_EQL)': { name: '¬', alias: 'CA_NOT', title: '¬' },
  // Row 2
  'ALGR(KC_E)': { name: '€', alias: 'CA_EURO', title: '€' },
  'ALGR(KC_LBRC)': { name: '`', alias: 'CA_GRV', title: '◌̀ (dead)' },
  'ALGR(KC_RBRC)': { name: '~', alias: 'CA_DTIL', title: '◌̃ (dead)' },
  // Row 3
  'ALGR(KC_SCLN)': { name: '°', alias: 'CA_DEG', title: '°' },
  // Row 4
  'ALGR(KC_Z)': { name: '«', alias: 'CA_LDAQ', title: '«' },
  'ALGR(KC_X)': { name: '»', alias: 'CA_RDAQ', title: '»' },
  'ALGR(KC_COMM)': { name: '<', alias: 'CA_LABK', title: '<' },
  'ALGR(KC_DOT)': { name: '>', alias: 'CA_RABK', title: '>' },

  /* Right Ctrl symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │   │ ¹ │ ² │ ³ │ ¼ │ ½ │ ¾ │   │   │   │   │   │ ¸ │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │ Ω │ Ł │ Œ │ ¶ │ Ŧ │ ← │ ↓ │ → │ Ø │ Þ │   │ ~ │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │ Æ │ ß │ Ð │   │ Ŋ │ Ħ │ Ĳ │ ĸ │ Ŀ │ ´ │   │   │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │   │   │   │ ¢ │ “ │ ” │ ŉ │ μ │ ― │ ˙ │   │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  'RCTL(KC_1)': { name: '¹', alias: 'CA_SUP1', title: '¹' },
  'RCTL(KC_2)': { name: '²', alias: 'CA_SUP2', title: '²' },
  'RCTL(KC_3)': { name: '³', alias: 'CA_SUP3', title: '³' },
  'RCTL(KC_4)': { name: '¼', alias: 'CA_QRTR', title: '¼' },
  'RCTL(KC_5)': { name: '½', alias: 'CA_HALF', title: '½' },
  'RCTL(KC_6)': { name: '¾', alias: 'CA_TQTR', title: '¾' },
  'RCTL(KC_EQL)': { name: '¸', alias: 'CA_CEDL', title: '◌̧ (dead)' },
  // Row 2
  'RCTL(KC_Q)': { name: 'Ω', alias: 'CA_OMEG', title: 'Ω' },
  'RCTL(KC_W)': { name: 'Ł', alias: 'CA_LSTR', title: 'Ł' },
  'RCTL(KC_E)': { name: 'Œ', alias: 'CA_OE', title: 'Œ' },
  'RCTL(KC_R)': { name: '¶', alias: 'CA_PARA', title: '¶' },
  'RCTL(KC_T)': { name: 'Ŧ', alias: 'CA_TSTR', title: 'Ŧ' },
  'RCTL(KC_Y)': { name: '←', alias: 'CA_LARR', title: '←' },
  'RCTL(KC_U)': { name: '↓', alias: 'CA_DARR', title: '↓' },
  'RCTL(KC_I)': { name: '→', alias: 'CA_RARR', title: '→' },
  'RCTL(KC_O)': { name: 'Ø', alias: 'CA_OSTR', title: 'Ø' },
  'RCTL(KC_P)': { name: 'Þ', alias: 'CA_THRN', title: 'Þ' },
  'RCTL(KC_RBRC)': { name: '~', alias: 'CA_TILD', title: '~' },
  // Row 3
  'RCTL(KC_A)': { name: 'Æ', alias: 'CA_AE', title: 'Æ' },
  'RCTL(KC_S)': { name: 'ß', alias: 'CA_SS', title: 'ß' },
  'RCTL(KC_D)': { name: 'Ð', alias: 'CA_ETH', title: 'Ð' },
  'RCTL(KC_G)': { name: 'Ŋ', alias: 'CA_ENG', title: 'Ŋ' },
  'RCTL(KC_H)': { name: 'Ħ', alias: 'CA_HSTR', title: 'Ħ' },
  'RCTL(KC_J)': { name: 'Ĳ', alias: 'CA_IJ', title: 'Ĳ' },
  'RCTL(KC_K)': { name: 'ĸ', alias: 'CA_KRA', title: 'ĸ' },
  'RCTL(KC_L)': { name: 'Ŀ', alias: 'CA_LMDT', title: 'Ŀ' },
  'RCTL(KC_SCLN)': { name: '´', alias: 'CA_ACUT', title: '◌́ (dead)' },
  // Row 4
  'RCTL(KC_C)': { name: '¢', alias: 'CA_CENT', title: '¢' },
  'RCTL(KC_V)': { name: '“', alias: 'CA_LDQU', title: '“' },
  'RCTL(KC_B)': { name: '”', alias: 'CA_RDQU', title: '”' },
  'RCTL(KC_N)': { name: 'ŉ', alias: 'CA_APSN', title: 'ŉ' },
  'RCTL(KC_M)': { name: 'μ', alias: 'CA_MICR', title: 'μ' },
  'RCTL(KC_COMM)': { name: '―', alias: 'CA_HRZB', title: '―' },
  'RCTL(KC_DOT)': { name: '˙', alias: 'CA_DOTA', title: '◌̇ (dead)' },

  /* Shift+Right Ctrl symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ - │ ¡ │   │ £ │   │ ⅜ │ ⅝ │ ⅞ │ ™ │ ± │   │ ¿ │ ˛ │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │   │   │   │ ® │   │ ¥ │ ↑ │ ı │   │   │ ° │ ¯ │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │   │ § │   │ ª │   │   │   │   │   │ ˝ │ ˇ │ ˘ │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │ ¦ │   │   │ © │ ‘ │ ’ │ ♪ │ º │ × │ ÷ │   │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  'RCTL(S(KC_GRV))': { name: 'SHYP', alias: 'CA_SHYP', title: 'Soft hyphen' },
  'RCTL(S(KC_1))': { name: '¡', alias: 'CA_IEXL', title: '¡' },
  'RCTL(S(KC_3))': { name: '£', alias: 'CA_PND', title: '£' },
  'RCTL(S(KC_5))': { name: '⅜', alias: 'CA_TEIG', title: '⅜' },
  'RCTL(S(KC_6))': { name: '⅝', alias: 'CA_FEIG', title: '⅝' },
  'RCTL(S(KC_7))': { name: '⅞', alias: 'CA_SEIG', title: '⅞' },
  'RCTL(S(KC_8))': { name: '™', alias: 'CA_TM', title: '™' },
  'RCTL(S(KC_9))': { name: '±', alias: 'CA_PLMN', title: '±' },
  'RCTL(S(KC_MINS))': { name: '¿', alias: 'CA_IQUE', title: '¿' },
  'RCTL(S(KC_EQL))': { name: '˛', alias: 'CA_OGON', title: '◌̨ (dead)' },
  // Row 2
  'RCTL(S(KC_R))': { name: '®', alias: 'CA_REGD', title: '®' },
  'RCTL(S(KC_Y))': { name: '¥', alias: 'CA_YEN', title: '¥' },
  'RCTL(S(KC_U))': { name: '↑', alias: 'CA_UARR', title: '↑' },
  'RCTL(S(KC_I))': { name: 'ı', alias: 'CA_DLSI', title: 'ı' },
  'RCTL(S(KC_LBRC))': { name: '°', alias: 'CA_RNGA', title: '◌̊ (dead)' },
  'RCTL(S(KC_RBRC))': { name: '¯', alias: 'CA_MACR', title: '◌̄ (dead)' },
  // Row 3
  'RCTL(S(KC_S))': { name: '§', alias: 'CA_SECT', title: '§' },
  'RCTL(S(KC_F))': { name: 'ª', alias: 'CA_FORD', title: 'ª' },
  'RCTL(S(KC_SCLN))': { name: '˝', alias: 'CA_DACU', title: '◌̋ (dead)' },
  'RCTL(S(KC_QUOT))': { name: 'ˇ', alias: 'CA_CARN', title: '◌̌ (dead)' },
  'RCTL(S(KC_NUHS))': { name: '˘', alias: 'CA_BREV', title: '◌̆ (dead)' },
  // Row 4
  'RCTL(S(KC_NUBS))': { name: '¦', alias: 'CA_BRKP', title: '¦' },
  'RCTL(S(KC_C))': { name: '©', alias: 'CA_COPY', title: '©' },
  'RCTL(S(KC_V))': { name: '‘', alias: 'CA_LSQU', title: '‘' },
  'RCTL(S(KC_B))': { name: '’', alias: 'CA_RSQU', title: '’' },
  'RCTL(S(KC_N))': { name: '♪', alias: 'CA_ENOT', title: '♪' },
  'RCTL(S(KC_M))': { name: 'º', alias: 'CA_MORD', title: 'º' },
  'RCTL(S(KC_COMM))': { name: '×', alias: 'CA_MUL', title: '×' },
  'RCTL(S(KC_DOT))': { name: '÷', alias: 'CA_DIV', title: '÷' },

  /* Other keys */
  KC_BSLS: { name: 'À', title: 'À' },
  'S(KC_BSLS)': { name: 'À', title: 'À' },
  KC_RCBR: { name: 'Ç', alias: 'S(CA_CCED)', title: 'Ç' },
  KC_PIPE: { name: 'À', alias: 'S(CA_AGRV)', title: 'À' },
  KC_QUES: { name: 'É', alias: 'S(CA_EACU)', title: 'É' },
  KC_DQUO: { name: 'É', alias: 'S(CA_EGRV)', title: 'É' },

  SC_LSPO: { name: 'LS / (', title: 'Left Shift when held, ( when tapped' },
  SC_RSPC: { name: 'RS / )', title: 'Right Shift when held, ) when tapped' },
  SC_LCPO: { name: 'LC / (', title: 'Left Control when held, ( when tapped' },
  SC_RCPC: { name: 'RC / )', title: 'Right Control when held, ) when tapped' },
  SC_LAPO: { name: 'LA / (', title: 'Left Alt when held, ( when tapped' },
  SC_RAPC: { name: 'RA / )', title: 'Right Alt when held, ) when tapped' },

  QK_GESC: {
    name: '//\\\nEsc',
    title: 'Esc normally, but / when GUI is active or \\ when Shift is active'
  }
};
