/* Copyright 2022 - Generated by convert_keymap_extras_header.js
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

export default {
  /*
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ „ │ 1 │ 2 │ 3 │ 4 │ 5 │ 6 │ 7 │ 8 │ 9 │ 0 │ - │ = │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │ Q │ W │ E │ R │ T │ Y │ U │ I │ O │ P │ Ă │ Î │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │ A │ S │ D │ F │ G │ H │ J │ K │ L │ Ș │ Ț │ Â │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │ \ │ Z │ X │ C │ V │ B │ N │ M │ , │ . │ / │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  KC_GRV: { name: '”\n„', alias: 'RO_DLQU', title: '„ and ”' },
  KC_1: { name: '!\n1', alias: 'RO_1', title: '1 and !' },
  KC_2: { name: '@\n2', alias: 'RO_2', title: '2 and @' },
  KC_3: { name: '#\n3', alias: 'RO_3', title: '3 and #' },
  KC_4: { name: '$\n4', alias: 'RO_4', title: '4 and $' },
  KC_5: { name: '%\n5', alias: 'RO_5', title: '5 and %' },
  KC_6: { name: '^\n6', alias: 'RO_6', title: '6 and ^' },
  KC_7: { name: '&\n7', alias: 'RO_7', title: '7 and &' },
  KC_8: { name: '*\n8', alias: 'RO_8', title: '8 and *' },
  KC_9: { name: '(\n9', alias: 'RO_9', title: '9 and (' },
  KC_0: { name: ')\n0', alias: 'RO_0', title: '0 and )' },
  KC_MINS: { name: '_\n-', alias: 'RO_MINS', title: '- and _' },
  KC_EQL: { name: '+\n=', alias: 'RO_EQL', title: '= and +' },
  // Row 2
  KC_Q: { name: 'Q', alias: 'RO_Q', title: 'q and Q' },
  KC_W: { name: 'W', alias: 'RO_W', title: 'w and W' },
  KC_E: { name: 'E', alias: 'RO_E', title: 'e and E' },
  KC_R: { name: 'R', alias: 'RO_R', title: 'r and R' },
  KC_T: { name: 'T', alias: 'RO_T', title: 't and T' },
  KC_Y: { name: 'Y', alias: 'RO_Y', title: 'y and Y' },
  KC_U: { name: 'U', alias: 'RO_U', title: 'u and U' },
  KC_I: { name: 'I', alias: 'RO_I', title: 'i and I' },
  KC_O: { name: 'O', alias: 'RO_O', title: 'o and O' },
  KC_P: { name: 'P', alias: 'RO_P', title: 'p and P' },
  KC_LBRC: { name: 'Ă', alias: 'RO_ABRV', title: 'ă and Ă' },
  KC_RBRC: { name: 'Î', alias: 'RO_ICIR', title: 'î and Î' },
  // Row 3
  KC_A: { name: 'A', alias: 'RO_A', title: 'a and A' },
  KC_S: { name: 'S', alias: 'RO_S', title: 's and S' },
  KC_D: { name: 'D', alias: 'RO_D', title: 'd and D' },
  KC_F: { name: 'F', alias: 'RO_F', title: 'f and F' },
  KC_G: { name: 'G', alias: 'RO_G', title: 'g and G' },
  KC_H: { name: 'H', alias: 'RO_H', title: 'h and H' },
  KC_J: { name: 'J', alias: 'RO_J', title: 'j and J' },
  KC_K: { name: 'K', alias: 'RO_K', title: 'k and K' },
  KC_L: { name: 'L', alias: 'RO_L', title: 'l and L' },
  KC_SCLN: { name: 'Ș', alias: 'RO_SCOM', title: 'ș and Ș' },
  KC_QUOT: { name: 'Ț', alias: 'RO_TCOM', title: 'ț and Ț' },
  KC_NUHS: { name: 'Â', alias: 'RO_ACIR', title: 'â and Â' },
  // Row 4
  KC_NUBS: { name: '|\n\\', alias: 'RO_BSLS', title: '\\ and |' },
  KC_Z: { name: 'Z', alias: 'RO_Z', title: 'z and Z' },
  KC_X: { name: 'X', alias: 'RO_X', title: 'x and X' },
  KC_C: { name: 'C', alias: 'RO_C', title: 'c and C' },
  KC_V: { name: 'V', alias: 'RO_V', title: 'v and V' },
  KC_B: { name: 'B', alias: 'RO_B', title: 'b and B' },
  KC_N: { name: 'N', alias: 'RO_N', title: 'n and N' },
  KC_M: { name: 'M', alias: 'RO_M', title: 'm and M' },
  KC_COMM: { name: ';\n,', alias: 'RO_COMM', title: ', and ;' },
  KC_DOT: { name: ':\n.', alias: 'RO_DOT', title: '. and :' },
  KC_SLSH: { name: '?\n/', alias: 'RO_SLSH', title: '/ and ?' },

  /* Shifted symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ ” │ ! │ @ │ # │ $ │ % │ ^ │ & │ * │ ( │ ) │ _ │ + │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │   │   │   │   │   │   │   │   │   │   │   │   │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │   │   │   │   │   │   │   │   │   │   │   │   │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │ | │   │   │   │   │   │   │   │ ; │ : │ ? │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  'S(KC_GRV)': { name: '”', alias: 'RO_RDQU', title: '”' },
  KC_TILD: { name: '”', alias: 'RO_RDQU', title: '”' },
  'S(KC_1)': { name: '!', alias: 'RO_EXLM', title: '!' },
  KC_EXLM: { name: '!', alias: 'RO_EXLM', title: '!' },
  'S(KC_2)': { name: '@', alias: 'RO_AT', title: '@' },
  KC_AT: { name: '@', alias: 'RO_AT', title: '@' },
  'S(KC_3)': { name: '#', alias: 'RO_HASH', title: '#' },
  KC_HASH: { name: '#', alias: 'RO_HASH', title: '#' },
  'S(KC_4)': { name: '$', alias: 'RO_DLR', title: '$' },
  KC_DLR: { name: '$', alias: 'RO_DLR', title: '$' },
  'S(KC_5)': { name: '%', alias: 'RO_PERC', title: '%' },
  KC_PERC: { name: '%', alias: 'RO_PERC', title: '%' },
  'S(KC_6)': { name: '^', alias: 'RO_CIRC', title: '^' },
  KC_CIRC: { name: '^', alias: 'RO_CIRC', title: '^' },
  'S(KC_7)': { name: '&', alias: 'RO_AMPR', title: '&' },
  KC_AMPR: { name: '&', alias: 'RO_AMPR', title: '&' },
  'S(KC_8)': { name: '*', alias: 'RO_ASTR', title: '*' },
  KC_ASTR: { name: '*', alias: 'RO_ASTR', title: '*' },
  'S(KC_9)': { name: '(', alias: 'RO_LPRN', title: '(' },
  KC_LPRN: { name: '(', alias: 'RO_LPRN', title: '(' },
  'S(KC_0)': { name: ')', alias: 'RO_RPRN', title: ')' },
  KC_RPRN: { name: ')', alias: 'RO_RPRN', title: ')' },
  'S(KC_MINS)': { name: '_', alias: 'RO_UNDS', title: '_' },
  KC_UNDS: { name: '_', alias: 'RO_UNDS', title: '_' },
  'S(KC_EQL)': { name: '+', alias: 'RO_PLUS', title: '+' },
  KC_PLUS: { name: '+', alias: 'RO_PLUS', title: '+' },
  // Row 4
  'S(KC_NUBS)': { name: '|', alias: 'RO_PIPE', title: '|' },
  'S(KC_COMM)': { name: ';', alias: 'RO_SCLN', title: ';' },
  KC_LT: { name: ';', alias: 'RO_SCLN', title: ';' },
  'S(KC_DOT)': { name: ':', alias: 'RO_COLN', title: ':' },
  KC_GT: { name: ':', alias: 'RO_COLN', title: ':' },
  'S(KC_SLSH)': { name: '?', alias: 'RO_QUES', title: '?' },
  KC_QUES: { name: '?', alias: 'RO_QUES', title: '?' },

  /* AltGr symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ ` │ ~ │ ˇ │ ^ │ ˘ │ ° │ ˛ │ ` │ ˙ │ ´ │ ˝ │ ¨ │ ¸ │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │   │   │ € │   │   │   │   │   │   │ § │ [ │ ] │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │   │ ß │ Đ │   │   │   │   │   │ Ł │   │ ' │   │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │   │   │   │ © │   │   │   │   │ < │ > │   │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  'ALGR(KC_GRV)': { name: '`', alias: 'RO_GRV', title: '`' },
  'ALGR(KC_1)': { name: '~', alias: 'RO_DTIL', title: '◌̃ (dead)' },
  'ALGR(KC_2)': { name: 'ˇ', alias: 'RO_CARN', title: '◌̌ (dead)' },
  'ALGR(KC_3)': { name: '^', alias: 'RO_DCIR', title: '◌̂ (dead)' },
  'ALGR(KC_4)': { name: '˘', alias: 'RO_BREV', title: '◌̆ (dead)' },
  'ALGR(KC_5)': { name: '°', alias: 'RO_RNGA', title: '◌̊ (dead)' },
  'ALGR(KC_6)': { name: '˛', alias: 'RO_OGON', title: '◌̨ (dead)' },
  'ALGR(KC_7)': { name: '`', alias: 'RO_DGRV', title: '◌̀ (dead)' },
  'ALGR(KC_8)': { name: '˙', alias: 'RO_DOTA', title: '◌̇ (dead)' },
  'ALGR(KC_9)': { name: '´', alias: 'RO_ACUT', title: '◌́ (dead)' },
  'ALGR(KC_0)': { name: '˝', alias: 'RO_DACU', title: '◌̋ (dead)' },
  'ALGR(KC_MINS)': { name: '¨', alias: 'RO_DIAE', title: '◌̈ (dead)' },
  'ALGR(KC_EQL)': { name: '¸', alias: 'RO_CEDL', title: '◌̧ (dead)' },
  // Row 2
  'ALGR(KC_E)': { name: '€', alias: 'RO_EURO', title: '€' },
  'ALGR(KC_P)': { name: '§', alias: 'RO_SECT', title: '§' },
  'ALGR(KC_LBRC)': { name: '[', alias: 'RO_LBRC', title: '[' },
  'ALGR(KC_RBRC)': { name: ']', alias: 'RO_RBRC', title: ']' },
  // Row 3
  'ALGR(KC_S)': { name: 'ß', alias: 'RO_SS', title: 'ß' },
  'ALGR(KC_D)': { name: 'Đ', alias: 'RO_DSTR', title: 'Đ' },
  'ALGR(KC_L)': { name: 'Ł', alias: 'RO_LSTR', title: 'Ł' },
  'ALGR(KC_QUOT)': { name: "'", alias: 'RO_QUOT', title: "'" },
  // Row 4
  'ALGR(KC_C)': { name: '©', alias: 'RO_COPY', title: '©' },
  'ALGR(KC_COMM)': { name: '<', alias: 'RO_LABK', title: '<' },
  'ALGR(KC_DOT)': { name: '>', alias: 'RO_RABK', title: '>' },

  /* Shift+AltGr symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ ~ │   │   │   │   │   │   │   │   │   │   │ – │ ± │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │   │   │   │   │   │   │   │   │   │   │ { │ } │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │   │   │   │   │   │   │   │   │   │   │ " │   │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │   │   │   │   │   │   │   │   │ « │ » │   │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  'S(ALGR(KC_GRV))': { name: '~', alias: 'RO_TILD', title: '~' },
  'S(ALGR(KC_MINS))': { name: '–', alias: 'RO_NDSH', title: '–' },
  'S(ALGR(KC_EQL))': { name: '±', alias: 'RO_PLMN', title: '±' },
  // Row 2
  'S(ALGR(KC_LBRC))': { name: '{', alias: 'RO_LCBR', title: '{' },
  'S(ALGR(KC_RBRC))': { name: '}', alias: 'RO_RCBR', title: '}' },
  // Row 3
  'S(ALGR(KC_QUOT))': { name: '"', alias: 'RO_DQUO', title: '"' },
  // Row 4
  'S(ALGR(KC_COMM))': { name: '«', alias: 'RO_LDAQ', title: '«' },
  'S(ALGR(KC_DOT))': { name: '»', alias: 'RO_RDAQ', title: '»' },

  /* Other keys */
  KC_BSLS: { name: 'Â', title: 'Â' },
  'S(KC_BSLS)': { name: 'Â', title: 'Â' },
  KC_LCBR: { name: 'Ă', alias: 'S(RO_ABRV)', title: 'Ă' },
  KC_RCBR: { name: 'Î', alias: 'S(RO_ICIR)', title: 'Î' },
  KC_COLN: { name: 'Ș', alias: 'S(RO_SCOM)', title: 'Ș' },
  KC_PIPE: { name: 'Â', alias: 'RO_ACIR', title: 'Â' },
  KC_DQUO: { name: 'Ț', alias: 'S(RO_TCOM)', title: 'Ț' },

  SC_LSPO: { name: 'LS / (', title: 'Left Shift when held, ( when tapped' },
  SC_RSPC: { name: 'RS / )', title: 'Right Shift when held, ) when tapped' },
  SC_LCPO: { name: 'LC / (', title: 'Left Control when held, ( when tapped' },
  SC_RCPC: { name: 'RC / )', title: 'Right Control when held, ) when tapped' },
  SC_LAPO: { name: 'LA / (', title: 'Left Alt when held, ( when tapped' },
  SC_RAPC: { name: 'RA / )', title: 'Right Alt when held, ) when tapped' },

  QK_GESC: {
    name: '„/”\nEsc',
    title: 'Esc normally, but „ when GUI is active or ” when Shift is active'
  }
};
