/* Copyright 2022 - Generated by convert_keymap_extras_header.js
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

export default {
  /*
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ ; │ + │ ľ │ š │ č │ ť │ ž │ ý │ á │ í │ é │ = │ ´ │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │ Q │ W │ E │ R │ T │ Z │ U │ I │ O │ P │ ú │ ä │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │ A │ S │ D │ F │ G │ H │ J │ K │ L │ ô │ § │ ň │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │ & │ Y │ X │ C │ V │ B │ N │ M │ , │ . │ - │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  KC_GRV: { name: '°\n;', alias: 'SK_SCLN', title: '; and ◌̊ (dead)' },
  KC_1: { name: '1\n+', alias: 'SK_PLUS', title: '+ and 1' },
  KC_2: { name: '2\nľ', alias: 'SK_LCAR', title: 'ľ and 2' },
  KC_3: { name: '3\nš', alias: 'SK_SCAR', title: 'š and 3' },
  KC_4: { name: '4\nč', alias: 'SK_CCAR', title: 'č and 4' },
  KC_5: { name: '5\nť', alias: 'SK_TCAR', title: 'ť and 5' },
  KC_6: { name: '6\nž', alias: 'SK_ZCAR', title: 'ž and 6' },
  KC_7: { name: '7\ný', alias: 'SK_YACU', title: 'ý and 7' },
  KC_8: { name: '8\ná', alias: 'SK_AACU', title: 'á and 8' },
  KC_9: { name: '9\ní', alias: 'SK_IACU', title: 'í and 9' },
  KC_0: { name: '0\né', alias: 'SK_EACU', title: 'é and 0' },
  KC_MINS: { name: '%\n=', alias: 'SK_EQL', title: '= and %' },
  KC_EQL: { name: 'ˇ\n´', alias: 'SK_ACUT', title: '◌́ (dead) and ◌̌ (dead)' },
  // Row 2
  KC_Q: { name: 'Q', alias: 'SK_Q', title: 'q and Q' },
  KC_W: { name: 'W', alias: 'SK_W', title: 'w and W' },
  KC_E: { name: 'E', alias: 'SK_E', title: 'e and E' },
  KC_R: { name: 'R', alias: 'SK_R', title: 'r and R' },
  KC_T: { name: 'T', alias: 'SK_T', title: 't and T' },
  KC_Y: { name: 'Z', alias: 'SK_Z', title: 'z and Z' },
  KC_U: { name: 'U', alias: 'SK_U', title: 'u and U' },
  KC_I: { name: 'I', alias: 'SK_I', title: 'i and I' },
  KC_O: { name: 'O', alias: 'SK_O', title: 'o and O' },
  KC_P: { name: 'P', alias: 'SK_P', title: 'p and P' },
  KC_LBRC: { name: '/\nú', alias: 'SK_UACU', title: 'ú and /' },
  KC_RBRC: { name: '(\nä', alias: 'SK_ADIA', title: 'ä and (' },
  // Row 3
  KC_A: { name: 'A', alias: 'SK_A', title: 'a and A' },
  KC_S: { name: 'S', alias: 'SK_S', title: 's and S' },
  KC_D: { name: 'D', alias: 'SK_D', title: 'd and D' },
  KC_F: { name: 'F', alias: 'SK_F', title: 'f and F' },
  KC_G: { name: 'G', alias: 'SK_G', title: 'g and G' },
  KC_H: { name: 'H', alias: 'SK_H', title: 'h and H' },
  KC_J: { name: 'J', alias: 'SK_J', title: 'j and J' },
  KC_K: { name: 'K', alias: 'SK_K', title: 'k and K' },
  KC_L: { name: 'L', alias: 'SK_L', title: 'l and L' },
  KC_SCLN: { name: '"\nô', alias: 'SK_OCIR', title: 'ô and "' },
  KC_QUOT: { name: '!\n§', alias: 'SK_SECT', title: '§ and !' },
  KC_NUHS: { name: ')\nň', alias: 'SK_NCAR', title: 'ň and )' },
  // Row 4
  KC_NUBS: { name: '*\n&', alias: 'SK_AMPR', title: '& and *' },
  KC_Z: { name: 'Y', alias: 'SK_Y', title: 'y and Y' },
  KC_X: { name: 'X', alias: 'SK_X', title: 'x and X' },
  KC_C: { name: 'C', alias: 'SK_C', title: 'c and C' },
  KC_V: { name: 'V', alias: 'SK_V', title: 'v and V' },
  KC_B: { name: 'B', alias: 'SK_B', title: 'b and B' },
  KC_N: { name: 'N', alias: 'SK_N', title: 'n and N' },
  KC_M: { name: 'M', alias: 'SK_M', title: 'm and M' },
  KC_COMM: { name: '?\n,', alias: 'SK_COMM', title: ', and ?' },
  KC_DOT: { name: ':\n.', alias: 'SK_DOT', title: '. and :' },
  KC_SLSH: { name: '_\n-', alias: 'SK_MINS', title: '- and _' },

  /* Shifted symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ ° │ 1 │ 2 │ 3 │ 4 │ 5 │ 6 │ 7 │ 8 │ 9 │ 0 │ % │ ˇ │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │   │   │   │   │   │   │   │   │   │   │ / │ ( │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │   │   │   │   │   │   │   │   │   │ " │ ! │ ) │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │ * │   │   │   │   │   │   │   │ ? │ : │ _ │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  'S(KC_GRV)': { name: '°', alias: 'SK_RNGA', title: '◌̊ (dead)' },
  KC_TILD: { name: '°', alias: 'SK_RNGA', title: '◌̊ (dead)' },
  'S(KC_1)': { name: '1', alias: 'SK_1', title: '1' },
  KC_EXLM: { name: '1', alias: 'SK_1', title: '1' },
  'S(KC_2)': { name: '2', alias: 'SK_2', title: '2' },
  KC_AT: { name: '2', alias: 'SK_2', title: '2' },
  'S(KC_3)': { name: '3', alias: 'SK_3', title: '3' },
  KC_HASH: { name: '3', alias: 'SK_3', title: '3' },
  'S(KC_4)': { name: '4', alias: 'SK_4', title: '4' },
  KC_DLR: { name: '4', alias: 'SK_4', title: '4' },
  'S(KC_5)': { name: '5', alias: 'SK_5', title: '5' },
  KC_PERC: { name: '5', alias: 'SK_5', title: '5' },
  'S(KC_6)': { name: '6', alias: 'SK_6', title: '6' },
  KC_CIRC: { name: '6', alias: 'SK_6', title: '6' },
  'S(KC_7)': { name: '7', alias: 'SK_7', title: '7' },
  KC_AMPR: { name: '7', alias: 'SK_7', title: '7' },
  'S(KC_8)': { name: '8', alias: 'SK_8', title: '8' },
  KC_ASTR: { name: '8', alias: 'SK_8', title: '8' },
  'S(KC_9)': { name: '9', alias: 'SK_9', title: '9' },
  KC_LPRN: { name: '9', alias: 'SK_9', title: '9' },
  'S(KC_0)': { name: '0', alias: 'SK_0', title: '0' },
  KC_RPRN: { name: '0', alias: 'SK_0', title: '0' },
  'S(KC_MINS)': { name: '%', alias: 'SK_PERC', title: '%' },
  KC_UNDS: { name: '%', alias: 'SK_PERC', title: '%' },
  'S(KC_EQL)': { name: 'ˇ', alias: 'SK_CARN', title: '◌̌ (dead)' },
  KC_PLUS: { name: 'ˇ', alias: 'SK_CARN', title: '◌̌ (dead)' },
  // Row 2
  'S(KC_LBRC)': { name: '/', alias: 'SK_SLSH', title: '/' },
  KC_LCBR: { name: '/', alias: 'SK_SLSH', title: '/' },
  'S(KC_RBRC)': { name: '(', alias: 'SK_LPRN', title: '(' },
  KC_RCBR: { name: '(', alias: 'SK_LPRN', title: '(' },
  // Row 3
  'S(KC_SCLN)': { name: '"', alias: 'SK_DQUO', title: '"' },
  KC_COLN: { name: '"', alias: 'SK_DQUO', title: '"' },
  'S(KC_QUOT)': { name: '!', alias: 'SK_EXLM', title: '!' },
  KC_DQUO: { name: '!', alias: 'SK_EXLM', title: '!' },
  'S(KC_NUHS)': { name: ')', alias: 'SK_RPRN', title: ')' },
  // Row 4
  'S(KC_NUBS)': { name: '*', alias: 'SK_ASTR', title: '*' },
  'S(KC_COMM)': { name: '?', alias: 'SK_QUES', title: '?' },
  KC_LT: { name: '?', alias: 'SK_QUES', title: '?' },
  'S(KC_DOT)': { name: ':', alias: 'SK_COLN', title: ':' },
  KC_GT: { name: ':', alias: 'SK_COLN', title: ':' },
  'S(KC_SLSH)': { name: '_', alias: 'SK_UNDS', title: '_' },
  KC_QUES: { name: '_', alias: 'SK_UNDS', title: '_' },

  /* AltGr symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │   │ ~ │   │ ^ │ ˘ │ ° │ ˛ │ ` │ ˙ │   │ ˝ │ ¨ │ ¸ │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │ \ │ | │ € │   │   │   │   │   │   │ ' │ ÷ │ × │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │   │ đ │ Đ │ [ │ ] │   │   │ ł │ Ł │ $ │ ß │ ¤ │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │ < │ > │ # │   │ @ │ { │ } │   │   │   │   │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  'ALGR(KC_1)': { name: '~', alias: 'SK_TILD', title: '~' },
  'ALGR(KC_3)': { name: '^', alias: 'SK_CIRC', title: '◌̂ (dead)' },
  'ALGR(KC_4)': { name: '˘', alias: 'SK_BREV', title: '◌̆ (dead)' },
  'ALGR(KC_5)': { name: '˛', alias: 'SK_OGON', title: '◌̨ (dead)' },
  'ALGR(KC_6)': { name: '`', alias: 'SK_GRV', title: '`' },
  'ALGR(KC_7)': { name: '˙', alias: 'SK_DOTA', title: '◌̇ (dead)' },
  'ALGR(KC_0)': { name: '˝', alias: 'SK_DACU', title: '◌̋ (dead)' },
  'ALGR(KC_MINS)': { name: '¨', alias: 'SK_DIAE', title: '◌̈ (dead)' },
  'ALGR(KC_EQL)': { name: '¸', alias: 'SK_CEDL', title: '◌̧ (dead)' },
  // Row 2
  'ALGR(KC_Q)': { name: '\\', alias: 'SK_BSLS', title: '\\' },
  'ALGR(KC_W)': { name: '|', alias: 'SK_PIPE', title: '|' },
  'ALGR(KC_E)': { name: '€', alias: 'SK_EURO', title: '€' },
  'ALGR(KC_P)': { name: "'", alias: 'SK_QUOT', title: "'" },
  'ALGR(KC_LBRC)': { name: '÷', alias: 'SK_DIV', title: '÷' },
  'ALGR(KC_RBRC)': { name: '×', alias: 'SK_MUL', title: '×' },
  // Row 3
  'ALGR(KC_S)': { name: 'đ', alias: 'SK_LDST', title: 'đ' },
  'ALGR(KC_D)': { name: 'Đ', alias: 'SK_CDST', title: 'Đ' },
  'ALGR(KC_F)': { name: '[', alias: 'SK_LBRC', title: '[' },
  'ALGR(KC_G)': { name: ']', alias: 'SK_RBRC', title: ']' },
  'ALGR(KC_K)': { name: 'ł', alias: 'SK_LLST', title: 'ł' },
  'ALGR(KC_L)': { name: 'Ł', alias: 'SK_CLST', title: 'Ł' },
  'ALGR(KC_SCLN)': { name: '$', alias: 'SK_DLR', title: '$' },
  'ALGR(KC_QUOT)': { name: 'ß', alias: 'SK_SS', title: 'ß' },
  'ALGR(KC_NUHS)': { name: '¤', alias: 'SK_CURR', title: '¤' },
  // Row 4
  'ALGR(KC_NUBS)': { name: '<', alias: 'SK_LABK', title: '<' },
  'ALGR(KC_Z)': { name: '>', alias: 'SK_RABK', title: '>' },
  'ALGR(KC_X)': { name: '#', alias: 'SK_HASH', title: '#' },
  'ALGR(KC_V)': { name: '@', alias: 'SK_AT', title: '@' },
  'ALGR(KC_B)': { name: '{', alias: 'SK_LCBR', title: '{' },
  'ALGR(KC_N)': { name: '}', alias: 'SK_RCBR', title: '}' },

  /* Other keys */
  KC_BSLS: { name: ')\nň', title: 'ň and )' },
  'S(KC_BSLS)': { name: ')', title: ')' },
  KC_PIPE: { name: ')', alias: 'SK_RPRN', title: ')' },

  SC_LSPO: { name: 'LS / 9', title: 'Left Shift when held, 9 when tapped' },
  SC_RSPC: { name: 'RS / 0', title: 'Right Shift when held, 0 when tapped' },
  SC_LCPO: { name: 'LC / 9', title: 'Left Control when held, 9 when tapped' },
  SC_RCPC: { name: 'RC / 0', title: 'Right Control when held, 0 when tapped' },
  SC_LAPO: { name: 'LA / 9', title: 'Left Alt when held, 9 when tapped' },
  SC_RAPC: { name: 'RA / 0', title: 'Right Alt when held, 0 when tapped' },

  QK_GESC: {
    name: ';/°\nEsc',
    title: 'Esc normally, but ; when GUI is active or ° when Shift is active'
  }
};
