export const fullKeyboardMatrixKeycodes = [
  // Row 0
  'KC_ESCAPE',
  'KC_F1',
  'KC_F2',
  'KC_F3',
  'KC_F4',
  'KC_F5',
  'KC_F6',
  'KC_F7',
  'KC_F8',
  'KC_F9',
  'KC_F10',
  'KC_F11',
  'KC_F12',
  'KC_PRINT_SCREEN',
  'KC_SCROLL_LOCK',
  'KC_PAUSE',
  'KC_F13',
  'KC_AUDIO_MUTE',
  'KC_AUDIO_VOL_DOWN',
  'KC_AUDIO_VOL_UP',
  // Row 1
  'KC_GRAVE',
  'KC_1',
  'KC_2',
  'KC_3',
  'KC_4',
  'KC_5',
  'KC_6',
  'KC_7',
  'KC_8',
  'KC_9',
  'KC_0',
  'KC_MINUS',
  'KC_EQUAL',
  'KC_BACKSPACE',
  'KC_INSERT',
  'KC_HOME',
  'KC_PAGE_UP',
  'KC_NUM_LOCK',
  'KC_KP_SLASH',
  'KC_KP_ASTERISK',
  'KC_KP_MINUS',
  // Row 2
  'KC_TAB',
  'KC_Q',
  'KC_W',
  'KC_E',
  'KC_R',
  'KC_T',
  'KC_Y',
  'KC_U',
  'KC_I',
  'KC_O',
  'KC_P',
  'KC_LEFT_BRACKET',
  'KC_RIGHT_BRACKET',
  'KC_BACKSLASH',
  'KC_DELETE',
  'KC_END',
  'KC_PAGE_DOWN',
  'KC_KP_7',
  'KC_KP_8',
  'KC_KP_9',
  'KC_KP_PLUS',
  // Row 3
  'KC_CAPS_LOCK',
  'KC_A',
  'KC_S',
  'KC_D',
  'KC_F',
  'KC_G',
  'KC_H',
  'KC_J',
  'KC_K',
  'KC_L',
  'KC_SEMICOLON',
  'KC_QUOTE',
  'KC_ENTER',
  'KC_KP_4',
  'KC_KP_5',
  'KC_KP_6',
  // Row 4
  'KC_LEFT_SHIFT',
  'KC_Z',
  'KC_X',
  'KC_C',
  'KC_V',
  'KC_B',
  'KC_N',
  'KC_M',
  'KC_COMMA',
  'KC_DOT',
  'KC_SLASH',
  'KC_RIGHT_SHIFT',
  'KC_UP',
  'KC_KP_1',
  'KC_KP_2',
  'KC_KP_3',
  'KC_KP_ENTER',
  // Row 5
  'KC_LEFT_CTRL',
  'KC_LEFT_GUI',
  'KC_LEFT_ALT',
  'KC_SPACE',
  'KC_RIGHT_ALT',
  'KC_RIGHT_GUI',
  'KC_APPLICATION',
  'KC_RIGHT_CTRL',
  'KC_LEFT',
  'KC_DOWN',
  'KC_RIGHT',
  'KC_KP_0',
  'KC_KP_DOT',
];

const keyboardEventToKeycode: Record<string, string> = {
  Digit1: 'KC_1',
  Digit2: 'KC_2',
  Digit3: 'KC_3',
  Digit4: 'KC_4',
  Digit5: 'KC_5',
  Digit6: 'KC_6',
  Digit7: 'KC_7',
  Digit8: 'KC_8',
  Digit9: 'KC_9',
  Digit0: 'KC_0',
  KeyA: 'KC_A',
  KeyB: 'KC_B',
  KeyC: 'KC_C',
  KeyD: 'KC_D',
  KeyE: 'KC_E',
  KeyF: 'KC_F',
  KeyG: 'KC_G',
  KeyH: 'KC_H',
  KeyI: 'KC_I',
  KeyJ: 'KC_J',
  KeyK: 'KC_K',
  KeyL: 'KC_L',
  KeyM: 'KC_M',
  KeyN: 'KC_N',
  KeyO: 'KC_O',
  KeyP: 'KC_P',
  KeyQ: 'KC_Q',
  KeyR: 'KC_R',
  KeyS: 'KC_S',
  KeyT: 'KC_T',
  KeyU: 'KC_U',
  KeyV: 'KC_V',
  KeyW: 'KC_W',
  KeyX: 'KC_X',
  KeyY: 'KC_Y',
  KeyZ: 'KC_Z',
  Comma: 'KC_COMMA',
  Period: 'KC_DOT',
  Semicolon: 'KC_SEMICOLON',
  Quote: 'KC_QUOTE',
  BracketLeft: 'KC_LEFT_BRACKET',
  BracketRight: 'KC_RIGHT_BRACKET',
  Backquote: 'KC_GRAVE',
  Slash: 'KC_SLASH',
  Backspace: 'KC_BACKSPACE',
  Backslash: 'KC_BACKSLASH',
  Minus: 'KC_MINUS',
  Equal: 'KC_EQUAL',
  AltLeft: 'KC_LEFT_ALT',
  AltRight: 'KC_RIGHT_ALT',
  CapsLock: 'KC_CAPS_LOCK',
  ControlLeft: 'KC_LEFT_CTRL',
  ControlRight: 'KC_RIGHT_CTRL',
  MetaLeft: 'KC_LEFT_GUI',
  MetaRight: 'KC_RIGHT_GUI',
  OSLeft: 'KC_LEFT_GUI',
  OSRight: 'KC_RIGHT_GUI',
  ShiftLeft: 'KC_LEFT_SHIFT',
  ShiftRight: 'KC_RIGHT_SHIFT',
  ContextMenu: 'KC_APPLICATION',
  Apps: 'KC_APPLICATION',
  Enter: 'KC_ENTER',
  Space: 'KC_SPACE',
  Tab: 'KC_TAB',
  Delete: 'KC_DELETE',
  End: 'KC_END',
  Help: 'KC_HELP',
  Home: 'KC_HOME',
  Insert: 'KC_INSERT',
  PageDown: 'KC_PAGE_DOWN',
  PageUp: 'KC_PAGE_UP',
  ArrowDown: 'KC_DOWN',
  ArrowLeft: 'KC_LEFT',
  ArrowRight: 'KC_RIGHT',
  ArrowUp: 'KC_UP',
  Escape: 'KC_ESCAPE',
  PrintScreen: 'KC_PRINT_SCREEN',
  ScrollLock: 'KC_SCROLL_LOCK',
  Pause: 'KC_PAUSE',
  F1: 'KC_F1',
  F2: 'KC_F2',
  F3: 'KC_F3',
  F4: 'KC_F4',
  F5: 'KC_F5',
  F6: 'KC_F6',
  F7: 'KC_F7',
  F8: 'KC_F8',
  F9: 'KC_F9',
  F10: 'KC_F10',
  F11: 'KC_F11',
  F12: 'KC_F12',
  F13: 'KC_F13',
  F14: 'KC_F14',
  F15: 'KC_F15',
  F16: 'KC_F16',
  F17: 'KC_F17',
  F18: 'KC_F18',
  F19: 'KC_F19',
  F20: 'KC_F20',
  F21: 'KC_F21',
  F22: 'KC_F22',
  F23: 'KC_F23',
  F24: 'KC_F24',
  NumLock: 'KC_NUM_LOCK',
  Numpad0: 'KC_KP_0',
  Numpad1: 'KC_KP_1',
  Numpad2: 'KC_KP_2',
  Numpad3: 'KC_KP_3',
  Numpad4: 'KC_KP_4',
  Numpad5: 'KC_KP_5',
  Numpad6: 'KC_KP_6',
  Numpad7: 'KC_KP_7',
  Numpad8: 'KC_KP_8',
  Numpad9: 'KC_KP_9',
  NumpadAdd: 'KC_KP_PLUS',
  NumpadDecimal: 'KC_KP_DOT',
  NumpadDivide: 'KC_KP_SLASH',
  NumpadEnter: 'KC_KP_ENTER',
  NumpadMultiply: 'KC_KP_ASTERISK',
  NumpadSubtract: 'KC_KP_MINUS',
  AudioVolumeUp: 'KC_AUDIO_VOL_UP',
  AudioVolumeDown: 'KC_AUDIO_VOL_DOWN',
  AudioVolumeMute: 'KC_AUDIO_MUTE',
};

export function getIndexByEvent(evt: KeyboardEvent): number {
  const keycode = mapEvtToKeycode(evt);
  if (keycode) {
    return fullKeyboardMatrixKeycodes.indexOf(keycode);
  }
  return -1;
}

export function mapEvtToKeycode(evt: KeyboardEvent): string {
  return keyboardEventToKeycode[evt.code];
}
